### ISSUE TITLE
Terminal loaded scripts notification code path is never taken

### ISSUE THREAD

**Issue by BrunoQuaresma** [coder/coder#10088]

**Comment by BrunoQuaresma** [comment]
Changed this to be a feature request because I didn't find evidence that we had this before.

**Comment by code-asher** [comment]
I tweaked the title a bit to clarify the issue, basically we show a notification when the scripts are still loaded, and we have another notification that is supposed to show when the scripts do finally load.  However, that notification never appears, my guess is because we never update `lifecycleState` because we are not polling the workspace.

If we do poll the workspace, care will probably need to be taken that we do not reload the terminal unexpectedly.  Or we can listen for the lifecycle state in a different way.

But I am not sure really how much value the loaded scripts notification has anyway, so I think it would not be the worst thing to simply remove it.
