### ISSUE TITLE
Add `coder_env` so that modules can set environment variables

### ISSUE THREAD

**Issue by bpmct** [coder/coder#10166]
Currently, modules need to work around this and set environment variables in `.bashrc`

https://github.com/coder/modules/blob/47ae684f8edbcb3d48dc9dc387ed3dc80d232217/vault/run.sh#L47-L62
Also requested in https://github.com/coder/terraform-provider-coder/issues/170

**Comment by matifali** [comment]
Also requested in https://github.com/coder/terraform-provider-coder/issues/170.

**Comment by bpmct** [comment]
I'm also curious how this could be used to extend $PATH, to make commands such as `slackme` or override `make`. Any ideas @mafredri

**Comment by mafredri** [comment]
@bpmct I think the best-effort approach we can/should take is similar to what we have now, i.e. setting the environment variable before launching the shell. There will be cases where user dotfiles overwrite it, but there's not much we can do about it (except--see below).

@bpmct off the top of my head, I can think of two options:
1. Allow variable expansion (`coder_env "foopath" { name = "PATH", value = "$PATH:/tmp/foo", expand = true }`)
2. Allow prepend/append syntax for envs (`coder_env "foopath" { name = "PATH", value = "/tmp/foo", separator = ":", method = append }`)

Something we may want to consider is also including a `order`/`priority` parameter in both cases to give higher or lower priority to certain env changes. Let's say you want to prepend and ensure you're first, then set `order = 9999` or something. 😄

---

As for verifying that env changes have been applied to the workspace, one method would be to in the agent:
1. Run startup scripts
2. Have the agent run a `bash -l` that waits for a prompt and runs `env`
3. Verify the output, e.g. `PATH` includes `/tmp/foo`
4. If not, surface an error/warning in the dashboard (warning: user may be experiencing a degraded experience, the `coder_env "foopath"` resource changes are missing from their shell environment

**Comment by matifali** [comment]
I think we should keep `coder_env` simple to only inject a single or a list of individual environment variables.

A user should do the prepend/append should then be handled using a `coder_script`.

**Comment by bpmct** [comment]
I'm a fan of variable expansion. I don't think a coder_script can be used to set PATH?

**Comment by mafredri** [comment]
IMO we need either append/prepend or the ability to script it. Variable expansion can also work as an alternative _in some cases_, but not all. At least it would be a nice addition.

Let's take `PATH`, since that's an is a fairly common one to change, but also has some strict requirements.

Just look at the following example:

```
~/test
❯ echo echo hi >hi.sh

~/test
❯ chmod +x hi.sh

~/test
❯ hi.sh
zsh: command not found: hi.sh

~/test
❯ PATH=$PATH:

~/test
❯ hi.sh
hi
```

As you see, when modifying path we must ensure to never allow `::` or a preceding/trailing `:` to exist. This means that variable expansion is _not_ guaranteed to be ok. For instance `/my/path:$MAYBE_VAR:$PATH` could produce `::` resulting in the current working directory being included in the path, not good.

We need a way to ensure that if `PATH` is empty, our addition to path won't produce `:/test` or `/test:`, the `:` should be stripped.

The prepend/append + separator solves this by only inserting `:` if it's viable.

---

A completely different approach would be to allow the `script` param on `coder_env`, in which case you could write your own validation logic:

```
coder_env "my_env" {
  var = "PATH"
  script = "echo -n /my/bin; [ -n \"$PATH\" ] && echo -n \":$PATH\""
}
```

This obviously allows _any_ kind of manipulation (good), but there's a higher risk of incompatibility and/or the users shell environment messing it up unless we take precautions.

---

With these considerations, I would like implement prepend/append/separator + expansion. Thoughts/objections @bpmct @matifali?

**Comment by matifali** [comment]
@mafredri This looks a viable solution and error prone if not used correctly. My suggestion is we limit the scope for now to injecting individual variables and handle Variable append/prepend later. I want this the ability to inject lone variables sooner instead we spend more time figuring out the correct way of appending/prepending existing variables.

If we can inject all variables before the `startup_script` or any `coder_script` starts executing. The user can leverage those to append/prepend existing variables as needed (by writing to `.bashrc` or `.profile`).

**Comment by mafredri** [comment]
@matifali what did you identify as error prone in the proposed solution? As I see it the only risk is you meant to use prepend, but forgot, and as a result your var doesn't get applied.

Anyway, if you're fine with us limiting scope to static and unique variables with dynamic data only available via terraform, we can do that. It'll also be impossible to set `PATH` (perhaps we outright disallow it). I'm mostly discussing use-cases and solutions here so that we can identify the best path forward, even if we'd only implement a subset.

Another issue/use-case that also hasn't come up yet is conflict resolution. For instance, when the agent already has defined a variable, or when another module has the same `coder_env` with different data. I'd say we just discard it and log that we couldn't apply it because of X, but still.

>  The user can leverage those to append/prepend existing variables as needed (by writing to `.bashrc` or `.profile`).

Are you saying that we do this automatically in the module or the user has to manually copy paste into their `.profile` for the module to work properly?

The former I am vehemently against. Touching user files is risky and due to user configuration, our assumptions can be thrown out the window. We may break their environment, or ours might not get applied, and we have no way of knowing it. I'm mainly question why we are implementing a completely new `coder_env` feature that only fixes a subset of the issues?

The latter, well, that doesn't really seem magical to me. 🤔 Every new workspace you create requires an additional manual step to get working like the last?

**Comment by matifali** [comment]
> @matifali what did you identify as error prone in the proposed solution? As I see it the only risk is you meant to use prepend, but forgot, and as a result your var doesn't get applied.

My concern was about multiple modules injecting the same `coder_env` or a `coder_agent` overwriting them with different values. But I think you have proposed a good solution here and I agree with having an overwrite for such cases. 

> Another issue/use-case that also hasn't come up yet is conflict resolution. For instance, when the agent already has defined a variable, or when another module has the same coder_env with different data. I'd say we just discard it and log that we couldn't apply it because of X, but still. For known/common variables we're sure we want to apply, we might need a overwrite = true here.

> The former I am vehemently against. Touching user files is risky and due to user configuration, our assumptions can be thrown out the window. We may break their environment, or ours might not get applied, and we have no way of knowing it. I'm mainly question why we are implementing a completely new coder_env feature that only fixes a subset of the issues?

I agree with this and we should not touch the user files. My idea was to write docs/guides to educate users on how they can manipulate `$PATH` or other variables using user files and `coder_env` injected variables.

**Comment by mafredri** [comment]
> My concern was about multiple modules injecting the same `coder_env` or a `coder_agent` overwriting them with different values. But I think you have proposed a good solution here ⬇️ and I agree with having an overwrite for such cases.

Just to clarify, with the prepend/append, there would be no conflict because they can all contribute. And likewise, unless prepend/append is explicitly set, normal conflict resolution (first-come first-served, then discard) would apply. (And if implemented, `overwrite` would take precedence over everything else.)

> I agree with this and we should not touch the user files. My idea was to write docs/guides to educate users on how they can manipulate `$PATH` or other variables using user files and `coder_env` injected variables.

Hmm, are you talking about module-writing users, or module users? For the former, I suppose docs is sufficient (but there's a **big** advantage to allowing `PATH` manipulation via `coder_env`). For the latter, docs are not OK IMO, if using a module requires e.g. `PATH` manipulation, that won't lead to a nice user experience.

What's the big advantage? _No need for `sudo`_. Right now if you want to be sure that your module adds an executable binary in `PATH`, you need `sudo` in order to be able to write to e.g. `/usr/local/bin`. With `PATH` manipulations, you can choose any writable path like `~/.local/share/my-module/bin` without relying on `sudo`, which may or may not be present.

**Comment by mtojek** [comment]
@matifali It looks like you can start playing with this feature!

**Comment by matifali** [comment]
I would test it. Thank you 👍
