### ISSUE TITLE
bug: If `coder_parameter` with `option` does not have a default value, workspace name is cleared out

### ISSUE THREAD

**Issue by sharkymark** [coder/coder#10265]
Version: [`v2.3.0+04e6783`](https://github.com/coder/coder/commit/04e67836a500d668c0bd3c8eb825c799a893dbb0)

If I have a coder_parameter data source with multiple option items, and do not have a default value, I cannot proceed past Create Workspace and it puts the cursor in the Workspace Name field and wipes out the name I had put in there.

https://github.com/coder/coder/assets/2022166/f1ccd81e-6fa2-450f-ab3a-618411c72eae

@BrunoQuaresma @Parkreiner

**Comment by Kira-Pilot** [comment]
@sharkymark I am having difficulty reproducing this error exactly as you see it. You can check out my attempt at reproduction on dev [using my own template](https://dev.coder.com/templates/kira-10265).

It is true that I am unable to build a workspace with this template if I do not choose an option; however, I get a sensible error message (parameters are required if there is not a default set), and my workspace name is not cleared:

![Screenshot 2023-10-17 at 4 56 05 PM](https://github.com/coder/coder/assets/19142439/e494352b-d782-4dcb-b480-66105dc9a4d3)

I think we recently fix a bug with the create workspace page refreshing so maybe this got fixed in the process. Do you mind double-checking, and, if you can still see the issue, sending me your template file?

**Comment by BrunoQuaresma** [comment]
@Kira-Pilot I recently refactored a few things in the create workspace so probably it was fixed during this time.

**Comment by Kira-Pilot** [comment]
Closing as per Bruno's comment but please re-open if this is still an issue for you!
