### ISSUE TITLE
Allow transferring workspaces to another user or change email of Okta-based users

### ISSUE THREAD

**Issue by yoshi23** [coder/coder#10280]
Hi, my company had a change of domain name and users have a new email in Okta. Adding the new domain to the Okta integration will let people log in but Coder sees them as new users with their new email and their workspaces are not accessible. Is there a way to do a one-off fix for somehow make Coder aware that the new emails belong to the same people, or to update the workspaces to be owned by the new user? Thanks a lot!

**Comment by elliot-graebert-skydio** [comment]
I'd like to add a +1, but simply for the ability to transfer workstations between users. I'm fine it this requires some type of restart as part of transfer or something. The use case I ran into this week was a dev that built a cool experiment, and wanted to give it to a coworker to try from there.

**Comment by MrPeacockNLB** [comment]
From security perspective this is a no-go. Workspace are user bonded and contains secrets. Save your work and start a new fresh workspace.

**Comment by matifali** [comment]
The email address should update automatically for all OIDC accounts when there is a change in the upstream identity provider. If not, then it's a bug that needs to be fixed. There was a corner case which was fixed in #10972.

There is an open [issue](https://github.com/coder/coder/issues/10516) with syncing usernames for OIDC provisioned accounts additionally.
