### ISSUE TITLE
Ability to recover from aborted TF operations

### ISSUE THREAD

**Issue by denbeigh2000** [coder/coder#10318]
# Background

When running Coder in k8s (via the provided Helm chart), it's possible for pods to be lost/replaced while they are executing operations (when workspaces are being started/stopped).

When this happens, the logs for the operation the pod was undertaking abruptly cut off, and the operation is displayed in the UI as failed. However, any resources that are created during this operation do not get tracked/destroyed, which can leave the workspace in an inoperable state.

# Scenario
This is what happened in our specific case:
- Coder kicked off an auto-start of (at least) 2 workspaces
- A pod running 2 of the operations went away (for whatever reason).
- In the UI, those builds showed as failed with a runtime of 60s, leaving their workspaces "not running" (their logs just stop after a certain timestamp)
- These devs attempted to start their workspaces, and the Terraform operations failed because there were already resources with the expected names.
- Admin had to manually intervene to delete these resources from the cloud console to allow the operations to succeed.

# Ask
This kind of failure should be recoverable without intervening via the cloud console.
Some potential thoughts on what the product can do here:
- Good: Coder exposes a manual "stop" button after failed ops, so the "stopped" tf state can be applied
- Better: Coder automatically/optionally tries a "stop" before its' "start" when restarting failed workspaces
- Best: Coder detects that the coderd node has gone away, and performs mitigations to get to the intended state without the dev needing to intervene.

**Comment by sreya** [comment]
So the issue from what I understand is that if TF detects resources that exist in your infrastructure that don't exist in your TF state then it'll abort the operation since it doesn't want to accidentally claim ownership over something unrelated to TF. The only real way to fix this is to use [terraform import](https://developer.hashicorp.com/terraform/cli/import) to update your state to match the reality of your infrastructure (or manually delete the resources). We update the state of a workspace regardless of whether we fail or succeed so one of the only ways to get a terraform mismatch is if your `coderd` pod gets killed before the state can be updated for a failed build. 

We do have support for [failure cleanup](https://coder.com/docs/v2/latest/templates/schedule#failure-cleanup) now but it's more of a cost-saving measure where things may fail because your cloud experienced some transient error that terraform can recover from.
