### ISSUE TITLE
OVH cloud provider template

### ISSUE THREAD

**Issue by iliachesnokov** [coder/coder#10401]
Greetings!

On the main page of the documentation for v2, there is an OVH cloud logo in the picture with providers, but I could not find a template for launching a workspace on OVH cloud.

Is there a common example template planned for OVH cloud? This is a very cool public cloud service provider and I would like to use it with the equally cool Coder.

Thanks in advance for your answer!

**Comment by stirby** [comment]
We don't really have the bandwidth to create this right now, we may revisit in the future!

**Comment by matifali** [comment]
@phorcys420 if you see any interest from the community feel free to reopen.

**Comment by phorcys420** [comment]
I have tried it but basically there are two options:
- Use their managed k8s offering
- Spawn a VPS per user 

The first option will work out of the box with our Kubernetes template.
The second option was a lot of effort and didn't seem easily doable due to the lack of cloud-init support on their end which made it so that you had to use SSH to start the agent.

cc: @matifali
