### ISSUE TITLE
Make the SSH key from `coder gitssh` usable with SSH

### ISSUE THREAD

**Issue by Gaming4LifeDE** [coder/coder#10487]
I think there should be a way to use the ssh key provided with 'coder gitssh' with the normal ssh command. A possible solution would be to add the private key to the ssh agent on workspace creation.

**Comment by kylecarbs** [comment]
The SSH agent is not particularly standardized from my perspective, especially across operating systems.

You could use a Module for this: https://github.com/coder/modules

**Comment by evilhamsterman** [comment]
@kylecarbs I'm not sure how using a module would help for this ask. I think @Gaming4LifeDE is asking that there be a way to either access the private key that corresponds to the one in your account i.e. `coder publickey` so it can be added to a `ssh-agent` running in the workspace. Or perhaps have `coder` provide a ssh agent socket that can be set with `$SSH_AUTH_SOCK`

**Comment by evilhamsterman** [comment]
@kylecarbs the ssh agent protocol is actually on a standards track now https://datatracker.ietf.org/doc/html/draft-miller-ssh-agent

**Comment by kylecarbs** [comment]
@evilhamsterman could you expand on the use case you're looking to solve here? I've seen in specific Enterprise situations where SSH keys are preferred, but for the vast majority of our customers temporary access tokens using our Git Auth is much preferred.

**Comment by evilhamsterman** [comment]
If only we used GitHub for everything, but we have some internal legacy systems that use Mercurial and rely on SSH keys for repository access plus tooling built around it that it will be a large project to move off of, if/when we can even get resources devoted to the project. 

Until then I have to get SSH keys into our users workspaces with a mix of VIM and VSCode users. Agent forwarding works with the `coder ssh` command but that only helps my VIM users, I don't see documentation on how to forward an agent with VSCode short of also running `coder ssh` which is not optimal. We obviously don't want them to have to generate a new key for every workspace.

Since Coder already generates and assigns a key to each user, if that was made available in the workspace through the standard ssh-agent protocol then we could just easily consume that. Potentially we could even build automation into the tooling to retrieve user keys from Coder. I could add the key to the agent myself but there doesn't appear to be a way to retrieve the private key from coder, which frankly is a good thing. Which is why it would nice if Coder itself provided an agent socket.

Another potential use case, not one that applies to us but I could foresee, is for using with tools that use SSH like Ansible, rsync, sftp.

**Comment by evilhamsterman** [comment]
@kylecarbs More on the ssh-agent protocol is supported by the golang crypto package https://pkg.go.dev/golang.org/x/crypto/ssh/agent making agent support easier. I was also looking at how your gitsshkey is implemented and I think it would probably be a better idea to just drop that and provide the ssh-agent instead. It looks like the code currently writes unencrypted private key to disk https://github.com/coder/coder/blob/f1b42a15fa1c10ee122a116cf4eb6b2f37f2f829/cli/gitssh.go#L58, which however short could lead to a leak, say if the disk is snapshot while the key is resident there. It's a small chance but it's a possibility.

If instead you just provide an ssh-agent socket that can be used by anything including git, and the private key never has to leave memory.

**Comment by kylecarbs** [comment]
I think it'd be better if someone created a small external binary user to pull the SSH key from the Coder and run an SSH agent.

The abstraction of our agent in regards to SSH is already a bit too fluffy (e.g. are we eventually implementing all of OpenSSH? 🤮).

**Comment by evilhamsterman** [comment]
To run an external binary would require an API to grab the private key. I did manage to find the API myself but it's not a documented part of the normal API, I had to review the source to find it.

I think making it part of your agent is a good idea because it is one less thing to deal with, it makes your key easily accessible by most tools that would use it, and it would be more secure than your current implementation for Git. I would drop the Git only code if you implemented the agent. You already have most of the parts in place, you have an agent running, you set environment variables so adding `SSH_AUTH_SOCK` is easy, the only part missing is opening a socket and attaching to it. Implementing the agent is pretty easy with the Go library, I was able to try it in just a few lines. 

I'm not sure when I can get to it, but I could see about a PR.

**Comment by evilhamsterman** [comment]
@Gaming4LifeDE You can get the private key now through the latest Coder Terraform provider if you are also using Coder 2.12. You can then use that to insert it in a coder_script, Kubernetes Secret, something else to add it to a regular ssh-agent.

**Comment by bpmct** [comment]
No plans for this at this time, we're happy to accept contributions or a module in the Coder Registry: https://registry.coder.com
