### ISSUE TITLE
Compatibility for on different Android versions?

### ISSUE THREAD

**Issue by eugene-yh** [coder/coder#10512]
There seems to be no official releases of coder for Termux on Android devices. However, `coder ssh` seems working fine on my Android 12 device (though with a warning, see the first screenshot), so it is kind of okay. But, my new phone is Android 13, and `coder ssh` throws an exception about network permission (see the second screenshot) and fails to connect to my workspace.
![Screenshot_20231103-222950_Termux](https://github.com/coder/coder/assets/52963371/83b2d3b2-5ad4-45c1-b69f-a94f481b6cc7)
![Screenshot_2023-11-03-22-40-23-30_84d3000e3f4017145260f7618db1d683](https://github.com/coder/coder/assets/52963371/c96e1f49-27dc-42eb-afbb-8bd5e039f32f)

I did some research and the network permission issue (caused by more strict security policy of newer Android versions) seems resolvable by making some modifications the network interface in Go. See [this](https://github.com/ipfs/kubo/issues/9513) as a reference.

I wonder if you guys can at least make `coder ssh`usable for termux on latest Android devices. It would be even better if all utilities are compatible.

**Comment by kylecarbs** [comment]
Are you building the Go binary for Android?

**Comment by kylecarbs** [comment]
If so, then I can really easily enable a workflow for this.

**Comment by kylecarbs** [comment]
I've gone ahead and created a PR that fixes this: https://github.com/coder/coder/pull/10515

Depending on how you're running this Coder binary I might have to change how it works.

**Comment by eugene-yh** [comment]
> I've gone ahead and created a PR that fixes this: #10515
> 
> Depending on how you're running this Coder binary I might have to change how it works.

Thanks in advance! I really appreciate it.

My minimal requirement is that I can run `coder ssh` to connect to my workspaces on latest Android devices. As for the coder binary itself, both building it myself from source or using a prebuilt release are okay to me.

**Comment by spikecurtis** [comment]
Hi @eugene-yh 

Unfortunately, we've decided not to merge #10515 as it complicates our integration with tailscale. That's just not a cost we're willing to bear for Android, since we don't have any plans to officially support it and don't have testing for it.

I expect that if you grab the branch from that PR and fork it to your own repo, you will be able to build a coder binary that works with Termux.

**Comment by TECHNOFAB11** [comment]
Just a quick note, I tried to get it working with NixOnDroid which is based on Termux. Even with a lot of modifications and with the anet package it's not possible to get it working. Netlinkrb is completely off limits on new android versions and always causes a permission denied. 
Tailscale's Android app just works because they call Kotlin code which in turn calls Android apis to get the network interfaces.

So for now the only way is to use the Web terminal. Theoretically it should be possible to build an Android app which uses the websocket connection of the Web terminal or add some functionality to the coder cli to ssh via the coordinator and not use tailscale. But that's probably OOS cuz Android is not supported. 
A way to ssh with the coder username and some personal access token would be cool though (also proxying through the coordinator)
