### ISSUE TITLE
feat: Workspace preview in the template dashboard should reflect `display_apps` configuration

### ISSUE THREAD

**Issue by sharkymark** [coder/coder#10635]
Version: [`v2.3.3+e491217`](https://github.com/coder/coder/commit/e491217a12abd3a00f5ed247f23f104732883c90)

With the release of `display_apps` to give configurable control over built-in buttons/apps, the preview in the template dashboard should show them to accurately tell the developer what the workspace will look like.

![image](https://github.com/coder/coder/assets/2022166/80157fac-154e-4638-97a9-474fa86d9652)

```hcl
  display_apps {
    vscode = false
    vscode_insiders = false
    ssh_helper = false
    port_forwarding_helper = false
    web_terminal = true
  }
```

```hcl
# code-server
resource "coder_app" "code-server" {
  agent_id      = coder_agent.dev.id
  slug          = "code-server"  
  display_name  = "code-server"
  icon          = "/icon/code.svg"
  url           = "http://localhost:13337?folder=/home/coder"
  subdomain = false
  share     = "owner"

  healthcheck {
    url       = "http://localhost:13337/healthz"
    interval  = 3
    threshold = 10
  }  
}
```

**Comment by Kira-Pilot** [comment]
@sreya There's not currently a great way to implement this on the FE because `agent.display_apps` appears to be just a [list of strings](https://github.com/coder/coder/blob/main/coderd/database/models.go#L342) rather than a list of app ids. There doesn't seem to be a definitive look-up between the two (am I missing something?) - right now, the workspace page logic uses branching and hard-coded strings to manually check whether each button should be shown. 
We can't take the same path in the `AgentRowPreview` because [we are mapping over a list ](https://github.com/coder/coder/blob/main/site/src/components/Resources/AgentRowPreview.tsx#L90)of apps.

It looks like the `display_app` list might be an informal list of `WorkspaceApp.slugs`. For now, I will use the app slug to look up whether the app should be displayed or not.

In the future, we should probably relate these two models on the BE because the current approach is a bit fragile.
