### ISSUE TITLE
bug: can't load daily insights

### ISSUE THREAD

**Issue by mtojek** [coder/coder#10784]
Steps to reproduce
1. Go to insights.
2. Select "Daily"
3. Select a random day range, for example: Nov 1- Nov 20.
4. Result

<img width="1266" alt="Screenshot 2023-11-20 at 10 36 04" src="https://github.com/coder/coder/assets/14044910/56e49637-f8cc-41d7-814c-59c47c7aee7b">

I guess that it depends on the user location, but for me backend complains about the future timestamp.

<img width="1065" alt="Screenshot 2023-11-20 at 10 47 18" src="https://github.com/coder/coder/assets/14044910/58484492-4468-4d8e-a349-9445fef3d72d">

**Comment by mafredri** [comment]
Seems the dashboard is requesting the wrong timezone. It's using `-02:00` instead of `+02:00` for me.

**Comment by matifali** [comment]
I noticed this in #10624, but suddenly, it was not reproducible. I guess it happens when 5th November, the DST change date, is within the selected interval.

**Comment by mtojek** [comment]
Also, can we modify the Insights page to show the error somewhere in the UI?

**Comment by mafredri** [comment]
The underlying cause for this bug is the `isPositive` check added in https://github.com/coder/coder/commit/645c4bd6123dd98791483f78b4ad352b27df363d. The assumption is that positive means we request a positive timezone, but it's actually the other way around, as per: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/getTimezoneOffset

**Comment by BrunoQuaresma** [comment]
I would rather have the BE taking care of these specific things and rules, is that possible @mafredri ?
