### ISSUE TITLE
Weird behaviour for autostop setting

### ISSUE THREAD

**Issue by fcsonline** [coder/coder#10841]
Since the `2.4.0` version, the autostop setting doesn't work as expected. After reviewing the [pull request](https://github.com/coder/coder/pull/10704/files) where all these changes were introduced, there are some copies in the UI that doesn't make sense.

![image](https://github.com/coder/coder/assets/135988/97b95614-166f-4c7c-8178-341e53ccf709)

The meaning of this setting has shifted a lot since these changes. Many developers in our team were confused by this change, because if they take a break longer than one hour (lunch break), they find out later their machines stopped, even if they worked few minutes before.

**Comment by bpmct** [comment]
Hey! Sorry you ran into this, I agree we need to update our copy here. [Our changelog[(https://github.com/coder/coder/releases/tag/v2.4.0) also describes this behavior more accurately.

To summarize, with the screenshot you attached. The real behavior is:

- Coder keeps the workspace alive for the first 4 hours
- After that, Coder will bump by 1 hour to keep the workspace active

We have considered making the second bump period configurable again (e.g. workspace is alive for the first 8 hours, bump by 2 hours instead of 1). The rationale behind our change in v2.4.0 is that many of our customers wanted to set this for a longer duration (e.g. 8 hours) to guarantee a workspace stays alive from 9-5 but didn't want to continue bumping by that same large period.

**Comment by fcsonline** [comment]
I totally understand the rationale for long periods, but for short periods, it is a bit misleading. Also, the +1 hour looks a bit arbitrary. Just because the scenario I mentioned before about lunch time. Having a new setting to configure the bump it would be awesome and it would solve both cases.

And sorry to bother you with this but the fact that this setting has changed the behavior so noticeable, just surprised our team, because some team members have found their workspaces stopped (after lunch, a meeting, etc.)

**Comment by sharkymark** [comment]
@fcsonline I can add some color - the auto bumping of `x` hours (the off setting) was causing significant cloud spend for some customers, which was part of the rationale for the `1` hour instead, which was the original functionality last year.

Sorry we didn't make it clear, and thanks for the candid feedback.

**Comment by fcsonline** [comment]
If we have this option to configure the bumping hours ("Grace period"), we will be able to set up the same behaviour as before.

Something like this will cover our case (short periods):
<img width="1040" alt="image" src="https://github.com/coder/coder/assets/135988/10773846-996f-41e7-b852-fb27c379b7bd">

And also, your case (long periods):
<img width="1035" alt="image" src="https://github.com/coder/coder/assets/135988/db3521b0-acbb-41aa-8bd2-9cf45dc005fa">

**Comment by fcsonline** [comment]
Do we have some news about this? We continue facing this issue and, this "Grace Period" setting would solve it.

**Comment by stirby** [comment]
This has been implemented as "Activity Bump" in the template settings. You can set N hours to bump the workspace deadline by whenever activity is detected.

**Comment by fcsonline** [comment]
Thank you so much!
