### ISSUE TITLE
bug: `route not found` for groups section of Account UI

### ISSUE THREAD

**Issue by sharkymark** [coder/coder#10871]
Version: [`v2.4.0+d19a762`](https://github.com/coder/coder/commit/d19a762589e84afd18f2245ebc03daccb53cb13f)

I just did a fresh install of Coder and when I went to the Account UI to create a long-lived token, I received this.

![image](https://github.com/coder/coder/assets/2022166/7882a6a0-4bc2-4f57-9cca-6cb3f1b44cc2)

**Comment by BrunoQuaresma** [comment]
I think this is caused because this Coder deployment does not have an enterprise license, so the API route for groups in the BE is not enabled. @Parkreiner we need to check if the user is entitled for the groups feature, if yes, we should display this section if not, we just don't do anything. Makes sense?
