### ISSUE TITLE
Audit log page makes unncessary API requests

### ISSUE THREAD

**Issue by deansheather** [coder/coder#11016]
Changing the page number on the audit logs page on the dashboard sends multiple requests to the backend for audit log entries.

It seems like it requests the previous page, the current page, and the next page. The following screenshot were the requests sent after clicking on page 2:
![image](https://github.com/coder/coder/assets/11241812/036884ff-e9ca-424d-b3a4-478f92b23bcb)

The audit log endpoint is not cheap so we should not be hitting it unnecessarily. If the frontend actually does need 75 entries then it should probably just set the limit query param to 75.

**Comment by matifali** [comment]
@Parkreiner would it be resolved with your current work around improving pagination?

**Comment by Parkreiner** [comment]
Actually, to be honest, this was *caused* by the tools I had set up for pagination. The prefetch requests are getting made to help ensure that the pages have data by the time the user clicks the next page. I didn't realize the audit queries were so expensive, though

Two fixes I can make this morning:
1. Make it so that it's easy to turn prefetching off, especially for pages where the queries are expensive – without having to toss out the other pagination niceties
2. Beef up the logic for prefetches so that it checks the staleness of the data better before deciding to make a new prefetch
