### ISSUE TITLE
Allow parameter updates through CLI to up-to-date workspaces

### ISSUE THREAD

**Issue by stirby** [coder/coder#11111]
Currently, the `coder update --parameter` command is only allowed on workspaces that have an template update available. This appears to be the only way to change workspace parameters through the CLI, so blocking the action for updated workspaces is not idiomatic.

The docs indicate that `coder update` is used to apply changes to out-of-date workspaces, but the requesting customer indicated that the `coder update --build-option` does not have the same limitation. If there's a reason for the `update` command to only apply to out-of-date workspaces, we should make it consistent, otherwise this should be unblocked.

**Comment by sreya** [comment]
Why not use `coder start --build-option ... --parameter`?

**Comment by stirby** [comment]
From requesting customer: 

The use-case for this is to apply a parameter update that triggers on the next restart, so `coder [start|restart] ...` is not viable.

**Comment by bpmct** [comment]
Bringing this as a candidate into our next sprint, I agree the flags should be unified here

**Comment by defelmnq** [comment]
As I started to investigate to resolve this one - I just want I'm missing nothing.

From my understanding, the comand `coder update` currently applies instantly : 
- If the workspace is running, the template will be rebuild with the new parameters (if any) and new version. The workspace will then be restarted.
- If the workspace is stopped, it will be started with the new version & parameters.

Discussing with @stirby , seems like the customer (and expected behavior) is to save the new parameters and only apply then while manually starting / restarting the workspace.

If everything above is true : 
- Either we want to verify how to implement the behavior described by the customer and this is something new.
- Either we want to allow the `--parameter` option and the workspace will be (re)started applying the new parameters.

**Comment by sreya** [comment]
The motivation is to be able to update build parameter inputs across many workspaces without spawning a ton of jobs.

**Comment by dannykopping** [comment]
I believe the problem here is stemming from a terminological issue.

A workspace is based on a template (more specifically a template _version_). When a template changes, a new version is created and any workspaces which reference this template but not the new version are marked as out-of-date and an `update` can now be applied.

**Updating a workspace which is already up-to-date is therefore _semantically invalid_.**

> Currently, the coder update --parameter command is only allowed on workspaces that have an template update available. This appears to be the only way to change workspace parameters through the CLI, so blocking the action for updated workspaces is not idiomatic.

This is untrue; it can be achieved using `coder restart --parameter`. In order to update a workspace parameter, the workspace must first be stopped, and a new build request issued with the given set of parameters.

We could consider introducing a new (more semantically clean) command like `coder reconfigure` for example which behaves like `coder restart`.

Therefore, I think we could resolve this issue by doing the following:

a) when `coder update --parameter` is executed for a workspace which is up-to-date, simply fail saying that the workspace is up-to-date, and to instead use `coder restart --parameter` or option _b_ below
b) if a `--force` option is supplied to the `coder update` command, execute it as if it's an alias for `coder restart`

> The use-case for this is to apply a parameter update that triggers on the next restart

I think this is new behaviour and makes the workspace build process more complex & unpredictable.
Our model currently is quite conceptually simple: at the time of build, specify all of the inputs for the build including parameters and "build options" (i.e. ephemeral parameters) in the request.

**Comment by sreya** [comment]
@dannykopping I don't really understand adding a `--force` parameter, that doesn't address the spirit of the problem here. This ticket should basically decide whether we plan on supporting a way to provide parameters that doesn't _also_ kick off a build. Our schema doesn't really support doing that so it'd be a bit of a refactor. I'd prefer we just close the issue if it's something we decide we don't want to support.

**Comment by dannykopping** [comment]
> This ticket should basically decide whether we plan on supporting a way to provide parameters that doesn't _also_ kick off a build.

I personally don't get that requirement from the initial report. @stirby could you add more detail around this, please?
Given that parameters are only used in the context of workspace builds, I struggle to understand why we'd want this.

If we want users to be able to set parameters in advance of a subsequent workspace build, I think that'll add some sharp edges. For example: will that parameter just be used for the next build? How does this show up in the CLI/web UI when building a workspace? What if the template changes and invalidates this parameter setting? Will it apply for all workspaces using this template, or only some?

Without more context and a compelling/broad use-case, I would vote for closing this issue.

**Comment by bpmct** [comment]
Closing this for now... I'm not super interested in expanding this at this point if we can't land on a good design for the use case
