### ISSUE TITLE
Allow new RemoteForward to override existing RemoteForward in Coder Agent

### ISSUE THREAD

**Issue by spikecurtis** [coder/coder#11198]
If a client that is SSH `RemoteForward`ing from their workspace is abruptly disconnected, the SSH server isn't immediately notified because the TCP sessions can be held open for a long time (currently 72h), and we currently block other SSH connections from `RemoteForward` the same target Unix socket path (and TCP port).

This can put the workspace in a state where RemoteForward no longer works unless they restart the workspace or the old TCP session times out.

Since Coder workspaces (unlike a general SSH server) are meant for a single user, we could fix this problem by allowing new connections to override previous `RemoteForward` requests.  The target would begin forwarding to a new connection that requests it and cease forwarding to the old connection.

We have a customer trying to configure remote forwarding to happen by default, and blocking remote forwarding based on a failed, old connection is making this unusable.

**Comment by bpmct** [comment]
related https://github.com/coder/coder/issues/6672

**Comment by mafredri** [comment]
After some more testing I wasn't able to re-produce the graceful handover I thought I initially identified with OpenSSH. On consequent tries I observed the following behavior:

1. Connection 1 creates `/tmp/sock`
2. Program 1 uses `/tmp/sock`
3. Connection 2 overwrites `/tmp/sock`, program 1 connection is uninterrupted
4. Program 2 uses `/tmp/sock`
5. Connection 2 closes, program 2 connection is interrupted
6. Program 3 cannot use `/tmp/sock` because connection 2 is closed

A similar behavior should be possible to implement, we just need to keep the listeners open as long as the sessions are too (irrespective of the socket file disappearing).

**Comment by spikecurtis** [comment]
Yeah, I think there can only be one SSH session that handles each connection to the forwarded socket.  Mirroring the traffic over multiple sessions makes no sense because a connection is bidirectional: sure you could write data to both sessions, but how do you merge the reads?

I agree it would be nice to just override the listener without affecting any connections in progress.
