### ISSUE TITLE
bug: Logo URL in Appearance dashboard does not explain that it also updates the logo on the Sign In page

### ISSUE THREAD

**Issue by sharkymark** [coder/coder#11345]
The help text for the Logo URL in Appearance dashboard does not correctly explain that it also updates the logo at the top of the Sign In page. It does update the logo at the top left of the main dashboard too.

<img width="1216" alt="image" src="https://github.com/coder/coder/assets/2022166/cdf66cf5-0606-4139-889a-38d5a651c15d">

<img width="404" alt="image" src="https://github.com/coder/coder/assets/2022166/e6924c96-87a6-4660-a017-1d77a6fdd7fb">

This a second issue, but changing the Application Name in the Appearance dashboard does not change anything on the Sign In page.

**Comment by matifali** [comment]
What do you suggest as the solution? Improve the wording or suport separate logos for both places?

**Comment by sharkymark** [comment]
The helper text needs to mention this name also updates the sign in page

The second issue is a bug I think - if you want to test.  Changing that text did nothing to my sign in page.

**Comment by f0ssel** [comment]
Went ahead and made a fix for the wording in https://github.com/coder/coder/pull/11377. I can look at the Application Name issue if product believes this is a bug but unfamiliar with the decisions and changes when they were made so I don't want to jump to conclusions that something needs fixing there.

**Comment by f0ssel** [comment]
So I looked into this further and the application name is only used on the frontend to provide an `alt` image text to the sign in page logo. https://github.com/coder/coder/blob/f0ssel/templatepush-2/site/src/pages/LoginPage/LoginPageView.tsx#L35 

**This means the Application Name would only be displayed if the image failed to load or if the user is using a screenreader.** 

This code looks pretty intentional, so I'm going to assume it isn't a bug but that the wording under this field is also slightly confusing. So I propose:
1. Fix the wording to make it clear it's only used for fallback if the image cannot load.
2. Make some frontend design changes to include the application name on the sign in page somewhere that isn't as hidden as image alt text. 

I probably am not the best at the design change part but can implement whatever the frontend team would like to do. 

CC @BrunoQuaresma @matifali

**Comment by BrunoQuaresma** [comment]
Just to take into consideration: A few customers shared that they found the old heading "Sign in to Company Name" quite overwhelming and I kinda agree with that. That was the reason why I simplified it in the last sign-in page refactoring.

We should improve the settings page where the user can upload the logo and let the user decide what they want to do:
- [ ] Display logo on the sign-in page
- [ ] Display logo on dashboard top left 
- [ ] Use the company name on the sign-in page

**Comment by f0ssel** [comment]
@BrunoQuaresma Do you think those same companies would fine the default "Sign in to Coder" overwhelming? I can see why someone settings it to "CartoonNetwork" might find "Sign in to CartoonNetwork" confusing, but I feel like the default should be sane enough to no need another toggle switch IMO.

**Comment by BrunoQuaresma** [comment]
@f0ssel yeap, I'm going to share it with you privately.
