### ISSUE TITLE
X11 forwarding not working with `ssh -X` session

### ISSUE THREAD

**Issue by ericpaulsen** [coder/coder#11531]
experienced on `2.6.0` - repro steps:

1. Download XQuartz (X client for Mac) to local Mac
2. Start Coder workspace (K8s pod), install `xauth` via `sudo apt-get update && sudo apt-get install -y xauth`
3. Authenticate to Coder via `coder login`
4. Run `coder config-ssh` to config local SSH config file
5. Run `ssh -X coder.<workspace-name>`
6. Run `xeyes` (install via `sudo apt-get install -y x11-apps`)
7. Observe XQuartz application opening, but no window appears

**Comment by mafredri** [comment]
This problem is due to us not managing `xauth` properly.

If you forward once, you're fine:

```
❯ ssh -X coder.w

coder@w ~
❯ xauth list
w/unix:0  MIT-MAGIC-COOKIE-1  4e41a3c0aa69172ca2438c185e7f5262
```

But the second time you do it, there will be two entries:

```
❯ ssh -X coder.w

coder@w ~
❯ xauth list
w/unix:0  MIT-MAGIC-COOKIE-1  4e41a3c0aa69172ca2438c185e7f5262
w/unix:0  MIT-MAGIC-COOKIE-1  635ea6298f18b17453ce613ed04ea438
```

The first one will be used, and thus, authentication fails.

The issue can be worked around by running `xauth remove w/unix:0` inside the workspace, then reconnecting with `-X` (`ssh -X coder.w`).

To fix this, we should remove the entry from `.Xauthority` on disconnect, and if present, remove or update the magic cookie.

**Comment by ericpaulsen** [comment]
@mafredri - thank you. I confirmed the problem and validated the forwarding works with a single magic cookie entry.
