### ISSUE TITLE
coder_parameter doesn't support monotonic for option values

### ISSUE THREAD

**Issue by mattlqx** [coder/coder#11579]
Would it be possible to support `monotonic` validation on parameters that use options that have numeric values?

I have a 3 volume size options on my template. Sizes can't be effectively reduced. It would be nice if the setting could be validated so that selecting a smaller one than current would fail validation. e.g.

```
data "coder_parameter" "home_volume_size" {
  name        = "Home Volume Size"
  description = <<-EOF
  How large should your home volume be?
  EOF
  default     = "300"
  mutable     = true
  order       = 3

  option {
    name  = "300 GB (Default)"
    value = "300"
  }

  option {
    name  = "600 GB"
    value = "600"
  }

  option {
    name  = "1 TB"
    value = "1000"
  }
}
```

I would like it to also support the block:
```
validation {
  monotonic = "increasing"
}
```

**Comment by matifali** [comment]
Hi @mattlqx do you have any issues while setting it. O think it should work of you also set the `type = "number"`. 
Or you need string values you can later use the [`tostring()`](https://developer.hashicorp.com/terraform/language/functions/tostring) function where you use this parameter.

**Comment by mattlqx** [comment]
The problem seems to be actually that `options` don't support `validation`.

```
2024-01-12 20:47:07.520Z Error: Conflicting configuration arguments
2024-01-12 20:47:07.520Z on params.tf line 77, in data "coder_parameter" "home_volume_size":
2024-01-12 20:47:07.520Z   77: data "coder_parameter" "home_volume_size" {
2024-01-12 20:47:07.520Z 
2024-01-12 20:47:07.520Z "validation": conflicts with option
```

That's with the following attributes:
```
  default     = "300"
  mutable     = true
  type        = "number"

  option {
    name  = "300 GB (Default)"
    value = "300"
  }

  option {
    name  = "600 GB"
    value = "600"
  }

  option {
    name  = "1 TB"
    value = "1000"
  }
```

**Comment by matifali** [comment]
We should definitely support monotonic type validation for options with type number. 

cc: @coder/pms @mtojek

**Comment by mtojek** [comment]
I second what Matt said about the problem. 

Coder enables validation for number fields, but since there are options provided, it assumes that it does not need [advanced validation](https://github.com/coder/coder/blob/054420bb33e1997ae2a378c46eab587733f7fce3/codersdk/richparameters.go#L98C1-L99C1). Hence there is a [type conflict](https://github.com/coder/terraform-provider-coder/blob/main/provider/parameter.go#L238). It is aligned with the initial design of Coder parameters which assumed that parameter options are only strings.

This issue is kind of a whack-a-mole challenge. Fix all places, hopefully only in Coder, until it works correctly.
