### ISSUE TITLE
Prometheus metrics aggregator pegging coderd CPU and potentially causing OOM kill

### ISSUE THREAD

**Issue by mafredri** [coder/coder#11775]
In the latest scale test, we ran into coderd restarts and upon inspecting logs, we saw that the OOM killer was summoned, that we saw _a lot_ of log messages from the aggregator: `update queue is full`.

As can be seen from these graphs, both CPU and memory usage spikes coincided with the restart(s).

<img width="1054" alt="image" src="https://github.com/coder/coder/assets/147409/e0855faa-76ba-4dde-ba0f-383a8911caa4">

What can also be observed above is that one coderd instance had it's CPU pegged, upon CPU/trace inspection, the finger is once again pointed towards the aggregator:

<img width="3199" alt="image" src="https://github.com/coder/coder/assets/147409/a80ff8d9-d7bd-43eb-aaa2-9acc513b844d">

The same is shown in the CPU profile:

<img width="511" alt="image" src="https://github.com/coder/coder/assets/147409/b7b848d9-cf13-4fc8-9cf3-aa8d7b613628">

One code-path that's being executed for a while (as shown in the trace above), is this loop: https://github.com/coder/coder/blob/369821ea19442bdb3a3c176baacd76b6e678b240/coderd/prometheusmetrics/aggregator.go#L156

// ping @mtojek for insights since you worked on the initial feature.

**Comment by spikecurtis** [comment]
One thing that I noticed is that we keep the metrics in a slice and do linear searches thru the slice to update metrics.  So updating our metrics becomes quadratic in the number of metrics.  We should consider putting them in a map.

**Comment by mtojek** [comment]
Thanks for posting graphs, @mafredri!

I have noticed a few things we could improve.

1. Size of [updateCh](https://github.com/coder/coder/blame/f5dbc718a76bafe5c674a89bbe39111ebca62f45/coderd/prometheusmetrics/aggregator.go#L27) is 1024. If 2000 users are using their 2000 workspaces, then we can see metrics being rejected. My first thought was to increase the limit to 4096, but... go to point no. 2.

2. I'm concerned about the memory increase, so I reviewed the changes we applied since I pushed the original implementation.

The original implementation uses a relatively simple [annotatedMetric](https://github.com/coder/coder/blob/bb0a38b161b743297b06b5d5258a1f3594dca1e1/coderd/prometheusmetrics/aggregator.go#L53-L61) structure. The [next PR](https://github.com/coder/coder/pull/10811) modified it to use a [proto structure](https://github.com/coder/coder/blob/cc152b52700936e9e2e97836d15ef51f1d33aa4a/coderd/prometheusmetrics/aggregator.go#L57-L66) instead. I don't know if we need the proto structures in the aggregator, and whether they were introduced on purpose.

> One thing that I noticed is that we keep the metrics in a slice and do linear searches thru the slice to update metrics. So updating our metrics becomes quadratic in the number of metrics.

I might be wrong, but metrics are intended to be kept in the aggregator state for [2 minutes](https://github.com/coder/coder/blob/cc152b52700936e9e2e97836d15ef51f1d33aa4a/coderd/prometheusmetrics/aggregator.go#L30). A map can improve performance of updating, but we still need to deal with the OOM issue.

3. Do we want to introduce an upper limit of the number of metrics kept in the metrics aggregator state to save the application from restarting/OOM?

**Comment by mafredri** [comment]
After the latest test, it seems unlikely that the aggregator caused OOM. The aggregator is not visible in the stack, and it's allocations look pretty OK to me:

<img width="300" alt="image" src="https://github.com/coder/coder/assets/147409/ce2ff052-f520-4d8d-bc8d-011666762d0e">
<img width="300" alt="image" src="https://github.com/coder/coder/assets/147409/56391d6f-5694-42c0-bee0-634bd5437fb8">

See also #11797

**Comment by mtojek** [comment]
> I believe we should focus on CPU usage in this issue.

I see 👍 I can do the first step and refactor the structure to use maps.

**Comment by mtojek** [comment]
@mafredri I have addressed performance-related findings. Should I resolve this issue or would you like to start another load test?

**Comment by mafredri** [comment]
@mtojek I'd say it's resolved, thanks for fixing the issue! I'll add this to a list of fixes-to-be-verified in follow-up scale tests.

**Comment by mtojek** [comment]
Alright! Let's reopen it if it doesn't help.
