### ISSUE TITLE
Time until autostart not indicated on dashboard

### ISSUE THREAD

**Issue by stirby** [coder/coder#11781]
From scheduling discussion.

The workspace dashboard doesn't indicate when the time to next autostart. A great UX improvement would be to show directly on the workspace page "Autostart in X hours" much like how Autostop is shown.

<img width="591" alt="autostart_display" src="https://github.com/coder/coder/assets/58410745/14ef028b-aecc-48bb-81f0-0769fd38cbad">

Distinction between autostart and autostop advisements can be increased with a unique icon (something like a sunrise?).  

This message should be entirely omitted on workspaces without autostart configured.

**Comment by matifali** [comment]
Good feedback. Something like "Next auto start in X hours" would be helpful.

**Comment by BrunoQuaresma** [comment]
We probably need some BE work on this to return this information. We probably want also to add the reason like:
```json
{
   // ...workspace
   stops_at: { time: "2024-01-02 13:00:00", reason: "autostop" }
   starts_at: { time: "...", reason: "..." }
}
```

**Comment by BrunoQuaresma** [comment]
cc.: @mtojek

**Comment by BrunoQuaresma** [comment]
@aslilac is this related to your recent schedule work at all?

**Comment by aslilac** [comment]
> is this related to your recent schedule work at all?

no, I just barely merged those changes.

---

we already have the autostop and autostart info available on the client side, but we intentionally hide the autostart status while a workspace is running, because it's confusing to talk about starting a workspace that's already running.

we _do_ already show autostart info on the dashboard, as long as the workspace is not already running.

in my mind, this is working as intended, but if you have a compelling reason why we need to show autostart info while a workspace is running, we can talk it through.

**Comment by BrunoQuaresma** [comment]
@stirby should we close this one?

**Comment by stirby** [comment]
I do think some customers still wanted to see the next autostart when the workspace is still running. e.g. if I am in my workspace at 9pm I want to know that it's going to start at 9am the next day. I think this came up from distrust in this behavior https://github.com/coder/coder/issues/2028. 

I'm going to close this though as the existing autostart visibility looks fine. Will revisit if customers request.
