### ISSUE TITLE
Automatically authenticate `gh` cli in coder workspaces

### ISSUE THREAD

**Issue by matifali** [coder/coder#11904]
## Context

Coder uses `GIT_ASKPASS` to automatically authenticate git with the configured git provider. In the case of GitHub, `gh` cli is pretty common. A noninteractive way to authenticate `gh` cli is to set `GH_TOKEN` or `GITHUB_TOKEN` environment variables. 

It can be currently injected using the `env` map in `coder_agent` resource.

```tf
data "coder_external_auth" "github" {
  id = "GitHub"
}

resource "coder_agent" "main" {
  # ...
  env = {
    GITHUB_TOKEN : data.coder_external_auth.github.access_token
  } 
  # ...
}
```

## Problem

> User access tokens created by a GitHub App will expire after eight hours by default.

So the token becomes stale after 8 hours. 

## Suggested Solution

After discussion with @Emyrk, we could replace the `env` map in `coder_agent` with

```tf
resource "coder_script" "gh-login" {
  agent_id     = coder_agent.main.id
  run_on_start = true
  cron         = "0 */6 * * *" # run every 6 hours
  script       = "coder external-auth access-token github | gh auth login --with-token" 
}
```
This would keep updating `gh auth` every 6 hours, but still, there could be windows where a user is unauthenticated.

1. One janky solution can be to run the `cron` more frequently to shrink the unauthenticated window duration. For example, `cron = "*/5 * * * *"` will update auth every 5 minutes.
2. We keep it for 6 hours but early renew the token if the expiry is less than 2 hours. This will refresh the token and make sure it does not stale for the next 8 hours.

**Comment by Emyrk** [comment]
It's quite unfortunate that `gh auth` doesn't have any sort of "hook" we can get into, because ideally we just call `coder external-auth access-token github` on demand (when the token is needed).

If we do the cron solution, the token can expire right after the cron, making it invalid until the next execution.

Some ideas...

## Force refresh

We could have a function to force a refresh of the token if it's _about to expire_. Then we could run the cron every hour, and force a refresh if the token will expire in the hour.

## Schedule based

The cli could fetch the expiry information, and only run the external api request when it knows the api key is expired.

Currently  `coder external-auth access-token github` always makes an api call, but we could run the cron say every minute, but it does not make http requests unless it's expired. I imagine the cost of that execution is pretty small?

# Some concerns

If we do this with the cron, that will make a `validate` call to the IDP on each execution. We have hit Github rate limits before (https://github.com/coder/coder/issues/10853). We don't want to abuse the Validate behavior.

If we begin to suggest a cron style approach, we should take that into consideration.

**Comment by matifali** [comment]
This becomes a bigger issue for providers where tokens expire more frequently. For example GitLab OAuth token expires in 2 hours.

**Comment by matifali** [comment]
As a workaround, I am using this alias in my dotfiles, which works smoothly.
```
if [ "$CODER" = "true" ]; then
  alias gh='GITHUB_TOKEN=$(coder external-auth access-token github) gh'
fi
```

**Comment by stirby** [comment]
Closing this, advise using @matifali's workaround.
