### ISSUE TITLE
Org scoped provision daemon jobs

### ISSUE THREAD

**Issue by Emyrk** [coder/coder#11932]
Provisioners in an org scope should only be able to run jobs in the same org scope.

https://github.com/coder/coder/blob/5006edcee7527166e367684217502117cae0fe00/coderd/database/dump.sql#L650-L650

**Comment by Emyrk** [comment]
I do not fully grasp the "domain" concept of the `AcquireJob` here: https://github.com/coder/coder/blob/fe6def31ebd0ef992d44314d4073e65ac49be504/coderd/provisionerdserver/acquirer.go#L91-L91

I think if I were to add `organization_id` as an argument, then `org_id` would have to be apart of the `domain` struct? (https://github.com/coder/coder/blob/fe6def31ebd0ef992d44314d4073e65ac49be504/coderd/provisionerdserver/acquirer.go#L155-L155)

@spikecurtis?

My WIP branch is here: https://github.com/coder/coder/tree/stevenmasley/org_scoped_acquire

**Comment by spikecurtis** [comment]
The idea is that if multiple provisioner daemons have identical provisioner types and tags, then they are equivalent from the perspective of what jobs they could acquire.  This happens with the internal provisioner daemons, of which there are typically 3 and untagged, or if you stand up many instances of external provisioner daemons with identical tags --- in both cases it's to increase the number of jobs we can build in parallel.  The set of job-equivalent provisioners is a domain: a job that is acceptable to one is always acceptable to any of them.

The Acquirer sorts provisioners into domains and then only allows one acquire query at a time per domain, so that we don't have multiple queries that lock the same rows.  (We still need the locks because the Acquirer is local to a single Coderd, and if there are multiple Coderd replicas, we depend on the database locking.)

My understanding is that we want both jobs and provisioner daemons scoped to an organization, and provisioner daemons can only acquire jobs from the same organization.  If that's the case, then we need to expand the domain definition to also include the organization --- so it needs to be added to the domain key and included on all AcquireJob requests.

**Comment by Emyrk** [comment]
Exactly what I thought, appreciate the input.
