### ISSUE TITLE
Active user count on deployment page has date off by one day

### ISSUE THREAD

**Issue by aaronlehmann** [coder/coder#11943]
The graph of daily active users on the "Deployment" page always shows a date one day earlier than the current day for the latest data point (which appears to reflect the number for the current day). I don't think this is a time zone issue, since displaying the date in an inaccurate timezone would lead to an error in the opposite direction, but it might be something internal where the system attempts to compensate for timezones and overcorrects.

Possibly related: #7275

**Comment by Emyrk** [comment]
The issue is actually how the frontend converts dates (I think). If you look at the network requests response data, it does include "today". 

This line makes the x axis labels

https://github.com/coder/coder/blob/multi-organization%2Fcreate-user/site/src/components/ActiveUserChart/ActiveUserChart.tsx#L57


If you run our dates through this function, it truncates to the previous day because the timestamp is UTC, and my timezone is behind.
```javascript
console.log(dayjs('2024-01-31T00:00:00Z').format("YYYY-MM-DD"));
// 2024-01-30
```
