### ISSUE TITLE
feat: support bundle: automatically detect DERP disconnects in network support bundle

### ISSUE THREAD

**Issue by johnstcn** [coder/coder#12166]
Part of https://github.com/coder/coder/issues/12160

Given that we have access to agent logs in coder support bundles, we can now scan the agent logs for potential issues.

Potential strings to scan for and alert on:
- "disconnected from coderd"
- "failed to connect to the coordinate endpoint"
- "failed to close remote coordination"
- "recv DERPmap error"
- "speedtest listener failed"
- "update tailnet addresses"
- "create tailnet"

NOTE: The above is a sample list; there may be more definitely interesting strings or patterns.

**Comment by johnstcn** [comment]
@spikecurtis @deansheather Would NETGRU have any suggestions here?

**Comment by spikecurtis** [comment]
To what end?

Like, let's say we scan the logs and find some log lines as above... then what?  Rewriting them to a different file in the support bundle seems superfluous, as the person analyzing the support bundle can just grep directly and see the logs in context.

Also, looking at log text is fragile, since we often tweak or change the logs as we modify the code.  If there is some specific kind of error we want to care about, we should make it a metric and report it up thru Coderd.

**Comment by johnstcn** [comment]
Thanks Spike. It sounds like this isn't necessarily something we should be doing in the Coder binary. Closing this out for now.
