### ISSUE TITLE
Coder Missing Status "Starting" Filter

### ISSUE THREAD

**Issue by francisco-mata** [coder/coder#12215]
There's no "Starting" Status on filter bar 
![image](https://github.com/coder/coder/assets/97964900/2b4f03ca-c5c2-4aac-b846-e334e339f0be)

**Comment by matifali** [comment]
Yes. We decided in favor of removing non-trivial status from the drop down in order to make it less crowded. 
All statuses are still available when used manually. 
We could bring them back as part of an advanced filtering if we see enough demand but I don't think we should add them to this drop-down now.

**Comment by BrunoQuaresma** [comment]
@francisco-mata closing this for now but we will let you know in case we get more requests for this. Thanks for letting us know.
