### ISSUE TITLE
Users should see seat violation errors

### ISSUE THREAD

**Issue by bpmct** [coder/coder#12321]
It turns out the `Member` account does not see this error:

![image](https://github.com/coder/coder/assets/22407953/63d14d96-5be0-4be6-b6f8-b0a9a30c4187)

All accounts should see license violation errors and warnings to lead to a conversation with sales. It does not block new user creation and we can always issue a temporary license if there is an active renewal/expansion underway.

Another error shows if a license is approaching expiration, but has not expired. This one can be limited to only admins.

A rule of thumb: any current violations should be shown to all users. Any upcoming violations should be admin only

**Comment by BrunoQuaresma** [comment]
> Another error shows if a license is approaching expiration, but has not expired. This one can be limited to only admins.

@bpmct it is easy to show license errors to everyone but right now, it is not possible to filter errors by type because the errors are returned as text. To make that happen, we probably need to do some tweaks in the BE, so I'm wondering if we want to move forward with this.

```ts
export interface Entitlements {
  readonly features: Record<FeatureName, Feature>;
  readonly warnings: string[];
  readonly errors: string[];
  readonly has_license: boolean;
  readonly trial: boolean;
  readonly require_telemetry: boolean;
  readonly refreshed_at: string;
}
```

cc.: @mtojek I think I can work on the BE for this if @bpmct wants to move forward with this feature.

**Comment by BrunoQuaresma** [comment]
@mtojek Another option I thought about is to return errors based on the user role so if a user is a member, we only return member related errors and so on.

**Comment by mtojek** [comment]
> Another option I thought about is to return errors based on the user role so if a user is a member, we only return member related errors and so on.

This is a fair point, but the `/entitlements` is open to the public. See https://dev.coder.com/api/v2/entitlements with _incognito mode_.

We have 2 options:
1. Implement a new endpoint `/license_errors` that requires RBAC so that we can determine which errors should be displayed to the user. This is what you suggested above.
2. The simplest way, without building a new endpoint, would be deprecating `errors` in `entitlements` in favor of `license_errors` with the following structure:

```json
[
{
  "message": "License is approaching expiration, but has not expired yet."
  "visibility": ["admin"]
},
{
  "message": "License has expired!"
  "visibility": ["admin", "user"]
}
]
``` 

@johnstcn @dannykopping Any thoughts about this one?

**Comment by johnstcn** [comment]
What about option 3: make `/entitlements` a private route and show the warnings/errors there?
Alternatively, we could check user auth in `/entitlements` as Bruno says and conditionally show warnings / violations.

**Comment by mtojek** [comment]
> a private route and show the warnings/errors there?

It depends on how we define "breaking changes in API".

> Alternatively, we could check user auth in /entitlements as Bruno says and conditionally show warnings / violations.

Oh, conditional auth, it is tempting, but also may give unpredictable results. Imagine that the user session expires, and suddenly the endpoint starts returning different results?

**Comment by johnstcn** [comment]
Honestly option 2 (deprecating errors in entitlements in favor of license_errors) sounds best.

**Comment by BrunoQuaresma** [comment]
I would like to avoid making one extra request only to get the errors. Another option is to add a `code` attribute to the error so the UI can identify the error and handle the visibility. I like to make the FE as dumb as possible but this solution sounds like a good middle term.

**Comment by bpmct** [comment]
We're going to table this for now.
