### ISSUE TITLE
Shared ports protocol switching is not instant

### ISSUE THREAD

**Issue by f0ssel** [coder/coder#12454]
If you change a port from HTTP to HTTPS it seems hitting that shared port url will continue to use HTTP to connect to the port for a little bit of time before switching over. I'm not sure what could be causing this lag but my guess is something with the session being cached and the switch happens on token refresh.

**Comment by f0ssel** [comment]
@deansheather would you have any insight here?

**Comment by deansheather** [comment]
The protocol is written into the "app token" JWT. It only lasts for 60 seconds, so it only exists if they just opened the app within the last minute. So for this to occur the token would've had to refresh recently (e.g. they just opened the app) and then switched back to coder and changed the protocol, then refreshed the app within 60 seconds of the initial token issuance.

There's no way to revoke the "app token", which is why they only last for 60 seconds. We could just add a note in the UI when you change the protocol, like a little popup that says "changes apply after a minute" or something similar.

On the backend/technical side I think this is a wontfix

**Comment by f0ssel** [comment]
I think that's a good call on the wontfix, I can add a description and "sign our way out of it".
