### ISSUE TITLE
"Don't panic..." message lies

### ISSUE THREAD

**Issue by ammario** [coder/coder#1291]
<img width="941" alt="image" src="https://user-images.githubusercontent.com/7416144/166832408-bc3e1767-d1f3-462c-97f9-9c68a3e73804.png">

My workspace has been booting up for at least 5 minutes. Something tells me it's broken and will never finish "booting up", contrary to the message.

What would be far more helpful is some kind of log.

**Comment by skerit** [comment]
I'm getting this on the first workspace I've ever created (a `docker-code-server` instance)
It seems to start fine, but the main agent just stays on the `⦿ Connecting` status.

Doing the `coder ssh testspace` command will then show the `Don't panic, your workspace is booting up!` warning without ever finishing.

**Comment by skerit** [comment]
@bpmct I found it after a few hours, and ultimately it was because I didn't notice the `docker-code-server` template has an explicit dns setting :grimacing: 

Because of some ISP issues, my public access url isn't accessible from within my own network. Or more accurately: my public IP isn't accessible from within the network.

I work around this by using a custom DNS server internally, and rewriting my public hostname to an internal ip address.
This works fine, but the template used `1.1.1.1` as a DNS server, so the coder container always used the wrong ip address :shrug:

**Comment by bpmct** [comment]
Ah nice - it is quite strange we have a hardcoded DNS server, that would actually break in my home network as well if I wasn't using Tailscale

**Comment by bpmct** [comment]
Adding this one to the EE milestone. I have a few ideas but would love others' thoughts.

After ~3 minutes of "Connecting" (dashboard) or "Don't panic" (CLI), we change the message and link to the [troubleshooting documentation](https://coder.com/docs/coder-oss/latest/templates#creating--troubleshooting-templates) if the user is an admin (this is likely since this error mostly occurs when a template is first being tested).

**Comment by bpmct** [comment]
Closing in favor of #1291
