### ISSUE TITLE
Stop using global Axios instance for API calls

### ISSUE THREAD

**Issue by Kira-Pilot** [coder/coder#13013]
Related to https://github.com/coder/backstage-plugins/issues/114

We use a global Axios interceptor instance in `/site`. As discussed in the ticket linked above, we would like to import our API definitions into external applications, specifically Backstage. In order to avoid configuration collisions or intercepting requests unrelated to Coder, we should scope our instance appropriately and document our usage of Axios.

**Comment by Parkreiner** [comment]
Looking into this now

There's a quick-and-dirty fix that comes to mind:
1. Rename the global Axios import to `globalAxios`
2. Use `globalAxios.create` to make a new Axios instance that is scoped to the ES module file
3. Update all our API functions to use the new instance instead

My main worry is testing setup. The above change would solve the issue of collisions with other Axios users, but we'd still have a global singleton value, even though it'd be scoped more defensively to Coder-only files.

I've already run into a testing issue when making new tests for Backstage. If you have two classes that each mutate the same Axios instance with interceptors, you run a high risk of those interceptors conflicting with each other. And you also have to make sure that you correctly clean up the classes, or else classes from completed tests can still hijack requests with stale data.

I have some logic in place to make sure the classes clean up after themselves following each test, but it feels like the better option is to increase testing isolation, by making it so that the logic goes through Axios instances. My main worry is that I don't know if you can do that without rewriting the entire file to use classes instead of functions
