### ISSUE TITLE
Refactor filter components to make them easier to maintain and more reliable

### ISSUE THREAD

**Issue by BrunoQuaresma** [coder/coder#13035]
Right now, our filter components are not easier to maintain because of the base abstraction that is hard to extend, change, or test. To make that better I think we can:
- [ ] Split the current filter component into minor components so each resource can have its filter component
- [ ] Create tests for each of these new components
- [ ] Create e2e tests for the filters

After that we can safely improve the data load from:
- Template filter
  - [ ] Only fetch templates if there is a selected template.
  - [ ] When "All templates" is selected, it only should fetch data on click.
- User filter
  - [ ] Only fetch users if there is a selected user.
  - [ ] When "All users" is selected, it only should fetch data on click.
  - [ ] When the selected user is the logged-in user, use the current user profile data instead of fetching data.

**Comment by Parkreiner** [comment]
This might be something we push off for a while, but I wonder if we can take advantage of pre-seeding the React Query cache to reduce requests, too

As in, React Query gives you the ability to [put data directly into the cache without having to go through a query first](https://tkdodo.eu/blog/seeding-the-query-cache#push-approach). So, because a lot of our API responses contain data you can get from other API endpoints, maybe it'd be worth it to have our query functions update multiple parts of the cache at once (not just the cache pocket for the request just made, but any related cache pockets, too)

**Comment by BrunoQuaresma** [comment]
We are going to have a major design refactoring related to the workspace page and filters so it doesn't make sense anymore.
