### ISSUE TITLE
Don't backfill recently used value if it is equal to the previous default

### ISSUE THREAD

**Issue by NiklasRosenstein** [coder/coder#13100]
We're providing a default URL for the dotfiles of user's workspaces, but this URL has changed. However, users don't get this new URL now because they all have "recently used" the old default. 99% of our users don't override this field, the "recently used" value that is being filled is just the old default.

**Comment by kylecarbs** [comment]
Ahh, interesting. Good bug, will fix.

**Comment by bpmct** [comment]
Once the workspace is created with the default value, that gets saved as a value for the database. There's really no clean way for us to do what you're looking for because it may have unintended consequences for users.

As a workaround, you can have a "leave blank to use the default" and use Terraform logic + locals to assign the new default for a template version.
