### ISSUE TITLE
Filter out devices in tailnet that have an MTU that is too small

### ISSUE THREAD

**Issue by deansheather** [coder/coder#13327]
On devices with too small of an MTU, direct connections may be established (i.e. disco packets fit) but will drop every packet containing app data which renders the connection unusable.

This can happen on Cloudflare WARP VPN.

We should block these devices from being used for direct connections:
- When binding the UDP socket, do not bind to any devices that have an MTU below the minimum
- Don't share endpoints gathered locally from these devices

Background
------------

Relates to https://github.com/coder/customers/issues/592

Inside the Wireguard tunnel to the workspace, we use IPv6 as the network layer protocol. IPv6 sets the minimum MTU for devices that carry it to 1280 octets.  Thus, we set the virtual Wireguard TUN to an MTU of 1280 octets, and gVisor's tcpip stack will keep the inner IPv6 packets smaller than 1280 octets.  However, these packets then need to get encapsulated in Wireguard, and in the case of direct connections, further encapsulated in UDP & IP and sent over the outer network interface.  With this overhead, the typical TCP packets are 1338 octets.  Thus, if the outer network interface has an MTU smaller than this, the packets are dropped.

It is not possible to reconfigure the inner protocols to use a smaller MTU because 1280 is the minimum for IPv6 according to the IPv6 specs.

gVisor is actually a bit conservative in its choice of segment size, leaving some extra room for TCP & IP options, so we may need greater than 1338 minimum to ensure packets aren't dropped.

Additional Requirements:

- [ ] Update our documentation to note this limitation
- [ ] Update our `netcheck` command to highlight devices which are being skipped

**Comment by spikecurtis** [comment]
gVisor is nominally permitted to send packets up to 1280.
Wireguard adds 30 bytes (1310)
UDP adds 8 bytes (1318)
IP adds 20-60 bytes (1338-1378)

So, I think it really needs to be 1378 to be totally safe

**Comment by spikecurtis** [comment]
Unfortunately, we can't filter out the devices at the `bind`, since tailscale binds to `0.0.0.0`, meaning all interfaces.

We could potentially intercept and squash Disco packets coming from these interfaces, or artificially inflate Disco packets to the maximum size we expect from Wireguard (1310), such that only paths that handle packets that big can get discovered for p2p.

**Comment by spikecurtis** [comment]
Disco doesn't have any length parameter built in, so if we padded the messages we'd have to change the protocol.  That's a nightmare from back-compatibility standpoint.

**Comment by spikecurtis** [comment]
Intercepting and squashing Disco packets from particular interfaces is quite difficult because of the way UDP sockets work.  For incoming UDP packets we can get their source IP (where they are from), but don't normally get the destination IP or interface.  There are some low-level system calls you can make to get this information, but they're not portable, so we'd be handling multiple OS implementations.

The next idea I had was to figure out which interface we'd be sending replies via by looking at the routing table.  But again, there is no portable implementation.  We'd have to do multiple OS implementations.

**Comment by spikecurtis** [comment]
Looks like we can pad out Disco pings and pongs prior to encrypting with NaCl.  (CallMeMaybe is only ever sent over DERP.)

This has some performance implications, but Disco packets don't get sent that often, so it's probably fine.

**Comment by spikecurtis** [comment]
Testing on Linux, I've discovered that with the inflated ping/pong packets, the Don't Fragment (DF) flag only gets set if the packet is smaller than the interface MTU.  If the interface MTU is smaller than the packet, then it fragments the packet.

1. I think this means that the strategy of inflating the ping/pong packets doesn't really work on its own to keep Tailscale from using interfaces with small MTU.  It just fragments and reassembles the packet.

2. It also means that our understanding of the Cloudflare WARP VPN issue might be incomplete. The OS might have been fragmenting the packets --- which is bad for performance, sure, but I don't think it should completely break connectivity.  It's possible that other OSes act differently, e.g. dropping UDP datagrams too big for the MTU rather than fragmenting, or that WARP refuses to forward fragmented packets (very odd if true).  Or maybe fragmentated performance is just so bad that it brings TCP to its knees?

So, possible next steps:

There is a DONT_FRAGMENT socket option we could try setting.  Not sure how portable it is, but in theory it might convince Linux to drop too-large packets instead of fragmenting them. Setting that on the tailscale UDP socket is basically us saying that we should always prefer DERP to a fragmented direct path, which may or may not be faster.

This whole thing is honestly turning into a boondoggle, IMO.  We _thought_ it would be easy, and prevent some customer heartburn by automatically preferring DERP over paths with "bad" MTU, but it's turning out to be very difficult and involved.  Customers _can_ already work around the issue by setting DISABLE_DIRECT, so maybe we should cut our losses: drop an MTU check into `coder netcheck` / `coder support bundle` and call it a day?

**Comment by spikecurtis** [comment]
@sreya what say we close this issue after #13562 is merged? I don't think there are any tailnet changes we can make that would be worth our time.
