### ISSUE TITLE
Swagger CSRF Error

### ISSUE THREAD

**Issue by rudolfbatke** [coder/coder#13535]
Some requests don't work due missing of the X-CSRF-TOKEN header. 

E. g. `.../swagger/index.html#/Builds/create-workspace-build`.

The 400 response contains the message 

`Something is wrong with your CSRF token. Please refresh the page. If this error persists, try clearing your cookies.`

Neither a page refresh nor clearing the cookies solves the problem.

An curl command of the exact same request, but including the X-CSRF-TOKEN header with the content of the csrf_token cookie works as expected.

**Comment by Emyrk** [comment]
The issue is swagger docs are hosted on the same domain as Coder. So it is using both header and cookie authentication. If these values do not match, we require CSRF since the cookie is set.

As a temporary measure, you can ensure the cookie value matches the `Authorize` value passed in.

![Screenshot from 2024-07-01 10-55-38](https://github.com/coder/coder/assets/5446298/c834c961-ac3e-4b5d-8cf3-54003f8322c6)


I have a PR fix: https://github.com/coder/coder/pull/13742. This will stop using browser based credentials and rely on the authorization creds.
