### ISSUE TITLE
Use pie chart for app usage in template insights 

### ISSUE THREAD

**Issue by stirby** [coder/coder#13627]
We currently use bars to show the usage of coder apps in the template insights page. These bars represent the percentage of total activity that was recorded through each app. Bar graphs/displays are not often used to express distribution so it's a little hard to understand:

![Screenshot 2024-06-20 at 2 19 17 PM](https://github.com/coder/coder/assets/58410745/29bab0af-61bf-4e34-a634-e9bcf72ed863)

I propose we switch it to a pie chart with tooltips explaining they're a percentage of usage. Much easier to see that they add to 100%:

![Screenshot 2024-06-21 at 11 01 29 AM](https://github.com/coder/coder/assets/58410745/7ba88459-42ef-4cba-b3b5-7bbde6ce6fbf)

We could also add app icons to the slices that are large enough to hold them, while keeping the "legend" as shown on the right. 

Yielding to your better eye for design here @BrunoQuaresma.

**Comment by aslilac** [comment]
sorry to come in as a naysayer after the work has already been done, but I disagree with this change. 😅 the bar chart has the nice property of giving very direct correlation between the app name and the app usage visual, without needing to hover over anything (plus it just looks a lot nicer than a pie chart, which I think you rarely see in modern apps)

**Comment by stirby** [comment]
@aslilac the feedback is more than welcome! 

I agree that we're at risk of losing correlation. Definitely want to maintain a clear visual association between apps and usage. Coming from a background with almost zero experience in web design and only light experience in research visualization, I thought a pie chart better fit proportional data. I immediately think of nominal data when I see bar charts. 

That said, I agree that the bars look objectively better than the currently proposed pie chart.

I think we should keep riffing on the pie. What if we had icons that point to each slice like in Nexus?

![Screenshot 2024-07-01 at 12 22 16 PM](https://github.com/coder/coder/assets/58410745/838ca1e1-39f1-485f-948e-144e05720b9a)

**Comment by BrunoQuaresma** [comment]
Unfortunately, it is not trivial to add icons into the pie chart slices due to several reasons:

- There is no built-in way to add them.
- We have to calculate the positioning of the icons inside each slice.
- Icons can be dynamic, so contrast can be an issue when placed inside a slice with a similar dynamic color.
- We have to calculate ourselves whether the slice has enough space to accommodate the icon inside it.

We could use a plugin to assist with some parts, but they have their own limitations, such as not ensuring contrast for the icons. Here is an example of such a plugin: [Chart.js Labels Plugin](https://emn178.github.io/chartjs-plugin-labels/samples/demo/). We could consider trying a different library, but I would only proceed with that if it becomes a significant issue for customers or if it is blocking users from accessing the information they need.

The pie charts in the global versions work well because the differences between values are balanced. Here's how they would look for the 'Coder in Coder' template usage without any additional hacks.

![image](https://github.com/coder/coder/assets/3165839/35760fe5-d905-4d8d-b245-c94320661b1d)

Just to clarify, I think the proposed changes are okay. I just want to ensure that we understand the amount of work required to achieve a good pie chart so that we can better assess its value.

**Comment by stirby** [comment]
Let's drop the change. No customers have complained about how the data is currently represented. I'm glad we experimented with other ways to show the data because using bars seemed arbitrary. 

@BrunoQuaresma can we show your "percentage of usage" tooltip when hovering over each app's bar? Otherwise, it will remain unclear that they sum to 100%.
