### ISSUE TITLE
Terms of use for templates

### ISSUE THREAD

**Issue by stirby** [coder/coder#13666]
### Problem statement
An enterprise customer wants to add a "Terms of usage" for their templates. Users would have to accept some message before using a template. I assume these terms of use would relate to data privacy or something similar.

The requester can't use deployment-wide banners because the message needs acknowledgment and only applies to specific users on the deployment.   

### Proposal
We can add a simple "terms of usage" message option in the template settings. Like the template deprecation message, terms of usage are only shown when the message is not null. The message would appear as a popup when users create new workspaces from the template, before the workspace creation screen. If accepted, the workspace creation screen is shown. If declined, they're taken back to the template page.

**Comment by bpmct** [comment]
Can't we use a parameter for this during template creation?

**Comment by ssncoder** [comment]
Try to use a parameter like this in the template, it will add a parameter in the workspace creation screen where users can type "yes" to accept their data privacy agreement. They can link to their doc in the parameter description.


data "coder_parameter" "terms_of_use" {
  name         = "terms-of-use"
  display_name = "Terms of use"
  description  = "Please type \"yes\" to accept the [data privacy agreement](https://coder.com/) before using this template. Otherwise, **the workspace build will fail**."
  type         = "string"
}


Then, apply the lifecycle block with a precondition on a resource that runs the agent to verify the user entered "yes." If they did not, the workspace build will be prevented.


lifecycle {
    # The user must accept terms of use
    precondition {
      condition     = regex("(?i)^\\s*yes\\s*$", data.coder_parameter.terms_of_use.value)
      error_message = "Build prevented. You must accept the terms of use before creating a workspace from this template." 
    }
  }
