### ISSUE TITLE
Solidify permissions and licensing checks in the UI for Org feature set

### ISSUE THREAD

**Issue by Kira-Pilot** [coder/coder#13915]
Orgs is an enterprise feature. We should ensure it is effectively and coherently gated prior to releasing as an experiment.

**Requirements**
- [x] experiment name should be appropriate and documented
- [x] add small notice if experiment is enabled but user does not have premium license
- [x] make sure org features cannot be accessed and orgs cannot be created without a premium license
- [x] change site-wide permissions to be org-scoped where necessary in line with [this PR](https://github.com/coder/coder/pull/14009)
- [x] ensure that the UI doesn't error for single-org deployment after we've added all these new org features
- [x] add Jest tests for above cases
- [x] Organization sidebar settings should be conditional based on actor's capabilities. 
  - [x] "Organization Settings" should change to "Organization Summary" if the user cannot `organization.<org_id>.update`
  - [x] See [comment below](https://github.com/coder/coder/issues/13915#issuecomment-2271486254) for conditional _ideas_
- [x] Docs link for orgs/premium license
- [x] Update middleware error to say premium instead of enterprise
- [x] Show summary if not entitled

**Known issues**

- [x] groups page user dropdown shows all users on the site, not just members of the organizatinon. When adding a user to the group if they are not in the org, you get an error "User must be a member of organization "rabbit-group""

**Comment by Emyrk** [comment]
Related: https://github.com/coder/coder/issues/14057

**Comment by code-asher** [comment]
Something that needs to be addressed is that you might see organizations you cannot edit.  Right now I am showing a "you cannot edit this org" message, but maybe we will want to filter out organizations the user cannot edit?

But there is also currently a halfway point where the user cannot edit the org but they can see the audit log link, so in that case I am not sure what to do.  If we decide to get rid of the per-org audit links then it will resolve itself though.

We could have that page be a sort of summary page for the org instead of a settings page if you do not have permissions.  Just displays the org name and description or something like that.

**Comment by Emyrk** [comment]
@code-asher I think we should do an auth check for each menu item, and show it conditionally.

Some pages like `groups` might be viewable if you have the read perm, but the "Create Button" might not be shown if they cannot make groups.

![Screenshot from 2024-08-06 09-46-52](https://github.com/user-attachments/assets/d77878ff-54ba-4d56-9a2f-8ff3014b1861)


> We could have that page be a sort of summary page for the org instead of a settings page if you do not have permissions. Just displays the org name and description or something like that.

I think this is a great idea. Then someone with no sidebar item perms, but can still see the org with `organization.read` will see something. Like `Organization Summary` instead of `Organization Settings`

**Comment by aslilac** [comment]
> no easy way to do this right now I think aside from making an auth check for each org

we do that in `CreateTemplateForm` already, shouldn't be too hard to do here too

**Comment by code-asher** [comment]
Oh dope!  I do actually run individual authcheck queries for the links under each org (so you should only see the sub-links you have permissions for), but I only do it at the point when the menu item is clicked and expanded because I was worried about firing off N queries all at once, but it sounds like that is probably the better way to do this, since that lets me hide the main org item entirely if the user has no permissions at all.  Thanks for the guidance all!

And I will add a summary page for users who can see at least one link but cannot edit.

**Comment by Emyrk** [comment]
@code-asher authchecks can be batched into a single api call. So if you know all the auth checks up front, you could send all N in 1 call

**Comment by code-asher** [comment]
Good grief how did I not realize that, I should have checked the PR more closely, thank you that makes things incredibly easy.

**Comment by Emyrk** [comment]
@code-asher the `org1.permission` is used when I do permissions. Like `workspace.read`. So I think the `.` is good :+1:

**Comment by bpmct** [comment]
I also noticed this if I have no license. We should probably hide it all. Apologies if this is somewhere in the issue already

![Screenshot 2024-08-15 at 9 53 48 AM](https://github.com/user-attachments/assets/2655eeab-77ed-4da4-b027-0314c6dd5b31)

**Comment by code-asher** [comment]
Ah yup that makes sense to me, could bring the same license UI that is on the new org page I think.

**Comment by Emyrk** [comment]
@bpmct I don't think we should hide all org stuff without the license. There is still an existence of organizations, and licenses can expire. Maybe we should have a conversation how to best handle this.

**Comment by code-asher** [comment]
For now I made it show the summary page, but I def think we should rethink especially since that summary page is pretty lame
