### ISSUE TITLE
POST to /api fails with 400 with CSRF error

### ISSUE THREAD

**Issue by jonrob** [coder/coder#13922]
```
Coder v2.13.0+56bf386 Tue Jul  2 17:54:06 UTC 2024
https://github.com/coder/coder/commit/56bf386b15128c986ad4172c1932c13bed626d58
```

### Steps to Reproduce

1.Log in to Coder. 
2.From dev tools console, make a request like this, populating the values accordingly:

`await fetch("https://<coder-host>/api/v2/organizations/<organization-id>/members/<member-id>/workspaces", {
    "credentials": "include",
    "headers": {
        "Accept": "*/*",
        "Accept-Language": "en-GB,en;q=0.5",
        "Content-Type": "application/json",
        "Sec-Fetch-Dest": "empty",
        "Sec-Fetch-Mode": "cors",
        "Sec-Fetch-Site": "same-origin"
    },
    "body": "{\"name\":<template-name>",\"template_id\":<template-id>,\"rich_parameter_values\":[],\"parameter_values\":[]}",
    "method": "POST",
    "mode": "cors"
});`

### Expected

Should get a 201 response indicating the workspace is created. 

### Actual

Get a 400 server error response saying "Something is wrong with your CSRF token. Please refresh the page. If this error persists, try clearing your cookies."

### Notes

We've a small JS application wrapping the Code server API to allow users to get a coder workspace direct from a link without having to interact with the code-server instance directly. 

The JS app and code server are both behind the same reverse proxy, so are on the same origin.

When they visit the JS app in their browser, it checks if the user is logged in by attempting to retrieve the `/users/me` API endpoint. If it doesn't get a 200 response, it redirects them to `/users/oidc/callback?redirect=/app`.  

It then makes a series of GET requests to collect information from the API, all of which work fine (e.g. organization, templates) before making the above POST request with the information populated. 

This was working on coder 2.2.1, but we've just tried to update to 2.13.0 and have begun getting the CSRF token error on the POST request. 

If you add the header `X-CSRF-TOKEN` with the value set to the value of the CSRF token cookie, the request succeeds.

**Comment by kylecarbs** [comment]
@Emyrk do we have an option to disable CORs?

**Comment by Emyrk** [comment]
@kylecarbs the error reported is CSRF, not cors.

The reported bug is is cross-site-scripting by definition, which CSRF is implemented to protect against. It is trying to use a workspace app to submit HTTP requests to the coder deployment. 

CSRF was turned on in v2.6.0 : https://github.com/coder/coder/pull/11283

By default, we cannot allow this kind of XSS, because we added application sharing as a feature in v2.9.0: https://github.com/coder/coder/releases/tag/v2.9.0. This would mean a user could hijack another user's credentials if they directed them to a malicious app.

-----

The simple solution idea is to add an option to disable CSRF. The option would be a `--dangerous-disable-csrf` with warnings that this is an intentional security feature that prevents XSS from user apps.

I dislike this idea, because it essentially allows any shared app to completely assume the identity of the user on the page. Which is quite dangerous. @jonrob does your application have a server side component? The ideal solution would be to use the server side component to make the api calls using the token in `~/.config/coderv2/session`.

**Comment by jonrob** [comment]
Thanks for the input @Emyrk - we don't have a server side component - it's just a static JS file served by a web server. 

We'll consider our options based on your feedback.

I don't know if possible, but it might also be useful to disable csrf checks on specific endpoints rather than just on or off, which would reduce the risk posed?

**Comment by Emyrk** [comment]
@jonrob turning it off for specific endpoints feels difficult to configure. 

On the implementation to get around CSRF though. You would have to put the session token in the header `Coder-Session-Token`. Rather than as a cookie. So your client side app could take the session token as input, save it in local storage, and make auth calls.
