### ISSUE TITLE
Integrate auditing view into the multi-org capable `ManagementSettingsPage`

### ISSUE THREAD

**Issue by aslilac** [coder/coder#13958]
### Notes

- Auditing is currently only accessible from the "Deployment" dropdown
- To make it consistent with the org level auditing, it should be accessible from the deployment section of the `ManagementSettingsPage`

### Goals

- [x] Change the /audit route to /deployment/audit, and add a `<Redirect>` to avoid breaking links.
- [x] Add an "Auditing" sidebar item underneath the Deployment settings
- [x] Make sure that the page integrates with/looks good in the new context (eg. the correct sidebar item is highlighted). 

Added by: https://github.com/coder/coder/pull/14023

- [x] Implement RBAC SQL filter for audit query on BE (https://github.com/coder/coder/pull/14070)

**Comment by Kira-Pilot** [comment]
@aslilac added @Emyrk to the ticket and added a BE filter-related goal to make this view reality

**Comment by Kira-Pilot** [comment]
![Image](https://github.com/user-attachments/assets/ef370a9a-f642-4e02-8cb2-bf4e969c2ae3)



![Image](https://github.com/user-attachments/assets/397dfb45-f012-4e81-8957-f442e96324fe)

**Comment by Kira-Pilot** [comment]
@aslilac anything else we need to do here or can we close out this ticket? I noticed you mentioned tweaking styles in the PR.

**Comment by aslilac** [comment]
I'd be fine with closing this and opening a follow-up to track other stuff.

Basically, two things

1. The actual design that I had in mind was something like our `HelpTooltip` component, but the mocks for this work have all been very low fidelity so that definitely wasn't communicated in the design. The `HelpTooltip` stuff just has really nice spacing, and the hover target is a bit smaller than what got merged in @code-asher's PR. (which again, low fidelity mock didn't make that vision clear)

2. Highlighting "Auditing" under the org, rather than under "Deployment" when filtering by an org name.

Neither should be particularly hard, but they also aren't stopping us from shipping, so they probably go pretty low on the list.

**Comment by Kira-Pilot** [comment]
Nice, both of those make sense to me! 2. might be dependent on the outcome of [this thread](https://codercom.slack.com/archives/C070XG9U23G/p1722304572009289) in Slack. 

So we don't lose track of those threads, can we add them to [this ticket ](https://github.com/coder/coder/issues/13241)as checklist items to the *After Experimental Release* section? Next sprint I will organize these to-dos with more rigor but for now that's place to list smaller but less-urgent tweaks we'll handle soon.

**Comment by code-asher** [comment]
I was thinking we were not doing the second because if for example you are at `/deployment/audit` and you type `organization:netgru` in the search box (or use the filter dropdown), you get "navigated" to a different section of the sidebar, which could be weird?  Similarly, if you remove it from the filter you get "navigated" back.

To solve both cases I think we would need to have the pages duplicated at two separate URLs which is easy enough, however honestly I feel like we should move the audit log back to `/audit` and not have the per-org audit links at all?  My impression is that I would rather just use the main audit log because fewer clicks to get to it (deployment > auditing) and I can change the organization without wiping the rest of my filters (say you are looking at logins for org1 and now you want to look at logins for org2).  But I am not sure what the motivations are, like if we had some user feedback that the separate audit logs made more sense under the settings sidebar or something like that, so grain of salt.  😆

**Comment by Emyrk** [comment]
@code-asher I agree that it might be excessive to have audting nested under `organization`. It could probably exist under just Deployment.

@aslilac ?

**Comment by Emyrk** [comment]
@code-asher can we close this issue out?

**Comment by code-asher** [comment]
I added a link to the PR that closed the frontend part of this in the issue description.

I think we can close, but I do think we will want to make a final decision on the per-org audit links.  I also think we could get rid of them and just have the one audit link (and that is where the deployment dropdown link goes anyway and is probably where most people will end up anyway, but to be fair I have no data on that, just a hunch).

**Comment by code-asher** [comment]
Although, if we do decide to have the one audit link I feel like we should just put it back at `/audit`, it is not a setting so it seems weird to be bunched with the other settings, and the sidebar makes it worse to use.

**Comment by Emyrk** [comment]
@code-asher Let's move it back to `/audit`. Remove it from the org settings page entirely.

**Comment by code-asher** [comment]
Perfect, will do!  Going to close this out and rely on another issue.
