### ISSUE TITLE
cleanup frontend template routing

### ISSUE THREAD

**Issue by aslilac** [coder/coder#14068]
go do a search for

```
// TODO: skip org name if we're not licensed
```

and then do what it says :)

basically, check

```ts
const { multiple_organizations: organizationsEnabled } = useFeatureVisibility();
```

and then if `organizationsEnabled` is `true`, use the `/template/:organization/:template` route, and if it's `false` use the `/template/:template` route.

**Comment by Emyrk** [comment]
This is tricky because having 2 different routes based on your license feels fragile. For one, if you downgrade from premium to AGPL, you could have 2 templates with the same name in different orgs, and now `/template/:template` feels ambiguous to a user.

Maybe we should just accept `/template/:organization/:template`? @kylecarbs would love for you to weigh in.

-------------------------

At present, customers could have `/template/:template` book marked, and if they upgrade to premium, their links and bookmarks are now ambigious without the `:organization` context.

Maybe we should have `/template/:template` route to some error page that lists all the templates that share that name. So the user can disambiguate themselves, and get directed to the new url.

![TemplateUrlMove drawio](https://github.com/user-attachments/assets/c6ed0aae-14fa-4afc-82e5-af6b675f991b)

**Comment by aslilac** [comment]
> now /template/:template feels ambiguous to a user.

I added some extra checks so that any deployment with more than one org will always get the multi-org routes, regardless of license state. and I don't think /template/:template is ambiguous, it's always equivalent to /template/default/:template. Any other template would've never been accessible at /template/:template, so it's a safe choice.

I know maintaining it long term will take work, but we already have to anyway, because we can't break old links for customers. 🤷‍♀️

**Comment by aslilac** [comment]
The work that I opened this issue to track is actually already completed, but I'll leave it open a bit longer if we can reach a consensus about what else needs to be changed.
