### ISSUE TITLE
`coderd_agentstats_session_count_*` are not being populated

### ISSUE THREAD

**Issue by bpmct** [coder/coder#14348]
<img width="2908" alt="Screenshot 2024-08-19 at 9 43 47 AM" src="https://github.com/user-attachments/assets/3ce8c88c-c646-4267-b11c-82f7e7a272e6">

using dev.coder.com and grafana.dev.coder.com. I did not check if there are other agent metrics that are not being populated

**Comment by f0ssel** [comment]
This annoyingly needs us to do some special case handling while we juggle the workspace activity experiment, I have a PR I'm working on here - https://github.com/coder/coder/pull/14576

**Comment by sreya** [comment]
@Kira-Pilot I assigned it to @ethanndickson and told him to correspond with @f0ssel before doing anything. I know you guys are pretty heads down with orgs and he has some cycles to spare.

**Comment by Kira-Pilot** [comment]
@sreya awesome, thank you so much! I'll let them coordinate.

**Comment by f0ssel** [comment]
@ethanndickson This problem (and workspace activity in general) is a little hairy so I wanted to leave some hand off notes:

### Background
We previously had workspace agents report the # of connections, latencies, bytes transfered, and session counts for `vscode`, `ssh`, `jetbrains`, and `reconnecting_pty`. This would be handled by the `agentapi` in `coderd` and written to the `workspace_agent_stats` table. In rolling out the new `workspace-usage` (workspace activity refactor) we now have a new way for clients (think coder CLI) to report sessions directly to `coderd` without the need of an agent middleman. The new endpoint writes these *session stats* to the same database table, but the stat is only partially filled and is missing agent information like bytes, latency, etc. 

### Problem
For cases like template insights, these partial stats (usage stats) living along side the existing agent stats is not a problem because of how the data is rolled up. Unfortunately, this is not the case for *Deployment Metrics* (the data bar at the bottom of the dashboard). The data being in two different formats in combination with us grabbing the "latest agent stat" means the two partial stat types will compete and overall report incorrect data over the period. This is really only a problem while we must support both writing patterns while this is in experiment.

### Solution
- Partition the data with a boolean flag for the new writing pattern and update insert queries accordingly. 
- Duplicate the queries and have them use the new flag when collecting and summarizing the data. 
- Add conditions to use the new queries when the experiment is enabled

### Considerations
If you look at the queries I have so far you'll see we are collecting stats over a period, and only use the `usage` flag for getting the session counts. This is because we still need the data that has been reported from the agent, like bytes and latencies, and we then combine them when returning the summarized values. 

### Progress
Feel free to branch off https://github.com/coder/coder/pull/14576 or commit directly to it when ready, I've so far got the queries written and I've wired up one of the queries to be used based on the experiment. Wiring up the rest of the query usages, the mock db implementations, and testing are left. For tests, we'll want to cover the new experiment enabled branches and if feasible we should try to get some tests cases to ensure we are filtering out / counting sessions correctly with a mix of stats in the table.
