### ISSUE TITLE
notifications: turn off a notification via email

### ISSUE THREAD

**Issue by stirby** [coder/coder#14389]
A user may receive an email notification from Coder and then want to opt out of that specific template immediately. To support this case, we should add an option to all SMTP notifications that allows users to block a template like so:

![stop_recieving_notif](https://github.com/user-attachments/assets/4b90c1d6-72ba-470c-9886-0755e2e33a67)

Not a blocker for release and implementation depends on customer corroboration of this flow. 

This would require a human-readable name for notification templates.

**Comment by dannykopping** [comment]
I would suggest a slight rephrasing as simply "Stop receiving emails like this"; I don't think we need to include the template name here.

**Comment by joobisb** [comment]
@dannykopping I would like to take a look at this

**Comment by dannykopping** [comment]
@joobisb go for it 👍 let me know if you run into any issues. Thanks!

**Comment by joobisb** [comment]
hi @dannykopping 

I believe we cannot make direct API calls from the received email to our backend server due to CORS and other issues, so I was thinking of the following:

- Instead of making an API call, add a query parameter to the "Manage Notifications" link. When the user lands on the notifications page, check for this parameter and perform the unsubscribe action.

- In the frontend code, check for the unsubscribe parameter, perform the action (PUT api/v2/users/{user}/notifications/preferences API), and display the same Notification preferences updated toast.

wdyt ?

**Comment by dannykopping** [comment]
Sounds good to me @joobisb!

**Comment by joobisb** [comment]
Hi @BrunoQuaresma,

https://github.com/coder/coder/pull/14520#issuecomment-2343787302 continuing this conversation here as I'm unable comment further on the PR

Thank you for reviewing the PR and merging it.

I appreciate you fixing the Notification stories as well, didn't know we could use decorators to spy the API before the story is rendered 

https://github.com/coder/coder/blob/330121297217c7174874543ef0c370af42d80535/site/src/pages/UserSettingsPage/NotificationsPage/NotificationsPage.stories.tsx#L107

had one question though, this message was added to show the user which template was disabled, wasn't it needed?

```displaySuccess(`${template.name} notification has been disabled`);```

**Comment by BrunoQuaresma** [comment]
@joobisb In order to obtain the template name, we would have to wait for the templates to be fetched, which would block the update request until that process was completed. In my opinion, having the name doesn't provide significant value as it slows down the action. Additionally, since the other toast messages don't include the template name, I think it would be acceptable to omit it. If we believe that including the name in the notification is essential, then we may need to update the API or possibly the email link to provide the name without blocking the delete action. Makes sense?

**Comment by joobisb** [comment]
> @joobisb In order to obtain the template name, we would have to wait for the templates to be fetched, which would block the update request until that process was completed. In my opinion, having the name doesn't provide significant value as it slows down the action. Additionally, since the other toast messages don't include the template name, I think it would be acceptable to omit it. If we believe that including the name in the notification is essential, then we may need to update the API or possibly the email link to provide the name without blocking the delete action. Makes sense?

@BrunoQuaresma it does. thanks for clarifying!
