### ISSUE TITLE
UI: add beta labels to Organization feature 

### ISSUE THREAD

**Issue by Kira-Pilot** [coder/coder#14499]
## Summary
We are releasing orgs as an `beta` feature and should tag it as such in the UI using a pill or something similar. Eventually we *might* have other labels, e.g. `alpha`, `early-access`, `experimental`, etc. Any design we come up with should consider these future labels (but not over-index on them as we're still discussing). Also of note: we do have some existing pills in the UI to indicate licensing, e.g.
![Screenshot 2024-09-09 at 10 57 00 AM](https://github.com/user-attachments/assets/26fd65d9-96d8-4e55-9120-edf2cae752ef)

## Requirements
- [ ]  Add `beta` labels in accordance with the linked designs
- [ ] Each `beta` label should link to the new `beta` docs (see below; coordinate with Product)

## Documentation
In the past, we did have `alpha` labels in the product and there's a [doc page](https://coder.com/docs/contributing/feature-stages) on them. We should link the labels in the UI to a similar page for `beta` so users can read more about the stage (and we should update the outdated `alpha` documentation or remove it entirely if it is no longer pertinent to our stage story). Product will be handling docs, alongside @mattvollmer. We should coordinate with Product prior to merging this ticket up so that the docs are fresh.

## New Org views & UI
We have introduced some new UI for Orgs. We want to be conservative when adding `beta` labels so that we don't clog up our pages with stage indicators; however, the below screenshots are comprehensive of what we've added:

This new menu option:
![Screenshot 2024-09-10 at 11 03 59 AM](https://github.com/user-attachments/assets/692561f2-3024-49a8-8b8f-262f6429b9d0)
All org pages under the new "Organizations" menu option:
![Screenshot 2024-09-10 at 11 04 36 AM](https://github.com/user-attachments/assets/c9da148b-ac3b-40c0-99d3-aef440781664)
New org filters on the audit, templates, and workspaces pages:
![Screenshot 2024-09-10 at 11 09 33 AM](https://github.com/user-attachments/assets/51d6711b-1fd5-4891-85a7-5afc1806fa89)
New dropdown on the Create Template form:
![Screenshot 2024-09-10 at 11 09 52 AM](https://github.com/user-attachments/assets/0a419133-ad8c-4c1f-9950-1b4bac0830a8)

And...coming soon:
New IdP page (under new "Organizations" menu option):
![Screenshot 2024-09-10 at 11 22 13 AM](https://github.com/user-attachments/assets/fde1982c-9f65-42e4-aa6a-8ab6a3a3aba4)

New provisioners page (under new "Organizations" menu option):
![Screenshot 2024-09-10 at 11 23 19 AM](https://github.com/user-attachments/assets/81e36778-d222-4eb9-addd-194cb828866e)

**Comment by stirby** [comment]
@Kira-Pilot do we already have badges for beta features? We should use tags that align with our [feature stage docs](https://coder.com/docs/contributing/feature-stages).

**Comment by Kira-Pilot** [comment]
This ticket needs some design

**Comment by Kira-Pilot** [comment]
Est: S

**Comment by bpmct** [comment]
let's change it to alpha: https://coder.com/docs/contributing/feature-stages

**Comment by chrifro** [comment]
[Here](https://www.figma.com/design/1bHJvrhzQNLnDqT3WRgqzn/organizations?node-id=0-1&t=ejGVc9VouNMkvmI5-1) is the design for the new label. 

Note: the design is based on screenshots and it's therefore not pixel-perfect. I'm gonna build on our Figma setup to avoid that in the future. Hope this gives you anyway a good insight into how it's supposed to look.

The new label comes in two sizes
big: used behind headlines (together with font sizes of around 24px)
small: used for drop-downs and submenus (together with font sizes of around 14px

Component:
<img width="862" alt="Screenshot 2024-09-12 at 09 35 08" src="https://github.com/user-attachments/assets/77140763-caca-4b56-b8d1-265f5ee30ece">

Context example:
<img width="864" alt="Screenshot 2024-09-12 at 10 01 20" src="https://github.com/user-attachments/assets/bc644ec8-4d7e-4b0e-a803-73f9eb4c3b22">

<img width="211" alt="Screenshot 2024-09-12 at 10 01 37" src="https://github.com/user-attachments/assets/bf72bc08-e99b-4407-b655-6e957ded6ff9">

Let me know in case you need any more details 🙌

**Comment by Parkreiner** [comment]
@chrifro Thank you! These look great – I think I just have one question around the expected hover behavior

I wouldn't expect these to ever be links or buttons, so I just want to make sure I understand when we would use the hover styling. Would it only be when a surrounding element is being hovered over?

For example, using your screenshots, there wouldn't ever be a hover style for the "Appearance" header because that's static text, but if someone hovers over the "Organizations" dropdown option, then its beta text would light up?

**Comment by chrifro** [comment]
Note: Ammar requested that the color of the beta tag be changed to something more vibrant. I've now picked #22D3EE which is part of the Tailwind CSS color palette.  

Regarding the hover style, great question @Parkreiner! It doesn't make sense to have the tag clickable when it's part of a drop-down or a sub-menu. Based on the context in the screenshots above, it should only be clickable when it's behind a headline e.g. "settings". In that case, the hover becomes active only when hovering directly over the tag. The tag should then link to https://coder.com/docs/contributing/feature-stages. 

cc @Kira-Pilot

**Comment by Kira-Pilot** [comment]
Thank you and nice work @chrifro! @Parkreiner this ticket is ready for implementation when you have time!

**Comment by Parkreiner** [comment]
Okay, the component is mostly done. Just need to do a few tweaks, and then wire it up throughout the codebase.
[Video preview](https://github.com/user-attachments/assets/87938f3c-9b7f-4a0f-9211-8563b3a8d177)

@chrifro – I have a couple of questions for you, though:
1. I haven't really put any effort into making the light mode colors look good yet, but do you have any preferences on how they should be designed? Sorry if this wasn't communicated to you earlier, but pretty much every design going forward is going to have to support our dark and light themes. You can toggle the theme for dev.coder.com by clicking the User icon in the top right corner --> Click account --> Click appearance
2. I know that you had used transparency to adjust your colors, which I'm a fan of, but I don't think there's a good way for us to support transparency with the current architecture we have. Basically, the current setup assumes that we'll always be using [solid colors from a given row in the Tailwind page](https://tailwindcss.com/docs/customizing-colors). I adjusted the colors as well as I could, but let me know if you want me to change them again
3. Let me know if you want me to change the body copy in the tooltip
4. Is it safe to assume that we'll be using this cyan palette for anything related to previews going forward? In that case, @aslilac, is it cool if I repurpose the Preview role, since we're not currently using it for anything? (We technically have it for the theme switcher buttons, but the conditionals can't trigger right now)

**Comment by chrifro** [comment]
Great points! Thanks @Parkreiner 🙏

Right now, choosing colors feels super random and inconsistent. Once I get to define our color usage and set up tokens for the different themes, it'll be straightforward to implement mockups. Hoping to get started on this by EOW. Sorry about the current confusion.

1. I added a light theme version to the [Figma file](https://www.figma.com/design/1bHJvrhzQNLnDqT3WRgqzn/organizations?node-id=2-25&t=s8XHCo20OuSDQbVA-1) and adjusted the colors so it passes accessibility tests 
2. Makes sense, I wanted to ask about how you're handling this. I've now updated the colors in Figma with full-tone colors
3. What do you think about shortening it to "This feature has not yet reached general availability (GA). + link". Not strongly opinionated though. I assume the design for the tooltip is the default of what you have used until now. That's fine :) 
4. Yes, that's the optimal way, but we need a place to document this otherwise it's easily forgotten. I'm hoping to jump into the basics of defining colors by EOW. 

Note: I slightly updated the blue tone to be consistent with the blue tone that we use for visualizing build times [[1](https://www.figma.com/design/Zm4W96k6oawgS8gXIKKpk8/Provisioning-times?node-id=91-6955&t=i3QaBEoEsUH2zOYA-1)]. I want to avoid using almost the same colors but not fully. Could you look at the [Figma file](https://www.figma.com/design/1bHJvrhzQNLnDqT3WRgqzn/organizations?node-id=2-25&t=s8XHCo20OuSDQbVA-1) again and adjust the colors accordingly? 
Sorry, for the back and forth. This has to get easier 💪

<img width="518" alt="Screenshot 2024-09-17 at 10 57 54" src="https://github.com/user-attachments/assets/e0804dc1-d221-406c-a023-636cff6b1a41">

**Comment by Parkreiner** [comment]
@chrifro Yeah, to be clear, Tailwind was actually on our side for the dark theme. I had already double-checked the colors, because I also don't want random inconsistencies. And it turns out, the 400-weight color at that low transparency on a black background is exactly the same as the 950-weight

But I can definitely get all the other colors taken care of

**Comment by Parkreiner** [comment]
@chrifro @Kira-Pilot Okay, last stretch.
- Colors updated
- Tooltip header removed

Just making sure: do we have a list of all the places where we want to add the badge?
 
Because I think it'd be a little hard to squeeze it in for the organizations dropdown on the workspaces page (the dropdown barely fits the "organizations" text just by itself)
<img width="1400" alt="Screenshot 2024-09-17 at 2 56 40 PM" src="https://github.com/user-attachments/assets/4dd56c48-bc64-47f9-9d11-d8f000566340">

Similarly, I'm a little worried about applying it too liberally, because then on some pages, it can feel like a bit much:
<img width="1500" alt="Screenshot 2024-09-17 at 2 52 21 PM" src="https://github.com/user-attachments/assets/1237f823-bf23-4f14-90c4-282af136ae4a">

**Comment by Kira-Pilot** [comment]
@Parkreiner, thanks for your work here! I am okay with leaving the badge off the dropdown on the `workspaces` table view.

> How do we feel about removing the large badge from the page header? We'd still have a beta badge that would label the full list of organization options, and it'd be on every organization page

Hmmm, if we remove it from the header, how would it be located on every organization page?
Something to keep in mind - I think we may end up redesigning the Organizations side menu in favor of a org drop-down that sits at the top of every page. I'll let @chrifro weigh in with her thoughts here.

**Comment by chrifro** [comment]
>it'd be a little hard to squeeze it in for the organizations dropdown on the workspaces page

I agree on dropping the label from the organization drop-down

>How do we feel about removing the large badge from the page header? We'd still have a beta badge that would label the full list of organization options, and it'd be on every organization page

I'd keep the labels as they are right now. FYI, here is a follow-up issue regarding the organization structure #14654
