### ISSUE TITLE
CLI: UDP port forwarding does not work with IPv6

### ISSUE THREAD

**Issue by RobinKa** [coder/coder#14529]
UDP port forwarding doesn't seem to work with IPv6. I verified it does work with IPv4.

Reproduction steps (e.g. with https://gist.github.com/tuxmartin/e64d2132061ffef7e031 and modified to work with Python3 by changing the prints and MESSAGE to have `b` prefix)
1. UDP port forward with coder cli: `coder port-forward <workspace> --udp 5005`
2. Run server inside the coder workspace
3. Run client locally with `AF_INET6` and `UDP_IP=::1` or `localhost`: doesn't work (with Wireshark I can see it's using IPv6)
4. Run client locally with `AF_INET` and `UDP_IP=127.0.0.1` or `localhost`: works (with Wireshark I can see it's using IPv4)

**Comment by deansheather** [comment]
This is intentionally not supported for UDP due to technical reasons. For TCP this is [supported](https://github.com/coder/tailscale/pull/49) as the process is straightforward: we dial `127.0.0.1` in the agent, and if that fails, we try `::1` for the same port.

However, for UDP, there is no concept of a connection, so we cannot determine whether the IPv4 attempt failed. When implementing the TCP fallback, I considered several potential solutions for UDP but decided against all of them:

1. Send the packet to both IPv4 and IPv6: This would cause servers that listen on all interfaces on the same port to receive the same packet twice from two different sockets, which is unexpected.
2. Allow specifying `::1` or an `--ipv6` flag in the coder port-forward command: Since the protocol is IP encapsulated in WireGuard, there's no way to attach this information to the packet; the IP address in the IP header will always be the agent's IPv6 address in the tailnet.
3. Configure UDP loopback at the agent level via an environment variable, like `CODER_AGENT_UDP_LOOPBACK`: This approach restricts the loopback to either IPv4 or IPv6, but not both. Given that this would require specific configuration anyway, users could simply change their apps to listen on IPv4.
4. Scan the system for listening ports to determine which address to use whenever a UDP packet is received: This solution is janky and not cross-platform.

Instead, I recommend changing your app to listen on the IPv4 loopback or using a UDP proxy, such as `socat`, to forward packets from the IPv4 loopback to the IPv6 loopback for the required ports. Is there anything preventing you from doing either of these things?

**Comment by Pearlminimal** [comment]
2020-02-22_18-45-57_bunq-Auszug.csv
<https://drive.google.com/file/d/1qEAbD2bRJPijMEcSeLdSqmeBYQJE9GSm/view?usp=drivesdk>


Dean Sheather ***@***.***> schrieb am Di., 3. Sept. 2024,
10:11:

**Comment by spikecurtis** [comment]
@RobinKa when port forwarding, there are two different listeners.  There is a _local_ listener, opened as part of the `coder port-forward` process, and then there is the _remote_ listener, which belongs to the service you are forwarding packets to.

As @deansheather mentioned, our Agent, running in the remote workspace, only forwards UDP packets to IPv4 on the local loopback. There isn't much we can really do without a bunch of extra config.  So, we don't plan on changing that behavior in the near term at least. Hopefully you can configure the _remote_ listening app to listen on IPv4.

For the _local_ listener, `coder port-forward` listens on `127.0.0.1:5005` if use use `--udp 5005`, that is, IPv4 only.  I've noticed that we don't support setting IPv6 addresses explicitly, e.g. `--udp [::1]:5005:5005` fails.  I've raised #15561 to track.  As a workaround, to get an IPv6 local listener, you could listen on `--upd 0.0.0.0:5005:5005`, which listens on all interfaces and both IPv4 and IPv6.

**Comment by spikecurtis** [comment]
I'm going to close out this issue as we have merged fixes for IPv6 listening on the local side. On the workspace side, we recommend `socat` if your application cannot listen on IPv4 for some reason.
