### ISSUE TITLE
Notifications: improve wording

### ISSUE THREAD

**Issue by mtojek** [coder/coder#14893]
Follow-up on an old PR -

We need to improve the wording of our notifications. The rendered [testdata](https://github.com/coder/coder/tree/e6d8f674ad48a601f25bb98420a14f1150914ead/coderd/notifications/testdata/rendered-templates) can be a reference point.

- [x] [TemplateTemplateDeleted](https://github.com/coder/coder/blob/e6d8f674ad48a601f25bb98420a14f1150914ead/coderd/notifications/testdata/rendered-templates/TemplateTemplateDeleted-body.md.golden)  
   * missing comma after name
   * support template display name
- [x] [TemplateUserAccountActivated](https://github.com/coder/coder/blob/e6d8f674ad48a601f25bb98420a14f1150914ead/coderd/notifications/testdata/rendered-templates/TemplateUserAccountActivated-body.md.golden)  
   * missing new line after name
   * mention the real name of the user
   * might be good to add information who activated the account
- [x] [TemplateUserAccountCreated](https://github.com/coder/coder/blob/e6d8f674ad48a601f25bb98420a14f1150914ead/coderd/notifications/testdata/rendered-templates/TemplateUserAccountCreated-body.md.golden)  
   * mention the real name of the user
   * might be good to add information who created the account
- [x] [TemplateUserAccountDeleted](https://github.com/coder/coder/blob/e6d8f674ad48a601f25bb98420a14f1150914ead/coderd/notifications/testdata/rendered-templates/TemplateUserAccountDeleted-body.md.golden)  
   * mention the real name of the user
   * might be good to add information who delee the account
- [x] [TemplateUserAccountSuspended](https://github.com/coder/coder/blob/e6d8f674ad48a601f25bb98420a14f1150914ead/coderd/notifications/testdata/rendered-templates/TemplateUserAccountSuspended-body.md.golden)  
   * missing new line after name
   * mention the real name of the user
   * might be good to add information who suspended the account
- [x] [TemplateWorkspaceAutoUpdated](https://github.com/coder/coder/blob/e6d8f674ad48a601f25bb98420a14f1150914ead/coderd/notifications/testdata/rendered-templates/TemplateWorkspaceAutoUpdated-body.md.golden)  
   * missing new line and comma after name
   * empty line before `Reason for update`
- [x] [TemplateWorkspaceAutobuildFailed](https://github.com/coder/coder/blob/e6d8f674ad48a601f25bb98420a14f1150914ead/coderd/notifications/testdata/rendered-templates/TemplateWorkspaceAutobuildFailed-body.md.golden)  
    * missing comma after name
    * no new line before `The specified reason...`
- [x] [TemplateWorkspaceDeleted](https://github.com/coder/coder/blob/e6d8f674ad48a601f25bb98420a14f1150914ead/coderd/notifications/testdata/rendered-templates/TemplateWorkspaceDeleted-body.md.golden)  
    * missing comma after name
    * no new line before `The specified reason...`
- [x] [TemplateWorkspaceDormant](https://github.com/coder/coder/blob/e6d8f674ad48a601f25bb98420a14f1150914ead/coderd/notifications/testdata/rendered-templates/TemplateWorkspaceDormant-body.md.golden)  
    * missing comma after name
- [x] [TemplateWorkspaceManualBuildFailed](https://github.com/coder/coder/blob/e6d8f674ad48a601f25bb98420a14f1150914ead/coderd/notifications/testdata/rendered-templates/TemplateWorkspaceManualBuildFailed-body.md.golden)  
    * consider the template display name
    * no new line before `The workspace build...`
- [x] [TemplateWorkspaceMarkedForDeletion](https://github.com/coder/coder/blob/e6d8f674ad48a601f25bb98420a14f1150914ead/coderd/notifications/testdata/rendered-templates/TemplateWorkspaceMarkedForDeletion-body.md.golden)  
    * missing comma after name
- [x] [TemplateYourAccountActivated](https://github.com/coder/coder/blob/e6d8f674ad48a601f25bb98420a14f1150914ead/coderd/notifications/testdata/rendered-templates/TemplateYourAccountActivated-body.md.golden)  
    * missing new line after name
    * might be good to add information who activated the account
- [x] [TemplateYourAccountSuspended](https://github.com/coder/coder/blob/e6d8f674ad48a601f25bb98420a14f1150914ead/coderd/notifications/testdata/rendered-templates/TemplateYourAccountSuspended-body.md.golden)  
    * missing new line after name
    * might be good to add information who suspended the account

**Comment by SasSwart** [comment]
Requesting a mutex on this one. I'll assign it to myself as soon as my access is granted, which I will also request shortly.

**Comment by SasSwart** [comment]
Feedback so far:

Simpler formatting updates have been made in #14967, which is under review.

I've looked into how the notifier works so that I can understand how to make more complicated changes. I plan two more change sets.

The first will contain updates to the notification templates where the data that should be added is already part of the notification payload. 

The second will deal with notifications for which such additional information is not yet in the payload object. For this final change I will need to look into how to safely add more information to the payload. Because we do not support empty fields in our templates (https://github.com/coder/coder/blob/adffe60de5c2464620705999266635c4c6b3a866/coderd/notifications/render/gotmpl.go#L23), this would be a backward incompatible change as far as I can tell. We would need to version the payload.

I'm also curious about the risk of the Payload struct becoming a kind of god-struct. As it becomes larger over time to support more diverse notifications, it might start to contain information from disparate domains that might be cumbersome to populate in all cases.

cc @mafredri @dannykopping @mtojek

**Comment by SasSwart** [comment]
@mafredri Are we happy to close this one? I've merged multiple PRs that address all of these.
