### ISSUE TITLE
Evaluate `coder_workspace_tags` during template create/push

### ISSUE THREAD

**Issue by bpmct** [coder/coder#15427]
The `coder_workspace_tags` data source is not respected or read from the template during template imports, but it works for template builds. As a workaround, the admin must run a generic provisioner simply for template imports AND/OR set tags manually in the template UI.

This is a bad workaround as certain provisioners must be run just for template imports. From #15047:

> It's definitely a bug that we don't process coder_workspace_tags for template import jobs. A full fix would have us directly inspect the HCL on coderd to find the coder_workspace_tags and the coder_parameters, then resolve the tags based on the parameters passed to the import job.

Related PRs:
- [x] https://github.com/coder/coder/pull/15236
- [ ] Upcoming PR to evaluate in template imports

**Comment by johnstcn** [comment]
One potential issue with this approach is that the use of functions will be severely limited.
Terraform does not export its [default set of functions](https://github.com/hashicorp/terraform/blob/e044e569c5bc81f82e9a4d7891f37c6fbb0a8a10/internal/lang/functions.go#L54), to be used while evaluating Terraform. Even if we were to copy that directly, there are a number of functions also defined in `internal/lang`. 
In order to allow using the full set of functions while taking the current 'static analysis' approach, we'd essentially have to manually vendor all of the function definitions.

**Comment by bpmct** [comment]
> One potential issue with this approach is that the use of functions will be severely limited. Terraform does not export its [default set of functions](https://github.com/hashicorp/terraform/blob/e044e569c5bc81f82e9a4d7891f37c6fbb0a8a10/internal/lang/functions.go#L54), to be used while evaluating Terraform. Even if we were to copy that directly, there are a number of functions also defined in `internal/lang`. In order to allow using the full set of functions while taking the current 'static analysis' approach, we'd essentially have to manually vendor all of the function definitions.

This applies to workspace builds too, right? Not just template builds. We may want to extract function handling or these other edge cases into another issue.

**Comment by johnstcn** [comment]
https://github.com/coder/coder/pull/15578 adds logic to extract and validate tags from uploaded templates.
Docs are updated in https://github.com/coder/coder/pull/15620.
