### ISSUE TITLE
feat: do not show sensitive values in terminal 

### ISSUE THREAD

**Issue by bpmct** [coder/coder#1903]
## What is your suggestion?

Change examples to ask users to specify a `.tfvars` file, or use the cloud the host machine may already be authenticated with (e.g kubectx, aws session).

## Why do you want this feature?

Remove secrets from being entered in shell or screen recordings

## Are there any workarounds to get this functionality today?

A user can edit the template or specify params this #1541 

## Are you interested in submitting a PR for this?

Yes

**Comment by kylecarbs** [comment]
What do you think about explaining in `coder templates init` that it's *very expected* for users to modify the templates? I feel that this isn't obvious enough, and users get errors that they could easily fix, but aren't sure if it's a bug in Coder or not.

**Comment by ketang** [comment]
By "users" here this means admins and owners, right?

If they're getting errors, though, we need to fix them.

**Comment by kylecarbs** [comment]
Errors like:
```
You don't have a default VPC subnet.
```
are something only they can fix, and we can't make templates that work for all cloud scenarios, since all clouds are unique! Because of this, we should educate the user that they might need to modify the templates, and that's entirely expected. We have a warning right now, but it should probably be louder.

**Comment by ketang** [comment]
Aaah got it.

**Comment by bpmct** [comment]
Will close this and re-open one related to clarifying that users can edit templates.
