### ISSUE TITLE
Decide how to handle canceling builds

### ISSUE THREAD

**Issue by presleyp** [coder/coder#1928]
Here are some notes on how we might implement @spikecurtis's idea of not exposing `cancel` jobs alone to the user, but rather always pairing them with `start` or `stop` jobs so that the workspace is always in a meaningful state. One potential issue is that the `cancel` job could succeed and the `start` or `stop` job fail, so the `canceled` state may not be totally avoidable.

Reasons a user might want to cancel a `start` job and buttons they want in that scenario (button label in bold and then API requests it would call:
1. I changed my mind, I don't want to start right now. **Cancel** (issues cancel followed by stop)
2. The job is hanging, I guess I can't start right now, so I don't want to waste resources, I want to stop. **Cancel** (cancel, stop)
4. The job is hanging, but I'm feeling lucky, I want to try starting again. **Retry** or **Restart** (cancel, start)
5. I made an edit, now I want to start with the edits included. **Restart** (Retry doesn't sound as good here) (cancel, start)

Reasons a user might want to cancel a `stop` job and buttons:
1. I changed my mind, I don't want to stop right now. **Cancel** (cancel, start)
2. The job is hanging, I guess I can't stop right now, leave me in a meaningful state. **Cancel** (cancel, start)
3. The job is hanging, I want to try stopping again. **Retry** (Restop sounds weird) (cancel, stop)

**Comment by spikecurtis** [comment]
> One potential issue is that the cancel job could succeed and the start or stop job fail, so the canceled state may not be totally avoidable.

I'd call that a failed job, same as if there were no cancelled job.

**Comment by f0ssel** [comment]
What are the exact decisions needed here? I'm happy to try and weigh in.

**Comment by misskniss** [comment]
I would like to include when this decision should take effect. Is this something that we are trying to bring in for Community? If so, go ahead and label it for Community.

**Comment by ketang** [comment]
As long as we have cancellation functionality with a name that users can understand, we can take as long as we want.  I think cancellation is necessary for Community, but perfectly-named cancellation is not.

**Comment by misskniss** [comment]
Leaving this as is for Community. We can come back to it.

**Comment by Kira-Pilot** [comment]
I just wanted to drop a gif of the resulting UI here (I think this is the right ticket) because I encountered this again today and thought the indeterminate state was a little confusing - you can see the user is presented with both start and stop options:
![Kapture 2022-06-07 at 13 52 15](https://user-images.githubusercontent.com/19142439/172451108-7b160f7b-2adb-4cfa-98f4-4dd594d8c576.gif)

Regardless of how we choose to handle this on the BE, it would be nice to lend a little more clarity to the FE, maybe by hiding some buttons or something.

**Comment by ketang** [comment]
Oh yikes, having both start *and* stop is not good not at all.

**Comment by spikecurtis** [comment]
> Oh yikes, having both start and stop is not good not at all.

Wait, why?  If I cancel a Start, why is it wrong to Start again? Why is it wrong to Stop?

**Comment by ketang** [comment]
If your workspace incarnation `i` is currently stopping, I think you shouldn't be able to hit the stop button again.  It won't do anything.  The presence of the active stop button implies that previous attempts to stop didn't take.  I also think (*for now*) you shouldn't be able to spin up incarnation `i+1` because we haven't validated the need nor designed a UI that can unconfusingly represent that.

**Comment by spikecurtis** [comment]
Start / Stop / Delete are being shown after the Action is cancelled, not while the workspace is stopping.

I agree that if the Stop ~build~ action is currently pending/executing (both I believe are interpreted as `Stopping` in the UI), you can't Stop again.  But if you _Cancel the Stop_, then you should be able to run a new Action with any transition.

**Comment by ketang** [comment]
In that situation you shouldn't be able to run Start, so it avoids the problem of having Start and Stop buttons simultaneously.
