### ISSUE TITLE
Bug: Changing role error is not specific to backend error

### ISSUE THREAD

**Issue by Emyrk** [coder/coder#1932]
## Steps to Reproduce

1. Go to `Users` page
2. Attempt to change your own roles
3. Error is: `Error on update the user roles`

## Expected

The backend payload is `{"message":"You cannot change your own roles."}`. We should elevate a more detailed error in the toast error.

## Actual

Error is always the same error regardless of backend text.

## Screenshot

![Screenshot from 2022-05-31 15-15-55](https://user-images.githubusercontent.com/5446298/171279394-5c46db51-c851-4861-9389-d0701163ae13.png)

## Notes

Our frontend does constant errors in a lot of places, we should elevate backend text.

**Comment by Emyrk** [comment]
@presleyp  pinging you on this. The UI doesn't show the right error for changing your own role.

**Comment by presleyp** [comment]
@BrunoQuaresma I started on this, just having the XService display the error's message if it's an `Error`, else the standard error from `Language`, and the problem is that it shows "Request failed with status 400" instead of the nice error message that I see in the Network tab. I think you had thoughts about how we can get the good error message into XState, right?

**Comment by Emyrk** [comment]
@presleyp I did this for suspended users logging in: https://github.com/coder/coder/pull/1849

Bruno helped me out.
