### ISSUE TITLE
Delete awkwardness and 410 error instead of taking user to Workspaces list after deleting the workspace

### ISSUE THREAD

**Issue by misskniss** [coder/coder#1955]
Steps to repro: 

1. Create a workspace
2. Select that workspace from the workspaces list
3. Select Delete Workspace and confirm
4.  --> User just gets sent to the workspaces list when the workspace is still present and the status says Queued. It should say `'Deleting...`
![Queued.png](https://images.zenhubusercontent.com/588b7bd751aa2c305772f431/7a26e632-d43a-4260-9905-ad4811962b81)
Also --> We should keep them on that workspace rather than kicking them all the way out to the main list.
5. Click on the Workspace --> Status = Deleting,,,
![Correct job status.png](https://images.zenhubusercontent.com/588b7bd751aa2c305772f431/b83e5e2b-c822-4ab7-bd0c-c9fe0729bb80).
6. The Logs show it completes, refreshing the logs page keeps it on the logs page BUT the workspace is technically not there. This is OK. 
![Logs confirm job finishes.png](https://images.zenhubusercontent.com/588b7bd751aa2c305772f431/8ebdf251-312b-40f1-abb3-51f3299c8e4f)
7. Hit 'Back' in your browser --> User gets this 410 error when they should be take back to the workspaces list. 
![410 error deleted workspace.png](https://images.zenhubusercontent.com/588b7bd751aa2c305772f431/ce807cd7-729a-4137-825e-1557030d9ef7)

**Comment by presleyp** [comment]
I wrote a decision ticket about how to handle deleting #1837, where we decided that eventually we want to be able to see a deleted workspace (so no 410 error), but that requires a backend change. So in the meantime I went with the redirection so you don't get the error on the page you're looking at.

**Comment by Kira-Pilot** [comment]
@presleyp what I'm hearing is:

- we should keep the redirect, so I should ignore this comment : "Also --> We should keep them on that workspace rather than kicking them all the way out to the main list."
- I should fix the status that says `Queued` instead of `Deleting...`
- I should fix the back button. We should route back to the workspaces page.

Does the above AC look good to you?

**Comment by presleyp** [comment]
- add query param to fetch deleted workspace
- delete any code related to the now-unnecessary redirect
- consider conditionally rendering parts of the workspace page that don't make sense when deleted?
- fix "queued" status - should show workspace status which is never that, I think?

You won't see the deleted workspace in your list but that's okay. Back will work.

**Comment by Kira-Pilot** [comment]
Just a note: queued status was the result of workspaces list not refreshing and is no longer an issue because we're not redirecting: 
![Screen Shot 2022-06-09 at 9 29 12 AM](https://user-images.githubusercontent.com/19142439/172887528-ed2b9bf4-99d6-4ed1-b327-c9d061ae93aa.png)

Eventually we should consider making the entire workspaces list realtime, but that is outside the scope of this ticket.
