### ISSUE TITLE
Find viable design option for "Open in Terminal" and other apps with icon and text to save space

### ISSUE THREAD

**Issue by ammario** [coder/coder#2003]
<img width="1129" alt="image" src="https://user-images.githubusercontent.com/7416144/171725087-3c1f4693-9389-449b-a5be-75c0e2d362dc.png">

An icon would be just as clear and takes up less space. @kylecarbs may be doing this already as I know he's reworking the resources card.

(cc @mtm20176 too)

**Comment by ammario** [comment]
Yeah, a better and larger icon sorry lol. E.g:
<img width="434" alt="Screen Shot 2022-06-02 at 2 50 17 PM" src="https://user-images.githubusercontent.com/7416144/171726160-96454334-d916-4014-b4e2-380c55f3253f.png">

**Comment by presleyp** [comment]
@Kira-Pilot am I remembering right that a label is better for screen readers? Or is there a workaround?

**Comment by misskniss** [comment]
Let's have the team work on a few design options here to handle the accessibility AND the cleaner UI. Changing this ticket to a design scope.

**Comment by presleyp** [comment]
Collecting concerns about resource card design:

- not showing enough identifying info about agents
- what happens when the name of the resource is long
- some resources won't have any agents 
- we'll have multiple access links
- access links are high priority to display

Questions:

- is it important to show the link between a resource and an agent? That is, what are the downsides to a v1-like card that collects all access links?
- what should we expect in terms of resource name length, agent name length, number of resources, number of agents per resource (like what's the max)?
- will Dev URLs/applications have user-defined names? With there be a length limit on those names? How many applications might a user have?
- what do users want to know about their resources and agents? Will this stuff mean anything to the average user?

Tentative solution:

Separate Resources from Agents.
The Resources card can just contain a list of resources and be fairly compact, no table needed.
The Agents card can contain a table with the Agent, Access, and Status columns, plus a Resource column to show which resource it's in. It will save vertical space because there will be no blank rows for non-existent agents.
Cells with variable-length information can have optional scrolling if they overflow.

Layout could be: 
Status-card
Agents-card
Resources-card Schedule-card
Timeline-card

Concerns: having resources in the agents card and resources card is redundant, but is the only way to both avoid blank agent rows and display agentless resources. What would be an elegant design here? If the average user doesn't need to see everything we're currently displaying, we could put some of it in a collapsed section or something like that.

**Comment by ammario** [comment]
> * is it important to show the link between a resource and an agent? That is, what are the downsides to a v1-like card that collects all access links?

In v1 there was only one compute environment. In v2 there can be many, so I think we have to show the relationship.

> * what should we expect in terms of resource name length, agent name length, number of resources, number of agents per resource (like what's the max)?

I'm not sure about name lengths, but I can't imagine above 255 characters. 

I believe there can only be one agent per resource. In theory, we should be able to support an unlimited number of resources. The terraform for our consumer product had 300 resources. We have a vision that people will use Coder to create lightweight mimics of their production environment, so we should expect even more than 300 eventually. We can certainly wait before implementing sorting, filtering, searching and pagination though.

> * will Dev URLs/applications have user-defined names? With there be a length limit on those names? How many applications might a user have?

Yes for Applications. I can't think of any other way we'd be able to show code-server as "code-server", etc. I think for DevURLs we're using the port, workspace name and username. Theoretically it can get very long.

If v1 is any indication, a user will have on average 3 applications but up to 10. We can't limit the number here, either.

> what do users want to know about their resources and agents? Will this stuff mean anything to the average user?

For agents: 

- CPU used / total
- Mem used / total
- Disk used / total
- OS
- Connection status

There's probably more and we won't figure them all out now. These fields will also be sparse. For example, we may want to show GPU usage when one is available. We will want to display RAM differently depending on OS, since virtual memory can be nuanced. Due to field sparseness and quantity, a table is a bad way to display agent information.

An idea is putting the agent information in some area under the resource name. By breaking free from the table, we can relentlessly scale the number of fields.

<img width="1027" alt="image" src="https://user-images.githubusercontent.com/7416144/172488007-2c3cfdd7-0e11-4fc5-b0da-0ce242b7164f.png">

I also think your suggest of showing the agent resources separately from the inert resources makes sense. The data structure is quite a bit different.

**Comment by ketang** [comment]
Just want to reiterate that "agent" is not meaningful language to our user (#2063).  We should call it something different like "compute."

**Comment by ammario** [comment]
I suggest we take this conversation to Figma. My brain hurts converting these text posts into mental imagery, and we may even be talking about the same thing and not realizing it.

**Comment by presleyp** [comment]
We should definitely go to Figma, but first I want to get all the info straight, because right now I don't know what I'd suggest.

If we're expecting to have a ton of resources, we can't just list them all on the workspace page, like we'd need a Resources page (per workspace). Does that sound right @kylecarbs @ammario ? If so, then that reinforces the idea that application links need to be separate from the resources list, because applications are too important to bury. I don't know how to display them yet, but that's an important piece of the puzzle.

**Comment by tjcran** [comment]
Relatedly: #2169

**Comment by misskniss** [comment]
After a long discussion in Office Hours today we decided that this change would be either a small clarity improvement or a potential confusion addition that we need more feedback from customers first to know if this is worth the change for now. We are pulling it back into the backlog until we get some time with this in the wild.

**Comment by presleyp** [comment]
We discussed this in office hours and decided that because we want to show the user all of the info currently there, and the current design is not a major problem, we will close this ticket. However, https://github.com/coder/coder/issues/2422 will open up a bit more space in the resources card.
