### ISSUE TITLE
Codersdk: make workspace_build.deadline a pointer

### ISSUE THREAD

**Issue by johnstcn** [coder/coder#2015]
# What

Change this

```
type WorkspaceBuild struct {
    ...
    Deadline time.Time `json:"deadline"`
    ...
```

To this:

```
type WorkspaceBuild struct {
    ...
    Deadline *time.Time `json:"deadline"`
    ...
```

# Why

The FE currently needs to check for the zero-value of `time.Time` for 'falsey' values.
Making this a pointer would allow passing `null` and avoid this need.

**Comment by mafredri** [comment]
Since we're starting to have quite a few pointers, I would suggest two options:
1. Start using `type Null[Type] struct` types where `Valid` is set to true/false
2. Separate the fields so that there is `Deadline time.Time` and `DisableDeadline bool` (as an example)

For 1. we could either maintain our own package of types used by the API, or rely on pre-existing work. One example is https://github.com/guregu/null/blob/21596e8e52a426a14cd73b22f6ffa4d31165302f/time.go#L12-L16. These would support JSON (de-)marshaling and be slightly safer to use than pointers (and dereferencing).

For 2. first I would like to ask: Why does the frontend need to pass `null` vs `undefined`? If we don't care about changing the value, then undefined should be just fine. In TypeScript this would simply read `deadline?: string` which matches the API contract when using JSON `omitempty`.
