### ISSUE TITLE
Standalone workspace directly on Coder host, no templates

### ISSUE THREAD

**Issue by bpmct** [coder/coder#2108]
For simple Coder deployments, it would be great to code directly on the Coder host (where you deployed Coder). Similar to cloud shells in AWS, GCP, Azure, or Proxmox. 

- deploy Coder and instantly have a workspace + web IDE
- create/edit templates directly via the web terminal/code-server
   - deploy Coder on AWS with one-click, log in, add templates
- use Coder in "single player mode" without having to create templates
   - quick time to IDE like code-server, but with support for desktop IDEs + JetBrains
- install cloud CLIs for use with templates (`aws-cli`, `terraform`, `gcloud`, `kubectl`)

Since this poses a risk for large-scale deployments or IaC-only environments, a feature like this should be:

- optional: enabled/disabled via an environment variable
- role-restricted: only admins (or the "admin" user) can use it

Concepts:

!["new workspace" screen](https://user-images.githubusercontent.com/22407953/172272503-f95feb8e-32a8-4415-9b87-b7a26f5534ea.png)

![workspaces page](https://user-images.githubusercontent.com/22407953/172272547-84204acd-257e-4acc-9563-cbd2d99ecb45.png)

or (like cloud shell in GCP)

![cloud shell concept](https://user-images.githubusercontent.com/22407953/172389038-8ca2a088-ad12-4f06-a3dd-bac058a1bffc.png)

**Comment by ketang** [comment]
Absolutely positively disabled by default.

Would something based on Docker or Docker Compose be appropriate here?

**Comment by bpmct** [comment]
> Would something based on Docker or Docker Compose be appropriate here?

I imagine this would be similar/equivalent to (pre)installing the Docker template on Coder and creating a workspace? I think this would work well in many cases. A "kitchensink" Dockerfile with `aws-cli`, `gcloud`, `terraform`, `kubectl`, and `code-server` can be provided. However, it's unclear to me how the user would add additional dependencies to an image, if they wanted to use this primary workspace as a dev machine or add more cloud CLIs.

Serving a workspace directly on the host achieves something closer to code-server's `Install` -> `Add dependencies` -> `Start coding` flow. There's no need to modify container images or templates. Just set up like any new computer. There are advantages and disadvantages to both 🤷🏼 

It's also worth mentioning that Proxmox and GitHub Enterprise give the "installer/admin account" direct access to the host through their product for configuration or debug purposes. Because of this, I'm not convinced this feature request is an anti-pattern, but I see why it should be disabled in many deployments that prefer to use IaC/GitOps to the manage Coder host environment and templates.

**Comment by bpmct** [comment]
The more I think about it, it doesn't really matter if a container image has aws-cli or gcloud, because it must be present on the host itself to work with Coder templates.

**Comment by jsjoeio** [comment]
@bpmct for those who might not be familiar, can you explain what you mean by Coder host? Like is this a sandbox, is this a "trial provider" or something else? 

And also the motivation (maybe mention time to first workspace, reducing friction for trying out the product)

**Comment by bpmct** [comment]
A Coder host would be whatever machine you are hosting Coder on (laptop, AWS VM, container, etc) @khorne3 is working on a doc that should help us aligning on terminology ;)

Added one sentence about time to first workspace

**Comment by jsjoeio** [comment]
Re: "time to first workspace" - we discussed how this compares in v2 vs code-server. Hoping that using a Coder host would reduce this and make it easier to try out the product. 

<img width="1205" alt="image" src="https://user-images.githubusercontent.com/3806031/172445210-ed427e9f-bb88-45c7-811c-c27c99039269.png">

**Comment by spikecurtis** [comment]
Calling direct, un-encapsulated access to the Coder host a "workspace" feels like a bad plan.  After all, the person who deploys coder to a server _almost certainly_ already has SSH (or similar) access to that machine.  We are not providing any value by recreating that access.

One other observation is that currently, the coder install just installs the coder binary, and so basically everything will fail because Terraform isn't installed.  So, there is a whole pre-req that we need to include in our installer or document.  We could include an optional step to get Docker installed, at which point we could get a Dockerized workspace running on the same host fairly easily.

**Comment by bpmct** [comment]
> After all, the person who deploys coder to a server almost certainly already has SSH (or similar) access to that machine. We are not providing any value by recreating that access.

I think it would provide equal value as code-server (use web IDE) + additional value to connect to different web apps or IDEs.

> We could include an optional step to get Docker installed, at which point we could get a Dockerized workspace running on the same host fairly easily.

I do agree this is the best solution, if the home volume in the container shared with a host "coder" user. Then, for example, one could authenticate with AWS from the container and `~/.aws/config` is used. Same for kube context, etc.

**Comment by ammario** [comment]
I'm in support of the proposal. We are adding value through convenience. Want to quickly manage your Coder deployment? Open it up in code-server.

I think we can achieve this without additional configuration, too.

The admin role as it stands is a misnomer. It should probably be "root" or "deployer". I prefer "root" since everyone knows you're not supposed to use "root" except transiently. Everyone also knows "root" is dangerous.

Our "root" user _already_ has full shell access to every workspace, letting them steal secrets and manipulate workspaces at will.  We have clear instructions from our customer that this is a Big Bad. Our major deployments will disable the root user. Thus, we're only adding marginal risk by letting the root user shell into the box.

Finally, this is a convenience feature so it's easily reversed. If the security costs outweigh the virality benefits, we remove it.

**Comment by ammario** [comment]
[Here](https://docs.github.com/en/enterprise-server@3.1/admin/configuration/configuring-your-enterprise/accessing-the-administrative-shell-ssh) is some precedent from GitHub Enterprise for giving superadmins shell access to the deployment.

**Comment by spikecurtis** [comment]
> Terraform isn't required on the host to use Coder.

It's not required for coderd, but it is for provisionerd and today, these run in the same process.  We have future plans to allow people to run a standalone provisionerd, but it is not yet supported.  In any case, the scenario we're discussing here is a single-machine deployment of Coder and so terraform needs to be installed.

**Comment by spikecurtis** [comment]
> Want to quickly manage your Coder deployment? Open it up in code-server.

This makes some sense to me for provisionerd, since we recommend that they run it with the environment authenticated with cloud providers.

With the caveat that coderd and provisionerd are currently joined at the hip, I don't think it makes sense to configure coderd with a remote IDE, because other than very low level config _required for coderd to function at all_ (postgres connect string, access URL, etc), coderd doesn't have persistent state on the host machine.  Our goal is to allow all the configuration that matters for coderd to be configured via APIs (and by extension, the CLI and WebUI).

**Comment by ammario** [comment]
> > Terraform isn't required on the host to use Coder.
> 
> It's not required for coderd, but it is for provisionerd and today, these run in the same process. We have future plans to allow people to run a standalone provisionerd, but it is not yet supported. In any case, the scenario we're discussing here is a single-machine deployment of Coder and so terraform needs to be installed.

If the proposed feature was implemented, Terraform wouldn't be required? I understand that it is now. 

> With the caveat that coderd and provisionerd are currently joined at the hip, I don't think it makes sense to configure coderd with a remote IDE, because other than very low level config required for coderd to function at all (postgres connect string, access URL, etc), coderd doesn't have persistent state on the host machine. Our goal is to allow all the configuration that matters for coderd to be configured via APIs (and by extension, the CLI and WebUI).

Making stub workspaces out the provisionerd is a cool idea as well. It accomplishes the same goals outlined in the OP but is more powerful as the user scales out their coder architecture.

**Comment by bpmct** [comment]
Some things discussed synchronously, still subject to change:

- code-server button will be greyed out by default, pressing it will allow user to install via install script on the host 
   - if code-server is in PATH (or running on specified port?), it will be launched
- name idea: Coder Shell, a good place to manage templates without the installing the CLI
- good candidate for README demo

**Comment by ammario** [comment]
https://github.com/coder/coder/issues/3331 moves us towards the goals of this issue in a simpler fashion.
