### ISSUE TITLE
Typing `exit` in web terminal does not show "Disconnected" until another keystroke or resizing the window

### ISSUE THREAD

**Issue by mafredri** [coder/coder#2156]
Typing `exit` in web terminal does not show "Disconnected" until another keystroke or resizing the window.

Type exit (followed by enter), nothing happens => Press enter:
<img align=left height=200px src="https://user-images.githubusercontent.com/147409/172590985-635b77ff-a102-47b2-b65a-81fbf1be4475.png"><img height=200px src="https://user-images.githubusercontent.com/147409/172590998-a3440b4d-6022-4ea9-94a5-2247ea5bb70d.png">

**Comment by mafredri** [comment]
Still an issue.

**Comment by code-asher** [comment]
I volunteered to take this since I was also going to do https://github.com/coder/coder/issues/3666 since that will touch the reconnection code anyway but it is looking like it will be a while yet before I can find the time so if someone else picks up 3666 maybe they can take a look at this as well afterward.
