### ISSUE TITLE
The `do-linux` template has small instance sizes, which aren't great for remote development

### ISSUE THREAD

**Issue by spikecurtis** [coder/coder#2180]
For the `do-linux` example template, we list machine sizes that go down to 1vCPU + 1 GB memory.  I tried running JetBrains Gateway + GoLand on it, and it crashed and burned, including disconnecting my agent from coderd.

Let's remove such small machines from the template choices, with the idea that these should be suitable for "real" remote dev and to optimize for a smooth new user experience.  If people really need tiny droplet workspaces, they can always edit the template later.

**Comment by mafredri** [comment]
Would it suffice to just change the default and improve documentation (i.e. mention JetBrains min requirements?)?

https://github.com/coder/coder/blob/567e4afdfc1446844edbf079fadacc3e2aa3dda1/examples/templates/do-linux/main.tf#L61

Even just going from 1GB to 2GB RAM is at least double the cost. Haven’t checked code server or VSCode remote requirements but they can probably make due with fewer resources.

If we can, it would be nice to be able to detect these scenarios and fail knowingly with an informative error instead of crash and burn. This way the experience would be nice with templates that are out of our control.

**Comment by spikecurtis** [comment]
> Commented out stanza in the scripts with a different value?

I like this.  I don't want to overwhelm with a bazillion options by default.  Just a handful or fewer.

For what to include, it's a balancing act. I _want_ to steer people toward trying a machine that will _feel fast to them_ so they get hooked (so, like faster than your average laptop), but I also don't want to turn them off to the whole idea when they get the cloud bill (although, given the choice of optimizing for people who are highly price sensitive and those who are not, I'm inclined to the later).

**Comment by ketang** [comment]
How's this?  We pick the higher performance one by default, put appropriate comments in the right places about how to do something different, and invest our efforts over time to help customers maximize their cost efficiency, e.g. nicely supporting pre-emptible instances.
