### ISSUE TITLE
Bug: `coder ls` output should measure TTL from the time the provision job was completed

### ISSUE THREAD

**Issue by johnstcn** [coder/coder#2197]
My workspace took about four minutes to build today, and this is being interpreted as 4 minute "extension" by the output of `coder ls`:

![image](https://user-images.githubusercontent.com/4949514/172814338-8e258732-88a6-4a2f-b049-5742b675ad0a.png)

Currently, we're measuring from the time the workspace build job was created. We should probably be looking at the time the associated provisioner job was completed.

**Comment by ketang** [comment]
I'm new to the codebase, so tell me if this sounds right.  We need a new column in the `workspace_builds` table named something like `built_at` which contains a date/time stamp.  That starts out as null.  Then if/when the provisioner job completes successfully, we need to set the `built_at` column for that build.  We need to add that to the API response, and then when the CLI queries the list of workspaces, it needs to use that field instead of the `created_at` field it's using now.  Did I understand that correctly?

**Comment by johnstcn** [comment]
I this can actually be closed as fixed by #2402. Instead of showing the +/- extended in the "Stops after" column, I changed it to show the time remaining ([link](https://github.com/coder/coder/commit/c9691eafcba20422b8982ab34cef345e814da291#diff-1e401eb6a76f73028b9e1ec88d824123ff54e42a5a286ce34edf4e455a0f5037R103)). That information seems more useful.

**Comment by johnstcn** [comment]
> I'm new to the codebase, so tell me if this sounds right. We need a new column in the `workspace_builds` table named something like `built_at` which contains a date/time stamp. That starts out as null. Then if/when the provisioner job completes successfully, we need to set the `built_at` column for that build. We need to add that to the API response, and then when the CLI queries the list of workspaces, it needs to use that field instead of the `created_at` field it's using now. Did I understand that correctly?

We can use `codersdk.Workspace.LatestBuild.CompletedAt` ([link](https://github.com/coder/coder/blob/7a4fd12911d202047410a974ae424f3130f23e31/codersdk/provisionerdaemons.go#L66))
