### ISSUE TITLE
Rename `coder server` command to `coder launch`

### ISSUE THREAD

**Issue by ketang** [coder/coder#2466]
`coder server` sounds just like `code-server`, and I imagine endless confusion resulting from that with lots of calls where someone says "no no no codER, with an 'r'" or "no, I mean CODE server, just the editor."  Let's spare ourselves that.

Rename the `server` command to `launch`.  Keep `server` as an alias so we don't screw anything up, but update all the `-h` help text etc. to use "launch" instead of "server."

**Comment by kylecarbs** [comment]
It could become difficult for users to understand what component they are running when they execute `launch`. I'd personally expect `launch` to open an IDE maybe? It doesn't seem like it would serve anything necessarily.

I personally like the familiarity and since `code-server` is a separate command-line interface (instead of `code server`), I don't believe we'll encounter this problem frequently.
