### ISSUE TITLE
audit: Hide the auditor role in AGPL

### ISSUE THREAD

**Issue by ntimo** [coder/coder#2516]
# Current situation
Currently the admin user does not have the aditor rule assigned. Which can be confusing.

# Suggestion
Assign the default admin both the admin role and the auditor role

**Comment by kylecarbs** [comment]
@Emyrk is the auditor role even used? Seems like we could just remove it.

**Comment by Emyrk** [comment]
@kylecarbs It was added because the UI actually added the "audit" page which can only be seen in developer mode. The page is hidden when the static files are compiled. So the `auditor` role is hooked up to the UI, but the backend feature is sparse atm (table exists, but that is it atm).

What I can do is just say the "user admin" has auditing permissions and delete the auditor role? I want to keep 1 role with that permission so that the FE team has a role they can use for testing that UI feature that is already implemented.

**Comment by BrunoQuaresma** [comment]
The owner role has audit permissions, but the admin does not. Is it something we want to add?

**Comment by kylecarbs** [comment]
@Emyrk I updated the title of this. I assume it's trivial to do... thoughts?

**Comment by kylecarbs** [comment]
I think that would make sense

**Comment by Emyrk** [comment]
Interesting :thinking:. Might want to mark some roles as "enterprise" or something. But show them if the user has the role, even if the license is not enterprise.

**Comment by Emyrk** [comment]
Probably worth keeping this issue open. 

The BE returns assignable roles here: https://github.com/coder/coder/blob/79f45ede05939a73437007fd5292c897784607d4/coderd/roles.go#L23-L23

and for orgs: https://github.com/coder/coder/blob/79f45ede05939a73437007fd5292c897784607d4/coderd/roles.go#L38-L38


We need to remove AGPL roles from this is they are not enabled in the license. But if a user has the role, and no longer has the license, that role should still appear on the user in question.

**Comment by kylecarbs** [comment]
@Emyrk should we close this out? It seems relatively low pio.

**Comment by Emyrk** [comment]
I would love to close this out until someone is very adamant they need this :smile:.

This gets complicated in edge cases if someone downgrades from enterprise to APGL for example.
