### ISSUE TITLE
Generic OIDC Support RFC Update

### ISSUE THREAD

**Issue by misskniss** [coder/coder#2550]
As a company we want to update and align on our Generic OIDC support for Enterprise. 

Definition of Done (for Generic OIDC support)
@tjcran 

The requirements and context from the [original OIDC/Auth RFC](https://www.notion.so/coderhq/v2-Authn-99da0c6744d24ba88e6f413abd20a916) should still apply, but we'll want to adapt as necessary now that we have built-in and Github oauth in the product in case anything has changed from the original plan. 

## Why do we need this?

This is a table-stakes OSS feature, not intended to be included in any paid packages. We should aim for parity with v1 at a minimum, which basically includes a genericized support for OIDC apps for authentication. This is important to increase the ease of use for teams to get in, reduces security concerns for password sharing and resetting, and reduces friction for users signing in.
- When configured, these log-in options for providers should appear in the log-in window. 
- We’ll need a way for admins to configure the OIDC settings, preferably in a UI format. 

Nice to have: Built-in auth should also be able to be disabled by admins to force their users to auth with the registered OIDC app. 

## When do we need it?

Immediately. This will be necessary before the product can be sold and OIDC support will also increase our Community adoption.

**Comment by tjcran** [comment]
Update: Because a previous RFC was written and the remaining work to create a way to add an OIDC provider (backend only) is all that is necessary, we can punt on an RFC and focus on just adding implementation details into a new issue. 

The admin setup portion will only be backend and the signin form _should_ already pickup any OIDC providers that are added in the backend automatically. 

@kylecarbs @deansheather please correct me on any points if I am incorrect. Otherwise, I'll close this issue.
