### ISSUE TITLE
``coder template pull <name>`` does not pull as a folder

### ISSUE THREAD

**Issue by phorcys420** [coder/coder#2651]
* Version: ``v0.7.4+3f97767``
* Host: ``Windows``

---

``coder templates pull <name> <path>`` pulls the template and writes it as a tar instead of extracting it's contents.
``C:\Users\fr20100048\Documents\basic-env>coder templates pull basic-env basic-env``

![image](https://user-images.githubusercontent.com/57866459/175772883-8309e631-c699-4967-925a-f13b1cf869b6.png)

---

``coder templates pull <name>`` without any path prints out the tar's contents to stdout.
``C:\Users\fr20100048\Documents\basic-env>coder templates pull basic-env``

```
README.md0000666000000000000000000000052414255567654010553 0ustar0000000000000000---
name: Basic dev environment
description: Basic environment with code-server.
tags: [local, docker]
---

[...]
main.tf0000666000000000000000000000340314255560711010535 0ustar0000000000000000terraform {
  required_providers {
    coder = {
      source  = "coder/coder"
      version = "0.4.2"
    }
    docker = {
      source  = "kreuzwerker/docker"
      version = "~> 2.16.0"
    }
  }
}

[...]
```
---
Maybe getting a tar should still be possible with a ``--tar`` argument or ``--format tar`` argument? (or if ``<path>`` ends with ``.tar``?).
Also, ``coder template pull <name> .`` currently isn't possible, but that would be a nice feature to have so i'm suggesting it here since it's related.

**Comment by sreya** [comment]
Hi! So the behavior of this command is intentional. It's intended to emulate the behavior of a Linux utility where you can take the output of this command (a tar archive) and redirect it to an arbitrary file. Since `tar` is a fairly ubiquitous tool and untarring an archive is trivial it's left to the user to decide how they wish to unpack the bundle. You can check out something like `docker export <container>` which has similar behavior. 

`coder templates pull <name> .` will not work because it assumes that the destination you are providing is going to be a file that it writes to. So if you want it to work you should be able to do `coder templates pull <name> ./foo.tar`.

I have noticed that you're on Windows, is it difficult to use this command in its current state for you? I have little experience on Windows but my understanding is that it's common to drop into WSL when doing command line work.

**Comment by ketang** [comment]
WSL isn't available on all versions of Windows.

I understand wanting to align to a standard, but also `tar` is a command that is notorious for being hard to work with.

I think a decent compromise would be to have two commands.  I'm thinking `pull` does an unpacking and `export` gives you the tarball.

@kylecarbs what do you think?

**Comment by kylecarbs** [comment]
I'd rather have the tar be default behavior, but I think export is a better name.

What do you think about a --extract flag? We could default to cURL behavior, where if the output is a TTY we require explicit - as the argument.

**Comment by sreya** [comment]
I think an `--extract` flag is reasonable, we can also certainly support the case where if you specify a directory we will pick a name and write it to the directory as opposed to returning an error.

**Comment by ketang** [comment]
Well yeah, that's why you implemented it!  But `pull` sounds more like `git` than a strict downloader.  I'm trying to imagine use cases, and I think it's far more likely that someone wants the expanded form.  What is their intention when they `pull`?  It's almost always going to reading or editing.  *Sometimes* it's going to be about transporting it somewhere else, but ow we're talking about situations where it's also not in revision control or they can't just do a recursive copy.  As the default behavior it just doesn't match how people are typically going to use it.

**Comment by ketang** [comment]
I spent a few hours fiddling with templates yesterday, and I'm absolutely 100% convinced that pull should extract a directory tree.  The intermediate archive file was only ever an impediment.

**Comment by phorcys420** [comment]
I definitely think the wording was confusing, I thought it would be like ``git pull`` indeed.
Maybe make ``pull`` extract and ``download`` download a tar or something like that ?

**Comment by ammario** [comment]
We could export as a directory if stdout is detected as a TTY.

**Comment by phorcys420** [comment]
> We could export as a directory if stdout is detected as a TTY.

sounds good to me

**Comment by ammario** [comment]
> > We could export as a directory if stdout is detected as a TTY.
> 
> sounds good to me, but then in `coder pull <name> <path>`, should `path` be a dir or a tarfile ?

This gets me thinking. We could copy the UX of tar for something intuitive:

Always require a `<path>`, so the full invocation becomes `coder templates pull <template> <path>` 

- If $path is `-`, send as tar (current behavior)
- If $path is `.`, use current working directory
- Else, use $path literally

**Comment by phorcys420** [comment]
This looks good to me, except you can't pipe tars in windows (it doesn't work), so maybe add a case where if $path ends with ``.tar`` write it as a tar file.
