### ISSUE TITLE
Dashboard: Wrap agent and IDEs below resources

### ISSUE THREAD

**Issue by f0ssel** [coder/coder#2697]
I have been having trouble when I view the workspace resources because the current table layout doesn't read very clear to me. I thought that "wrapping" the agent details on a block dedicated to the resource made more sense in my mind, so I made a quick mock up. 

Would like to ask if these seem like changes we would like to make and solicit feedback. Not attached to any solution I present here just would like to reorganize in hopes it reads more clearly to users. 

Before:

![image](https://user-images.githubusercontent.com/19379394/176059893-76e8bd93-0caf-46a0-9b1d-0a41a2d5db3f.png)

After:

![image](https://user-images.githubusercontent.com/19379394/176060653-73645a6e-d99c-474a-83f4-1abfbcc8c03a.png)

Key changes:
1. Move agent and application as sub-row details of the resource row.
2. Make resources with agents collapsible and open by default (idk if I love this yet)
3. Show agent status icon without status text next to resource title to both indicate it has an agent and the general health of it

**Comment by Kira-Pilot** [comment]
Thanks for looking into this!
Some quick thoughts:
1. I like your design because it gives us more space (we can display longer resource names, apps names)
2. I would like a little more visual differentiation between rows. The grouping still isn't clear to me. 
3. I think the agent status needs a little more thought, but that is a detail. 

P.S. Agent status doesn't translate to resource status, does it? Like we can't put that status in the resource name row, right?

**Comment by ketang** [comment]
I think consolidating the agent with the compute box makes sense because all lots of resources won't have an agent, so it's often going to be unused.  Also the agent doesn't have separate significance; it's subordinate to compute, so it shouldn't be made prominent.  I personally think we shouldn't even have the word "agent" here.

**Comment by bpmct** [comment]
Here's what a multi-agent example looks like today. I'm not sure how that would look in a wrapped view. 

<img width="872" alt="Screen Shot 2022-07-22 at 8 31 50 AM" src="https://user-images.githubusercontent.com/22407953/180449738-3de37883-6311-4858-a4c5-b9718aa9f93e.png">

**Comment by kylecarbs** [comment]
I think the UI looks fine for now. Until we get feedback otherwise, this doesn't seem actionable for now.
