### ISSUE TITLE
Clarify search bar behavior for users/workspaces

### ISSUE THREAD

**Issue by Emyrk** [coder/coder#2727]
The current search bar behavior is a result of the implementation, but we should define the expected behavior.

# Questions

## Multiple params

- Should multiple options be `AND` or `OR`?
  - `role:admin,auditor` show a user with just roles: `[admin]`?
  - `owner:me owner:you` show no workspaces? All workspaces owner by either?
  - `dev-workspace crazy-workspace` show both workspaces? Neither workspace?
  - `status:active,suspended` show all users?

Should we add `and` and `or`?
- `role:"admin or auditor"`
- `role:"admin and auditor"` (maybe `admin,auditor` defaults to `and`?)

## Repeating filters

Should we allow
- `owner:me owner:you`
- `workspace-one workspace-two`

## Showing errors

Do we have a good way to show errors on search?

**Comment by ketang** [comment]
There are exactly two correct ways to go about this.  I prefer to use PostgreSQL's exact query syntax and not implement this ourselves (see #2644).

If we were to implement it some other way (which we shouldn't), I think to the best of our ability we should behave the way ElasticSearch or GMail (or Indeed) does, which I think is semantically the same as PostgreSQL, so I'll document the expected behavior here, though the syntax may vary a bit:
* `role:admin,auditor`: must be both; if you want `OR` semantics you do `role:admin OR role:auditor`
* `owner:me owner:you`: shows nothing
* `dev-workspace crazy-workspace`: shows nothing unless there is a `dev-workspace` that has `crazy-workspace` in some other searchable field
* `status:active,suspended`: as above, it requires the field to contain both `active` and `suspended`, but this particular field is single valued, so this should return nothing.  To get the hypothetical behavior you do `status:active OR status:suspended`

Yes, we should add `and` and `or` (obviously I think so based on the above).
* `role:"admin or auditor"`: the quotes indicate a phrase match, so this will search for things attached to a *single* role with the name `admin or auditor`, which yields none.  `role:"admin" OR role:"auditor"` would be the union.
* `role:"admin and auditor"`: same as above except `role:"admin" AND role:"auditor"`, more concisely as `role:"admin" role:"auditor"`

Important to note that `role` is a multi-valued field.  If you specify one `role` field in your search, a document that contains that role and others will match.  If you specify two `role` query fields with `AND` semantics, then the document must have both those values as single values in its multi-value `role` field.

* `owner:me owner:you`: allow it, though it will return nothing
* `workspace-one workspace-two`: allow it; this is a search with two tokens of any searchable field

All searches that don't specify a field can match on any field.

I think in general this is how people have been trained to expect search to work.  We should not surprise them.

**Comment by Emyrk** [comment]
My only objection to the postgres exact query syntax is to not allow sql injection obviously.

**Comment by ketang** [comment]
You take the input and apply it by using the `tsquery` function in your `WHERE`.  That should support prepared statements and all that jazz.

**Comment by kylecarbs** [comment]
The action for this can be adding a tooltip documenting the behavior! It should work just like GitHub's does.

**Comment by kylecarbs** [comment]
I think we could add docs to clarify this, but I don't think it's a big deal for now. In an effort of keeping all issues actionable, I propose we close this and reassess later on.
