### ISSUE TITLE
Support dynamic lookups for workspace parameters

### ISSUE THREAD

**Issue by ketang** [coder/coder#2781]
Scenario: I have a few Docker registries that I want my users to be able to pull images from.  As workspace parameters are currently implemented, you may be able to select the registry, but then you have to type in the image name and tag.  All the information is static.  What would be better is to start with a template that has a static list of registries and input variables for image name and tag, and then:
1. during workspace creation, user selects a registry
1. this selection triggers a lookup that pulls the list of available images from the registry, which are then displayed to the user
1. user selects an image
1. this selection triggers a lookup that pulls the list of available tags from the registry, which are then displayed to the user
1. user selects a tag
1. user builds the workspace using the specified image and tag fetched from the specified registry

Additional considerations:
* We want both a value and a display name
* Do we need to support extra security policy for URL lookups from templates?
* How do we handle constructing requests and interpreting responses?
* How do we do this in a way that is not specific to Terraform but also not unnecessarily duplicative nor using a foreign idiom?

**Comment by spikecurtis** [comment]
For private registries, we'd need to be granted credentials, and the selection process involves a back-and-forth interaction with the Coder Server, which is actually making the requests to the registry.

> How do we do this in a way that is not specific to Terraform but also not unnecessarily duplicative nor using a foreign idiom?

This probably has to come through our custom Terraform provider, as "data" the template can read.  I can't see another way for template authors to express that a parameter needs to work this way, since the input variable construction has very few fields we can use, unless we get into having "special" variable name prefixes or something hacky like that.

But, in Coder itself, this gets modeled as a new parameter source type, I'd guess.

**Comment by ketang** [comment]
> This probably has to come through our custom Terraform provider, as "data" the template can read.

There's the option of putting a layer on top of Terraform with the semantics we want.  I suspect something like that is inevitable.

**Comment by kylecarbs** [comment]
I think we can do this eventually, but only would with customer input. Since we don't have that right now, I'm going to make this not planned.
