### ISSUE TITLE
"Starts at" block looks funky and isn't responsive

### ISSUE THREAD

**Issue by ammario** [coder/coder#2799]
<img width="1379" alt="image" src="https://user-images.githubusercontent.com/7416144/177009520-e36bd085-9785-4fe8-b2e6-7d1f0da502f8.png">

The overall element is inconsistent with the other informational panels we have below and the border with the Schedule button is unnatural.

<img width="486" alt="Screen Shot 2022-07-02 at 11 59 14 AM" src="https://user-images.githubusercontent.com/7416144/177009555-c2d43dfd-8073-4fa9-9710-2b6df7003a8e.png">

Things get very funky when you enter a low breakpoint view.

cc @BrunoQuaresma @tjcran 

Related #2798

**Comment by BrunoQuaresma** [comment]
Interesting, probably you have this perception because we are doing some changes proposed here https://github.com/coder/coder/issues/2091#issuecomment-1170057727 incrementally, since the component didn't change too much after the approval. Would you have any idea in mind to improve that? The component or where to display the schedule info?

About responsive, I think this ticket will free up some space in the header #2748 but, for v2, at least for community, we decided to not make the components responsive. If we want for enterprise, we need to start  to develop the UI/UX for that.

**Comment by ammario** [comment]
@ketang I disagree with the removal of the "bug" label. The UI looks broken on small viewports, and I'm sure the developer didn't intend that.

@BrunoQuaresma I don't know how to lay it out better.

I get why we want to deprioritize the mobile view, but the product shouldn't look broken on mobile. We should either commit to a functional mobile view or remove that viewport altogether so the site looks desktop all the time.

**Comment by BrunoQuaresma** [comment]
We tried to force the desktop viewport but the browsers are ignoring it for some reason 🙃. For enterprise, I think we can make it looks good at mobile without too much effort tho.

**Comment by BrunoQuaresma** [comment]
Fixed as part of #3185
