### ISSUE TITLE
Support two-way sync from local filesystem to remote

### ISSUE THREAD

**Issue by ketang** [coder/coder#3033]
Make it possible for users to run `coder sync [<local directory>] <workspace directory>` to establish a persistent (until `<Ctrl>-c`) sync between the local/client filesystem and the remote workspace filesystem.  This functionality mostly exists in `rsync` already.  I think making this two way would require running `rsync` daemon, which requires some delicacy as `rsync` is GPL v3.

**Comment by ammario** [comment]
You're basically suggesting what [Mutagen](https://mutagen.io/) does. I tried to integrate Mutagen into v1, and I've used it extensively. There are intractable problems related to [conflict resolution](https://mutagen.io/documentation/synchronization#conflict-resolution) that are inherent to two-way synchronization and not Mutagen's particular implementation. They do as good of a job as possible managing them, but still, in my opinion, only one-way file synchronization is practical.

I'll close this for now since the functionality already exists. One just does `coder config-ssh` and then uses mutagen over SSH.

**Comment by kylecarbs** [comment]
Okteto [does this](https://www.okteto.com/docs/reference/file-synchronization/) built-in with Syncthing.

**Comment by ketang** [comment]
>I'll close this for now since the functionality already exists.

Mmm.... I'm not convinced.  90% of what we're doing already exists.  We're just trying to make it easier and more practical.

**Comment by ammario** [comment]
Yeah we tried to push this feature in v1 with little success so I think our threshold for evidence should be high.

I'm going to close for now but we can reopen in light of new information.
