### ISSUE TITLE
Autostart: workspace didn't start on schedule after build failed

### ISSUE THREAD

**Issue by maryna-hankevich** [coder/coder#3084]
Autostop build failed in the evening. The next day workspace should have been auto started in the morning but it didn't. 

Steps to reproduce:

1. Create a workspace
2. Set up Start time
3. Trigger a new build so it fails => Workspace status should be "Failed"
4. Wait untill Start time configured in step 2

**Actual Result:** auto start build is not triggered, the Workspace status = Failed, 
schedule info may be confusing (e.g. it shows "Starts at 09:00 AM, Monday through Friday" but actually it will never start as long as the workspace is in Failed state)
![image](https://user-images.githubusercontent.com/35501151/180213835-e437639b-e5a8-4db7-b474-5c9507119527.png)

**Expected Result:** auto start build triggered on schedule

**Comment by tjcran** [comment]
This seems low importance. The start/stop will continue to be triggered but will not process because the workspace isn't in a running/stopped state and the actions will just fail. 

Ideally a failed build will just not attempt the start/stop, but I don't think this is  something we need to urgently address.
