### ISSUE TITLE
RBAC authorization is slow with >80 objects

### ISSUE THREAD

**Issue by kylecarbs** [coder/coder#3098]
### Problem
On dev.coder.com I noticed the `/api/v2/workspaces` endpoint is slow when querying all. Upon doing a `pprof`, it became apparent our authentication code is the primary cause of this:

<img width="583" alt="image" src="https://user-images.githubusercontent.com/7122116/180287568-d6f0a1c7-74d7-4165-ba5f-57e67162ca7d.png">

This is requesting 85 workspaces, and the request took ~180ms (of which ~170ms seems to be auth code).

[Here is a direct download to the pprof](https://github.com/coder/coder/files/9161837/pprof.coder.samples.cpu.001.pb.gz). You can view it yourself with: `go tool pprof -http=:8080 <downloaded file>`.

### Definition of Done
I'd suggest we write benchmarks for this code. Ideally it takes significantly less than 1ms to authorize a single RBAC object.

**Comment by Emyrk** [comment]
It looks like most of the cost is in the rego evaluation. So optimizing the setup code isn't going to buy us much.

I have a PR with a benchmark test to verify any code changes made to optimize the rego policy: https://github.com/coder/coder/pull/3121

According to https://www.openpolicyagent.org/docs/latest/policy-performance/, we can probably get a speedup in the range of 2-3x. This problem will then just crop up again at the 200/300 objects. I will take some time to play with the policy.


----

The real speedup is going to come in when we add pagination and limit the results.

**Comment by kylecarbs** [comment]
Can we cache rego evaluations by any level? I think it'd be good to investigate ways to improve the performance. I'm a bit surprised by the 200/300 objects performance limit.

**Comment by Emyrk** [comment]
It's not a limit, their basic RBAC was benchmarking around 0.045032ms. Ours is currently benchmarking around 0.362712ms.

300 objects at their benchmark is 15ms. Our RBAC has some extra features (which maybe we can remove now with some of the decisions we made early on). So if we double theirs, it's 30ms for 300. Acceptable, but for 1000 we are back at 100ms :man_shrugging: 

----

Right now the query is cached and prepared. There might be some additional levels of caching we can do, but given the object is apart of every rule, I'm not sure how much we can do with a list of objects if we assume they are "random" workspaces and not lumped into groups with similar properties.

**Comment by Emyrk** [comment]
The most optimal solution would be something like this: https://blog.openpolicyagent.org/write-policy-in-opa-enforce-policy-in-sql-d9d24db93bf4

I am happy to dive into this more when it's worth the effort.

**Comment by kylecarbs** [comment]
Is that benchmark with the changes you made @Emyrk? Or is that what it was at before? I saw 85 taking 170ms.

**Comment by Emyrk** [comment]
> Is that benchmark with the changes you made @Emyrk? Or is that what it was at before? I saw 85 taking 170ms.

That is the benchmark with very little changes. But one thing I noticed was that the current cost grows linearly with the number of roles you have. This should be optimized to not do that... If I add more roles and benchmark on my i7-6770HQ CPU @ 2.60GHz, 85 would be around ~50ms.

**I also only ran the benchmark with 1 "category" of workspaces**. See https://github.com/coder/coder/pull/3121/files. I'll keep playing with it, just found something I can fix with the simple benchmark atm.

```
cpu: Intel(R) Core(TM) i7-6770HQ CPU @ 2.60GHz
BenchmarkRBACFilter
BenchmarkRBACFilter-8   	    1707	    615300 ns/op
```

I'd be curious to know what cpu and load to have gotten the 170ms. 

----

Regardless there is an optimization to be made to not scale with more roles added. At some point though, I'd rather put effort into a more long term solution.

**Comment by kylecarbs** [comment]
Makes sense. Right now this would be a pretty significant inhibitor to large adoption (even our small team has hit this as a mediocre problem).

What do you think we should do to handle it? Pagination maybe?

**Comment by Emyrk** [comment]
Give me the weekend to play with some rego. I would imagine too an admin would be a lot quicker to list than a user, just from the fact the rego aborts early at the admin "I can do everything perm".


Hunches:
- Find easy optimizations in the rego in the non-admin case
- Look into if dropping `resource_id` can provide an improvement, and it's probably a step towards the SQL anyway. The use case for it is no longer relevant.
- Put some effort into rewriting to be more SQL transformation friendly. It _doesn't seem that hard_ and worth a quick investigation.

**Comment by ketang** [comment]
I want to use RBAC all over the place, so I think it's worth making this very fast, even if that adds some (well-managed) complexity.

**Comment by Emyrk** [comment]
I propose the following speedups. We can implement each phase as we require the next scaling needs. They all grow off each other, so all work is reused. This takes advantage of [rego partial evaluations](https://blog.openpolicyagent.org/partial-evaluation-162750eaf422). I have already started to rewrite our policy to support this, it just needs some more testing and some polish. 

WIP branch: https://github.com/coder/coder/tree/stevenmasley/rbac_partial

# Phases

## Phase 0

A great speedup will be to drop `object_id` from the rbac system. It adds a lot of overhead and complexity in the rego expression that makes everything below more challenging. It also adds items to the slices/arrays we have to iterate over.

## Phase 1: Optimize query for a given item set -- O(n)

The current `Authorize` is run for each object in the given set. `Authorize` has to iterate over each role and the permissions in each role a user has. The rego expression can be optimized if we know some properties of the set before, such as the object type and action.

 With rego's partial queries, we change the question from "Can the actor read the workspace X" to "What workspaces can the actor read". The difference in these questions is the second relies on only properties of the workspace, not on the user. An example partial returns two simplified queries (using [partial.rego](https://github.com/coder/coder/blob/4f6f8500e1eff2480e3f353ae79b8b2a7d2bc992/coderd/rbac/partial.rego)):

```
$ opa eval --partial --format=pretty 'data.authz.allow = true' -d partial.rego --unknowns input.object.owner --unknowns input.object.org_owner -i
 input.json
+---------+------------------------------------------------------------------------------------------+
| Query 1 | "eee4a9bb-86e9-4f86-a6a9-d5fa168901a0" = input.object.org_owner                          |
+---------+------------------------------------------------------------------------------------------+
| Query 2 | not "fake" = input.object.org_owner                                                      |
|         | input.object.org_owner in {"eee4a9bb-86e9-4f86-a6a9-d5fa168901a0", "fake", "org-member"} |
|         | "me" = input.object.owner                                                                |
+---------+------------------------------------------------------------------------------------------+

```

These queries are now run on each object in the set. The speedup occurs from a simplier rego policy (in this case just queries) and a much smaller input, as we only need to input the object (all inputs as json marshalled).

**Note: These benchmarks are a bit rough. The actual speeds posted in this issue are slower, so this benchmark is faster than what we see in production**
```
BenchmarkRBACFilter-8               3582            344428 ns/op
BenchmarkRBACFilterPartials-8           8529            146177 ns/op
```

## Phase 2: O(1)

We can build off step 1, and instead of run the partial results on each item, we can convert it into a SQL `WHERE` clause. The above 2 queries are `OR`'d. This solution requires walking the partial's AST and we'd have to make sure all partial results can be converted. 

```SQL
SELECT * FROM workspaces WHERE
	organization_id = 'eee4a9bb-86e9-4f86-a6a9-d5fa168901a0' 
	OR
	(
		organization_id != 'fake' AND 
		organization_id = ANY('ee4a9bb-86e9-4f86-a6a9-d5fa168901a0', 'fake', 'org-member') AND
		owner_id = 'me' 
	)
```

----

We can easily start with solution 1 and grow to 2. Phase 2 also supports the pagination.

**Comment by kylecarbs** [comment]
I like us going for phase 0 to start and doing a benchmark. Seems simple enough to me!

**Comment by ketang** [comment]
Is there some easy way to plug in a cache with like a 5 second TTL?

**Comment by Emyrk** [comment]
@ketang we could cache using `Roles` as the key to reuse across similar users. A short lived cache still pays the latency cost very frequently making the workspaces page feel slow. I think regardless of a cache we should do up to Phase 1. It's not much more work and speeds up our underlying policy.

**Comment by Emyrk** [comment]
@kylecarbs can we close this issue for now? There is a Phase 2 option to further optimize, but I think we are good for the time being?

If we need pagination and to support thousands of objects, we can open a new issue.

**Comment by kylecarbs** [comment]
Yup, let's close it out!
