### ISSUE TITLE
feat: Add dotfiles repo URL at the user account to be re-used across templates (for v1 parity)

### ISSUE THREAD

**Issue by mark-theshark** [coder/coder#3114]
This is the v1 comparable feature to copy.

As a developer, I want all of my workspaces to look the same with my dotfiles repo cloned and installed.

Presently in Coder OSS, I have to manually copy/paste my URL into each workspace creation step if the template prompts for it.

I would like this to behave like Coder v1 where I add the repo once at the user account level, and if a template is going to clone it, it grabs the URL from the Coder database.

<img width="559" alt="image" src="https://user-images.githubusercontent.com/2022166/180443115-bfbbd666-726b-46c1-9485-5d32242b6d20.png">

**Comment by ammario** [comment]
This is the most important user story that is resolved by https://github.com/coder/coder/issues/2387. We should not implement it in the v1 way because:

- We will want user-scoped values for more than dotfiles, meaning a first-class field would duplicate functionality
- We have [no standard approach](https://coder.com/docs/coder-oss/latest/dotfiles) to dotfiles like v1 does.
