### ISSUE TITLE
SSH config should not suggest or use `.dev` TLDs

### ISSUE THREAD

**Issue by kotx** [coder/coder#3143]
The `.dev` TLD is not reserved, and having `coder config-ssh` override `coder.workspace-name.dev` can conflict with real domains.
For example if my coder instance was hosted on `coder.aaaa.dev`, and I had a workspace called `aaaa`, I can no longer SSH to the server that hosts the Coder instance.
The frontend and `coder ssh-config` should therefore not use `.dev` after the workspace name.

**Comment by ammario** [comment]
The suffix is the name of the agent. All of our example templates use `dev` as the agent name, for example:

https://github.com/coder/coder/blob/5e32468a73a84cc222de9334a10e8209fc4c8462/examples/templates/docker/main.tf#L68-L88

Perhaps dev isn't the best name for agents, but since conflicts would be rare and the workaround is a small edit to the template, I think we can close this issue.

**Comment by kotx** [comment]
Maybe we can rename the agent in the default templates instead?
