### ISSUE TITLE
Design license banner

### ISSUE THREAD

**Issue by presleyp** [coder/coder#3211]
### Problem
When an enterprise customer's license is in a grace period or exceeds their active user limit, there needs to be a banner on all pages alerting them to the non-compliance. It must be able to display an arbitrary number of warning strings, in case the customer is out of compliance on multiple fronts. It must not be dismissible, but it must not interfere with any functionality.

### Definition of Done
A Figma mock-up showing the color, size, and placement of the banner.

### Issues to keep in mind
What will happen if the banner gets longer due to additional warnings? 
How much can we have the banner on the outside of all other content for ease of adding it to the component tree?

### Prior art
To see the v1 license banner, set the System Banner here https://master.cdr.dev/admin?tab=appearance. The color is settable by the admin (not a requirement in v2 as far as I know) so the color below is not a meaningful design choice. Note that the banner stays at the top of the viewport as you scroll:

<img width="1336" alt="Screen Shot 2022-07-26 at 10 55 29 AM" src="https://user-images.githubusercontent.com/1290996/181039830-2f515aa2-af10-4685-9b07-3c7e2b874713.png">
<img width="1319" alt="Screen Shot 2022-07-26 at 10 55 39 AM" src="https://user-images.githubusercontent.com/1290996/181039832-aa2def9b-522c-4fd7-987b-6b4cfac5e77d.png">

**Comment by BrunoQuaresma** [comment]
My first suggestions
![Multiple issues open](https://user-images.githubusercontent.com/3165839/184700252-228ded17-82e6-4249-b47e-4b16e806292d.png)
![Multiple issues close](https://user-images.githubusercontent.com/3165839/184700263-da8bfb5a-1903-45a9-8e7c-c1f54670fd7a.png)
![Single issue](https://user-images.githubusercontent.com/3165839/184700268-1bad3664-d192-43d1-90f9-a7fa4a3b28c5.png)

I used "Magenta" because it is a "red-ish" color but not so red, so the user will not confuse this message as an error. We also could use a more "blue-ish" color but I also would like to get the user's attention and say "This is critical". 

Thoughts?

**Comment by BrunoQuaresma** [comment]
Figma link: https://www.figma.com/file/YIGBkXUcnRGz2ZKNmLaJQf/Coder-v2-Design?node-id=674%3A587

**Comment by BrunoQuaresma** [comment]
I made a version which is softer, and I liked it more:
![Multiple issues open](https://user-images.githubusercontent.com/3165839/184716029-ab8bfd15-1d17-414d-95e1-7164ac64b8a3.png)
![Multiple issues close](https://user-images.githubusercontent.com/3165839/184716038-8503e05c-9791-41c4-b29f-ae269dedaaa4.png)
![Single issue](https://user-images.githubusercontent.com/3165839/184716043-aca7e336-30be-48e7-8c64-463d8f39316a.png)

**Comment by jsjoeio** [comment]
I like the color! I prefer the second one since it's not as tall.

**Comment by jsjoeio** [comment]
I feel like we should have a standard warning/error/info color and use that consistently throughout app. Then we could use the info or warning with the banner

**Comment by Kira-Pilot** [comment]
I really like the magenta. I like it a lot more than our red error state and I wish we could use it for errors or warnings as well. 
If we didn't want the licensing banner to be considered an error, we could use the grey and then add an icon or something in the magenta. That would be attention-grabbing but less severe looking.

It might be nice to be able to dismiss this banner with a corner icon (an 'X') instead of via a text link.

Looking good!

**Comment by BrunoQuaresma** [comment]
Great feedback! @Kira-Pilot this banner specifically should not be dismissible.

>  It must not be dismissible, but it must not interfere with any functionality.

**Comment by presleyp** [comment]
We're getting input that this should be coded as a warning and be an orangey color. Aside from that I think the design is great!

**Comment by ammario** [comment]
I guess magenta is too pretty for this purpose. Hopefully, we can find a use for it later.
