### ISSUE TITLE
Send an email to the user when one of their workspace is going to be shutdown/deleted

### ISSUE THREAD

**Issue by matifali** [coder/coder#3380]
Please add the ability to email the users when one of their workspaces is nearing a scheduled shutdown.
Currently, the user does not have any notification if their workspace is shutting down. Please add some kind of notification to notify the users.

Also, the shutdown should be postponed automatically if the code is running.

**Comment by mark-theshark** [comment]
I like these ideas. 👀

**Comment by matifali** [comment]
So any slack or email notifications?

**Comment by matifali** [comment]
> @matifali, how would you expect to configure email sending? Would you want to provide Coder with configurations for using an SMTP server (smtp.host.com/user/pass/port)
This is simpler and can be used.

**Comment by dcarrion87** [comment]
Ooo this would be nice for slack!

**Comment by matifali** [comment]
bump

**Comment by matifali** [comment]
Hi @Kira-Pilot if you are working on this, my suggestion is to let us specify an SMTP server address and login credentials and then Coder s NDS notifications by using that. 

Something like
```shell
CODER_SMTP_SERVER_ADDRESS=smtp.mycompany.com
CODER_SMTP_SERVER_PORT=587
CODER_SMTP_SERVER_USERNAME=user@mycompany.com
CODER_SMTP_SERVER_PASSWORD=secret42
```

Something like https://pkg.go.dev/net/smtp can be used

**Comment by Kira-Pilot** [comment]
@matifali I like that idea. For this first pass, we are going to [add VS Code notifications](https://github.com/coder/coder/issues/7360) and nothing more. We want to give a notifications feature more thought instead of jamming it into the Workspace Actions RFC work, which I've linked above. 
I'm going to take my name off this ticket because I don't think I'm fully meeting your feature request here; however, this is definitely something we want to do down the line!

**Comment by bpmct** [comment]
Going to close this one for now. We are implementing "quiet hours" which ensures a workspace will only shut down in the following cases:

- User is inactive
- Workspace is reaching its max window (e.g. has policy to restart every week)

Down the road, I'd love to add email support

**Comment by stirby** [comment]
Recently requested by an enterprise customer.
