### ISSUE TITLE
Piping output of `coder templates pull` to a file renders as a binary/unsupported text encoding

### ISSUE THREAD

**Issue by ericpaulsen** [coder/coder#3398]
When running `coder templates pull <template-name> >> file.txt`, it is unable to be viewed, since it is created as a binary/unsupported text encoding. Tested & reproduced with 3 templates using `0.8.2`.

Upon further investigation, I noticed the first line of the output shows an odd encoding, related to the template README file:

```
> coder templates pull gcp-ubuntu-docker

README.md0000644000076500000240000000214514273763201012451 0ustar00ericstaff00000000000000---
name: Develop in Linux on Google Cloud
description: Get started with Linux development on Google Cloud.
tags: [cloud, google]
```

**Comment by ericpaulsen** [comment]
I've learned that `coder templates pull` outputs as a tar file by default, so `coder templates pull <name> | tar -xvf -` would address this issue. We should probably clarify this in our documentation.

**Comment by mafredri** [comment]
I think it would make sense to extract the archive into destination when specified (second argument). This would align more with what `coder templates push` does (reads a folder).

It might also be best to not output the tar into the terminal when running `coder templates pull <name>` since it contains binary data and could mess up the users terminal.

Example from `curl` when trying to do this:

```
Warning: Binary output can mess up your terminal. Use "--output -" to tell
Warning: curl to output it to your terminal anyway, or consider "--output
Warning: <FILE>" to save to a file.
```

**Comment by ericpaulsen** [comment]
@mafredri thanks for the added context. so for example, a potential solution would be to support `coder templates pull <name> --output <FILE>`, correct?

**Comment by sreya** [comment]
You should be able to specify an output path like so

```bash
templates pull my-template template.tar
``` 

or alternatively

```
templates pull my-template > template.tar
```

See help

```
coder@aman ~ coder templates pull --help
Download the latest version of a template to a path.

Usage:
  coder templates pull <name> [destination] [flags]
```

**Comment by mafredri** [comment]
@ericpaulsen Yeah, that'd be one option (or another mentioned at the bottom of this comment).

@sreya Yeah, that's possible today. But the documentation (`--help`) does not explain it's a `tar` archive. Likewise, when simply running `templates pull my-template` it outputs the raw binary data which _looks like text_. That adds to the confusion about what this command really does. (Typically this might not mess up a terminal, but if the template dir happened to contain any binary files, it likely would.)

Since the current behavior is confusing and potentially bad for terminals, my thinking is that `templates pull my-template [destination]` _should_ extract the `tar` into destination folder so that `push` and `pull` behave similarly. Similarly we shouldn't output binary data (by default) when running `templates pull my-template` in a terminal unless piped, e.g. `templates pull my-template | tar xvf -`.

But that's just one option, `pull` behavior doesn't have to change as long as we update the `--help` to mention that a tar file will be downloaded (and prevent binary output to stdout). Then `templates pull my-template` won't output anything, but `templates pull my-template > template.tar` or `templates pull my-template | tar xvf -` will (by detecting tty status). And we can optionally add an `--output` flag to be more explicit (or force output to stdout).

**Comment by sreya** [comment]
@mafredri this issue duplicates #2651 are you cool with the solution mentioned [here](https://github.com/coder/coder/issues/2651#issuecomment-1210686764)?

**Comment by mafredri** [comment]
@sreya ah, yeah it sounds like #2651 would fix this issue. I think the proposal sounds reasonable.

**Comment by sreya** [comment]
@ericpaulsen I'm going to close this in favor of #2651, feel free to reopen it if you think it's appropriate.
