### ISSUE TITLE
coder login error..help

### ISSUE THREAD

**Issue by BSTluo** [coder/coder#3503]
![image](https://user-images.githubusercontent.com/36332288/184519491-90ddb6f4-9bd8-4f41-8518-de26d46414f3.png)
![image](https://user-images.githubusercontent.com/36332288/184519499-a70b661a-3d7a-43fc-9a38-23da3cde108f.png)
Using the command `coder login url`，It produces errors   ↑

**Comment by kylecarbs** [comment]
Are you certain the endpoint isn't pointing at a different web server? Seems like the API routes are returning some HTTP instead of JSON.

Can you try curl'ing it?

**Comment by BSTluo** [comment]
I'll have a try

**Comment by kylecarbs** [comment]
If you have any troubles, give us a shout!

**Comment by BSTluo** [comment]
thanks

**Comment by skerit** [comment]
I had the same issue, for anyone wondering: it was because the *public/access url* couldn't be opened by the server it was running on. Changing it to the internal url (in my case `127.0.0.1:7991`) fixed that.

What I'm more surprised by is that the `coder login` command tries to open a web browser. But I'm running this on a headless server? Is `coder` both a server and a client? Funny enough that isn't totally clear at first glance.
