### ISSUE TITLE
React 18 cleanup: fix act warnings and cleanup promises in test files

### ISSUE THREAD

**Issue by Kira-Pilot** [coder/coder#3626]
Several jest `act` warnings appeared after we upgraded to React 18 in #3353. We should clean these up, although they don't effect the passing of the test suite.

In addition, we overrode lint in the following test files:
`site/src/pages/CreateWorkspacePage/CreateWorkspacePage.test.tsx`
`site/src/pages/UsersPage/UsersPage.test.tsx`
`site/src/pages/WorkspacePage/WorkspacePage.test.tsx`,
specifically `eslint-disable @typescript-eslint/no-floating-promises` 

We should remove these overrides once we fix some of the async issues with the tests.

## To reproduce
`cd site`
`yarn run test`

## Resources
Learn more about the act warnings [here](https://kentcdodds.com/blog/fix-the-not-wrapped-in-act-warning). Learn about their appearance in React 18 [here](https://github.com/testing-library/react-testing-library/issues/1051).

**Comment by BrunoQuaresma** [comment]
This comment here is extra helpful https://github.com/testing-library/react-testing-library/issues/1051#issuecomment-1212955270

**Comment by jsjoeio** [comment]
@presleyp you wrote up a helpful doc about debugging `act` warnings in Notion. Is it okay if we repost it here (the actual text, not the link)?

**Comment by jsjoeio** [comment]
P.S. I've started briefly fixing some of these things one at a time:
- https://github.com/coder/coder/pull/4091
- https://github.com/coder/coder/pull/4161

I'll continue to chip away at this.

**Comment by presleyp** [comment]
> @presleyp you wrote up a helpful doc about debugging `act` warnings in Notion. Is it okay if we repost it here (the actual text, not the link)?

Sure!

- If you need to repeat code across tests, prefer just repeating code, or putting the repeated code in a function, over putting it in `beforeEach`. `beforeEach` can lead to weird behavior and should only be used for setup that has a matching `afterEach` teardown. ([related](https://github.com/testing-library/user-event/issues/497))
- Prefer `findBy` to `getBy` in case some loading needs to happen. Side effects that the test doesn’t wait for are the cause of those horrible `act` warnings.
- Prefer `userEvent` to `fireEvent` unless it’s not working. `userEvent` is more lifelike, but may have some holes. Use it like this:
    
    ```jsx
    const user = userEvent.setup()
    await user.click(someButton)
    await user.type(someInputField, "some text")
    ```
    
- You probably don’t need to use `act`. `findBy` queries, `waitFor`, and `userEvent` use `act` under the hood.
- Always `await` things that wrap `act`:
    - `findBy`
    - `waitFor`
    - `waitForElementToBeRemoved`
    - `userEvent` calls
- This warning explains why: “Warning: You called act(async () => ...) without await. This could lead to unexpected testing behaviour, interleaving multiple act calls and mixing their scopes. You should - await act(async () => ...);”.
- Be on the lookout for this interleaving. Is your test failing on the basis of lines that are not part of that test? Is its failure being reported multiple times? Does it pass when run in isolation? These are signs that another test is leaking state. RTL does `cleanup` for us but this can still happen.
- [“If you're still experiencing the **`act`**warning, then the most likely reason is something is happening **after your test completes** for which you should be waiting.”](https://kentcdodds.com/blog/write-fewer-longer-tests). You may need to `findBy` an element or `waitFor` a condition that becomes true later on in the loading process, even if your test doesn’t care about it. This is why it can make sense to have long tests rather than one test per assertion.

I was thinking it might make sense for us to eventually have a util function for each page that awaits whatever the last-to-load thing is, so each test for that page could start by calling it.
