### ISSUE TITLE
bug: template settings

### ISSUE THREAD

**Issue by matifali** [coder/coder#3640]
[Screencast from 08-23-2022 02:37:39 PM.webm](https://user-images.githubusercontent.com/10648092/186152279-ba1e5055-64c5-4692-999f-ee47fa02e89a.webm)
There are multiple issues.

1. Does not allow saving if,

    - Description is longer than some characters. (Show a limit on the length of maximum characters) or show a message if the user exceeds that limit
    - if `MAX_TTL` time is 1 year = 31536000000 milliseconds.

2. Make `MAX_TTL` in hours

3. Allow setting `MAX_TTL` to `inf` or turning off the auto-shutdown for the template.

**Comment by johnstcn** [comment]
Workaround: set template max_ttl via CLI:
```
coder template edit mytemplate --max-ttl 8766h # 1 year in hours
```
CLI syntax is Go duration e.g. `3h2m1s`.

**Comment by matifali** [comment]
> Workaround for 2: set template max_ttl via CLI:
> 
> ```
> coder template edit mytemplate --max-ttl 8766h # 1 year in hours
> ```
> 
> CLI syntax is Go duration e.g. `3h2m1s`.

I am using this workaround for now.

**Comment by johnstcn** [comment]
* We should check the bounds of `max_ttl` in the FE -> cannot be greater than 604800 seconds (7 days)
* We should also check the bounds of `max_ttl` in the BE (ditto, 7 days)
  * 7 days is the maximum allowable TTL of a workspace because it's a weekly schedule
* Backend must not return a number greater than MAX_INT64
* We should also update the form to allow input in hours (more granular -> use the CLI)
