### ISSUE TITLE
Junk is being inserted into the web terminal

### ISSUE THREAD

**Issue by johnstcn** [coder/coder#3666]
# Problem

Right around the time of a Coderd restart, @Emyrk was connected to the web terminal, lost connection, reconnected, and got a bunch of junk inserted into their terminal:

![image](https://user-images.githubusercontent.com/4949514/186453536-7398206b-fdba-49d8-a88c-b93754369e0b.png)

![image](https://user-images.githubusercontent.com/4949514/186456628-92db5028-df5b-4665-8be9-21346c49cab9.png)

We poked around in the Web inspector and found that the frontend was sending the content. It seems like there's some kind of replay buffer that's re-sending some terminal escape codes, but whatever had been listening to them is now gone and has no way of acking.

# Solution

@deansheather thinks we could just block on the websocket until we're finished rendering.

**Comment by code-asher** [comment]
For whoever works on this the solution we decided on v1 is to use screen: https://github.com/coder/wsep/pull/25

**Comment by matifali** [comment]
Faced this today on https://github.com/coder/coder/commit/f72d8e95a42bee59764dfa2ae3428e7ee5bb9a48
dev.coder.com
![image](https://github.com/coder/coder/assets/10648092/e2bf7b73-dcf5-4b9a-8a49-53fba4bc196f)

**Comment by mafredri** [comment]
I made an asciinema recording with a minimal shell setup: https://asciinema.org/a/fwLHGVx1zbIRtpYaB0isQz2mw

Uses `/bin/sh` and no tmux config, yet the issue persist on reloading the page. There's no way we filled the reconnecting pty buffer at this point so this may be an `xterm.js` bug.

When we reload the page, we get the initial payload:

```
00000000: 2420 6173 6369 696e 656d 6120 7265 6320  $ asciinema rec 
00000001: 2d2d 6f76 6572 7772 6974 6520 7e2f 7465  --overwrite ~/te
00000002: 7374 2e63 6173 740d 0a1b 5b30 3b33 326d  st.cast...[0;32m
00000003: 6173 6369 696e 656d 613a 2072 6563 6f72  asciinema: recor
00000004: 6469 6e67 2061 7363 6969 6361 7374 2074  ding asciicast t
00000005: 6f20 2f68 6f6d 652f 636f 6465 722f 7465  o /home/coder/te
00000006: 7374 2e63 6173 741b 5b30 6d0d 0a1b 5b30  st.cast.[0m...[0
00000007: 3b33 326d 6173 6369 696e 656d 613a 2070  ;32masciinema: p
00000008: 7265 7373 203c 6374 726c 2d64 3e20 6f72  ress <ctrl-d> or
00000009: 2074 7970 6520 2265 7869 7422 2077 6865   type "exit" whe
0000000a: 6e20 796f 7527 7265 2064 6f6e 651b 5b30  n you're done.[0
0000000b: 6d0d 0a24 2074 6d75 780d 0a1b 5b3f 3130  m..$ tmux...[?10
0000000c: 3439 681b 5b32 323b 303b 3074 1b5b 3f31  49h.[22;0;0t.[?1
0000000d: 681b 3d1b 5b48 1b5b 324a 1b5b 3f31 326c  h.=.[H.[2J.[?12l
0000000e: 1b5b 3f32 3568 1b5b 3f31 3030 306c 1b5b  .[?25h.[?1000l.[
0000000f: 3f31 3030 326c 1b5b 3f31 3030 336c 1b5b  ?1002l.[?1003l.[
00000010: 3f31 3030 366c 1b5b 3f31 3030 356c 1b28  ?1006l.[?1005l.(
00000011: 421b 5b6d 1b5b 3f31 326c 1b5b 3f32 3568  B.[m.[?12l.[?25h
00000012: 1b5b 3f31 3030 366c 1b5b 3f31 3030 306c  .[?1006l.[?1000l
00000013: 1b5b 3f31 3030 326c 1b5b 3f31 3030 336c  .[?1002l.[?1003l
00000014: 1b5b 3f32 3030 346c 1b5b 313b 3148 1b5b  .[?2004l.[1;1H.[
00000015: 313b 3334 721b 5b3e 631b 5b3e 711b 5b31  1;34r.[>c.[>q.[1
00000016: 3b31 481b 5b3f 3235 6c1b 5b4b 0d0a 1b5b  ;1H.[?25l.[K...[
00000017: 4b0d 0a1b 5b4b 0d0a 1b5b 4b0d 0a1b 5b4b  K...[K...[K...[K
00000018: 0d0a 1b5b 4b0d 0a1b 5b4b 0d0a 1b5b 4b0d  ...[K...[K...[K.
00000019: 0a1b 5b4b 0d0a 1b5b 4b0d 0a1b 5b4b 0d0a  ..[K...[K...[K..
0000001a: 1b5b 4b0d 0a1b 5b4b 0d0a 1b5b 4b0d 0a1b  .[K...[K...[K...
0000001b: 5b4b 0d0a 1b5b 4b0d 0a1b 5b4b 0d0a 1b5b  [K...[K...[K...[
0000001c: 4b0d 0a1b 5b4b 0d0a 1b5b 4b0d 0a1b 5b4b  K...[K...[K...[K
0000001d: 0d0a 1b5b 4b0d 0a1b 5b4b 0d0a 1b5b 4b0d  ...[K...[K...[K.
0000001e: 0a1b 5b4b 0d0a 1b5b 4b0d 0a1b 5b4b 0d0a  ..[K...[K...[K..
0000001f: 1b5b 4b0d 0a1b 5b4b 0d0a 1b5b 4b0d 0a1b  .[K...[K...[K...
00000020: 5b4b 0d0a 1b5b 4b0d 0a1b 5b4b 1b5b 3330  [K...[K...[K.[30
00000021: 6d1b 5b34 326d 0d0a 5b30 5d20 303a 7368  m.[42m..[0] 0:sh
00000022: 2a20 2020 2020 2020 2020 2020 2020 2020  *               
00000023: 2020 2020 2020 2020 2020 2020 2020 2020                  
00000024: 2020 2020 2020 2020 2020 2020 2020 2020                  
00000025: 2020 2020 2020 2020 2020 2020 2020 2020                  
00000026: 2020 2020 2020 2020 2020 2020 2020 2020                  
00000027: 2020 2020 2020 2020 2020 2020 2020 2020                  
00000028: 2020 2020 2020 2020 2020 2020 2020 2020                  
00000029: 2020 2020 2020 2020 2020 2020 2020 2020                  
0000002a: 2020 2020 2020 2020 2020 2020 2020 2020                  
0000002b: 2020 2020 2020 2020 2020 2020 2020 2020                  
0000002c: 2020 2020 2020 2020 2020 2020 2022 7722               "w"
0000002d: 2031 353a 3434 2032 342d 4d61 792d 3233   15:44 24-May-23
0000002e: 1b28 421b 5b6d 1b5b 3f31 326c 1b5b 3f32  .(B.[m.[?12l.[?2
0000002f: 3568 1b5b 313b 3148 1b28 421b 5b6d 1b5b  5h.[1;1H.(B.[m.[
00000030: 3f31 326c 1b5b 3f32 3568 1b5b 3f31 3030  ?12l.[?25h.[?100
00000031: 366c 1b5b 3f31 3030 306c 1b5b 3f31 3030  6l.[?1000l.[?100
00000032: 326c 1b5b 3f31 3030 336c 1b5b 3f32 3030  2l.[?1003l.[?200
00000033: 346c 1b5b 313b 3148 1b5b 313b 3334 721b  4l.[1;1H.[1;34r.
00000034: 5b3f 3235 6c1b 5b31 3b31 481b 5b4b 0d0a  [?25l.[1;1H.[K..
00000035: 1b5b 4b0d 0a1b 5b4b 0d0a 1b5b 4b0d 0a1b  .[K...[K...[K...
00000036: 5b4b 0d0a 1b5b 4b0d 0a1b 5b4b 0d0a 1b5b  [K...[K...[K...[
00000037: 4b0d 0a1b 5b4b 0d0a 1b5b 4b0d 0a1b 5b4b  K...[K...[K...[K
00000038: 0d0a 1b5b 4b0d 0a1b 5b4b 0d0a 1b5b 4b0d  ...[K...[K...[K.
00000039: 0a1b 5b4b 0d0a 1b5b 4b0d 0a1b 5b4b 0d0a  ..[K...[K...[K..
0000003a: 1b5b 4b0d 0a1b 5b4b 0d0a 1b5b 4b0d 0a1b  .[K...[K...[K...
0000003b: 5b4b 0d0a 1b5b 4b0d 0a1b 5b4b 0d0a 1b5b  [K...[K...[K...[
0000003c: 4b0d 0a1b 5b4b 0d0a 1b5b 4b0d 0a1b 5b4b  K...[K...[K...[K
0000003d: 0d0a 1b5b 4b0d 0a1b 5b4b 0d0a 1b5b 4b0d  ...[K...[K...[K.
0000003e: 0a1b 5b4b 0d0a 1b5b 4b0d 0a1b 5b4b 1b5b  ..[K...[K...[K.[
0000003f: 3330 6d1b 5b34 326d 0d0a 5b30 5d20 303a  30m.[42m..[0] 0:
00000040: 7368 2a20 2020 2020 2020 2020 2020 2020  sh*             
00000041: 2020 2020 2020 2020 2020 2020 2020 2020                  
00000042: 2020 2020 2020 2020 2020 2020 2020 2020                  
00000043: 2020 2020 2020 2020 2020 2020 2020 2020                  
00000044: 2020 2020 2020 2020 2020 2020 2020 2020                  
00000045: 2020 2020 2020 2020 2020 2020 2020 2020                  
00000046: 2020 2020 2020 2020 2020 2020 2020 2020                  
00000047: 2020 2020 2020 2020 2020 2020 2020 2020                  
00000048: 2020 2020 2020 2020 2020 2020 2020 2020                  
00000049: 2020 2020 2020 2020 2020 2020 2020 2020                  
0000004a: 2020 2020 2020 2020 2020 2020 2020 2022                 "
0000004b: 7722 2031 353a 3434 2032 342d 4d61 792d  w" 15:44 24-May-
0000004c: 3233 1b28 421b 5b6d 1b5b 3f31 326c 1b5b  23.(B.[m.[?12l.[
0000004d: 3f32 3568 1b5b 313b 3148 2420 1b5b 3f37  ?25h.[1;1H$ .[?7
0000004e: 3732 3768 0d0a 1b5b 313b 3334 721b 2842  727h...[1;34r.(B
0000004f: 1b5b 6d1b 5b3f 316c 1b3e 1b5b 481b 5b32  .[m.[?1l.>.[H.[2
00000050: 4a1b 5b3f 3132 6c1b 5b3f 3235 681b 5b3f  J.[?12l.[?25h.[?
00000051: 3130 3030 6c1b 5b3f 3130 3032 6c1b 5b3f  1000l.[?1002l.[?
00000052: 3130 3033 6c1b 5b3f 3130 3036 6c1b 5b3f  1003l.[?1006l.[?
00000053: 3130 3035 6c1b 5b3f 3737 3237 6c1b 5b3f  1005l.[?7727l.[?
00000054: 3130 3034 6c1b 5b3f 3130 3439 6c1b 5b32  1004l.[?1049l.[2
00000055: 333b 303b 3074 5b65 7869 7465 645d 0d0a  3;0;0t[exited]..
00000056: 2420 5e5b 5b3e 303b 3237 363b 3063 5e43  $ ^[[>0;276;0c^C
00000057: 0d0a 2420 6578 6974 0d0a 1b5b 303b 3332  ..$ exit...[0;32
00000058: 6d61 7363 6969 6e65 6d61 3a20 7265 636f  masciinema: reco
00000059: 7264 696e 6720 6669 6e69 7368 6564 1b5b  rding finished.[
0000005a: 306d 0d0a 1b5b 303b 3332 6d61 7363 6969  0m...[0;32mascii
0000005b: 6e65 6d61 3a20 6173 6369 6963 6173 7420  nema: asciicast 
0000005c: 7361 7665 6420 746f 202f 686f 6d65 2f63  saved to /home/c
0000005d: 6f64 6572 2f74 6573 742e 6361 7374 1b5b  oder/test.cast.[
0000005e: 306d 0d0a 2420 5e5b 5b3e 303b 3237 363b  0m..$ ^[[>0;276;
0000005f: 3063                                     0c
```

But after we receive it, we send out the following response:

```
00000000: 7b22 6461 7461 223a 225c 7530 3031 625b  {"data":"\u001b[
00000001: 3e30 3b32 3736 3b30 6322 7d              >0;276;0c"}
```

So something in the output triggered a response.

I do believe control characters at the edge of the buffer constitutes a problem as well, so we may be dealing with two separate but kind of related issues here.

**Comment by code-asher** [comment]
Yup this matches with my findings when we fixed this on v1, the client is responding to control codes in the buffer asking for its capabilities, cursors position, things like that.  But those responses are no longer expected for one reason or another (maybe the application that asked for them has exited for example) and get interpreted as regular input.

I think the only reliable solutions are to actually render the terminal, more or less using a full terminal emulator on the backend, or use something like `screen`.

https://github.com/coder/v1/issues/12909#issuecomment-1226202016

**Comment by mafredri** [comment]
Thanks for sharing that @code-asher, makes perfect sense! Your reply gives me the idea that we could just strip out the problematic escape sequences. There are not many that I know of that would be problematic.

Furthermore, I believe we can eliminate a slew of problems by making the ring buffer newline aware and evicting whole lines at a time (or let the reader do it, doesn’t matter).

**Comment by code-asher** [comment]
That was actually the approach I first took but I was not sure it would work; take for example a control character saying to "move down one", this will put the cursor in a different location than the first go around if there was a "move to the center of the screen" control code that has since been evicted from the buffer.

To recreate the current cursor state (as just one example) from a history of movement commands you would need the full history which means a buffer of unbounded size.

Otherwise I think it would work but I also found I was reading through the spec to make sure I got all the possible codes that could cause an issue and I suddenly realized I was starting down a rabbit hole of implementing a full-blown terminal emulator because I was not confident it could be reliably done by just a regex replacement or something like that.  :laughing:

**Comment by mafredri** [comment]
I do see where your coming from @code-asher and those are valid points. It would be quite elegant to render it server side, I agree. One problem with going the `screen` or `tmux`, though, is that in v2 we can't rely on either of these programs being present. We also currently have no facility for shipping such binaries to a workspace (not to mention in a platform independent way). So far we've managed to implement all features in Go which lets us have the single agent binary.

My next question would be, how do we perform terminal updates in a performant manner with SSR? Do we perform some sort of diffing for the currently rendered screen and attempt to deliver intelligent line updates or do we serialize the entire screen all the time?

I'm not entirely convinced that the loss of control characters past the circular buffer will be a huge problem for v2 considering the buffer is currently 64 KB in size (which is pretty big). That's because, if we discard based on newlines, we remove many problematic cases of control characters and (hopefully) only a little bit at the start of the scroll-back buffer may be corrupted (if at all).

See the following example:
<img width="397" alt="image" src="https://github.com/coder/coder/assets/147409/cd0e99c7-77c3-4bd6-876a-62718999b928">

The newline resets the cursor position and is thus a pretty good indicator of "we're safe now".

Some further mitigations we could do:

1. Discard the first terminal `$ROWS` of rendered output, if we do this client side we lose a bit of scroll-back but ensure that the output is much more likely to be clean
2. Set a maximum rows/cols for the web terminal, this is to give us an estimate that a single page of output never exceeds N% of the ring buffer

We could optionally also enable infinite scroll-back by storing it on the filesystem, but I guess this should be a user or terraform setting.

**Comment by code-asher** [comment]
In v1 we technically have no guarantee either, basically if you install `screen` in your image you get reconnections and if you do not then it degrades to no reconnection.

Yeah my concern with lost control characters is mostly just academic at this point; I have not actually experimented with reproducing.  I think maybe you could see it if you launch an editor like Vim and leave it running for a while, maybe?  I think it will not be such a big problem with the regular command prompt, if at all.

**Comment by code-asher** [comment]
Another thing I tried was not buffering anything that printed in the altscreen (which would cover Vim, Emacs, etc) and then trying to send a SIGWINCH to every child process on reconnect to force it to redraw but unfortunately that did not work as some applications would not redraw since it sees the height/width was the same.  I also tried resizing smaller once and then back up to the expected size but that also did not work because some applications seem to debounce the resize.  I am also not sure all apps handle SIGWINCH in the first place.

**Comment by code-asher** [comment]
I can reproduce some weirdness if I launch Emacs, split the window, open a file in one and eshell in the other, then run `printf 'A%.0s' {1..128000}` in eshell.

Actually any application that enters the altscreen starts by sending `1049h` right?  That could be pretty easily lost if you use the editor for a bit and then on reload xterm would never enter the altscreen?  Ohhhhhh that probably explains why sometimes scrolling stops working!  It must be scrolling xterm rather than sending to the app.

**Comment by matifali** [comment]
If we are talking about terminal then as a sperate issue. Press any key to reconnect actually doesn't work on terminal. It does reconnect on pressing Tab, Ctrl etc.

**Comment by mafredri** [comment]
> If we are talking about terminal then as a sperate issue. Press any key to reconnect actually doesn't work on terminal. It does reconnect on pressing Tab, Ctrl etc.

@matifali https://github.com/coder/coder/issues/6732

@code-asher You're likely on to something there. I'm unable to reproduce any altscreen issues with vim or tmux, but that's most likely due those applications re-rendering on screen resize (which happens on reload).

Exploring `vt10x` seems like a solid option, although I am a bit nervous about embedding it in the agent process. The more bloat we add to the agent, the more likely it will become a point of failure (unforeseen panics, increased memory usage resulting in OOM killing, etc) which would cripple the entire workspace. I'm not too worried about it in the immediate future, but something we may have to give some thought to down the line.

If we do go down the SSR path, it'd be nice to see a plan for protocol updates/bandwidth utilization.

Another option would be for us to have special handling of altscreen (separate buffer?), but obviously the more exceptions we add, the closer we get to implementing a terminal emulator ourselves. 😄

**Comment by code-asher** [comment]
I recorded a reproduction of the scroll issue with vim if you are curious what it looks like.  Here I scroll a bit to show the cursor moving up/down, run a command to generate some output, and finally cut/paste it a bunch to make sure I fill up the buffer.  On reload you see some flashing from old buffer contents being rendered and then finally scrolling is permanently broken (well at least until vim is restarted).

https://github.com/coder/coder/assets/45609798/aeb12b45-82fd-4d2b-b2f8-c2d8f613eb74

I bet if we dig into the codes there are other reproductions that can occur due to evictions especially with modes of which there appear to be many.
 
> the more exceptions we add, the closer we get to implementing a terminal emulator ourselves.

Hahaha that was my thinking exactly as I was going down the rabbit hole.  Every mode we check and every code we strip out gets us a little further.

I think `screen` is still a good option although it means users have to make sure it exists in their image if they want reconnectable terminals.  We could surface this information to the user, maybe even in the terminal itself?  For example we could print a message saying "install screen if you want to be able to reconnect" or something.

> If we do go down the SSR path, it'd be nice to see a plan for protocol updates/bandwidth utilization.

I am not sure how `screen` handles screen updates although I would (perhaps naively) assume they are optimal since it was probably used back in the day when bandwidth was an even bigger deal than it is today.

With `vt10x` the only way I can think of to make that work with xterm.js is to tee the input into both the tty and `vt10x` and then on reconnect we ask `vt10x` for the scrollback and send it all to the client.  We would want to limit the scrollback size which I think we would not need to do with screen.  On the flip side scrolling with screen would be slower since it would need to talk to the server to do that.

It is a bit weird since both `vt10x` and `xterm.js` are doing the same/similar emulating and they are only tangentially connected; hopefully they end up rendering the same way.  Maybe there is something we could replace `xterm.js` with and hook it directly into `vt10x` somehow.

**Comment by matifali** [comment]
#7765 may be related here.
