### ISSUE TITLE
Add an experimental mode that we can flag features on

### ISSUE THREAD

**Issue by kylecarbs** [coder/coder#3780]
Features aren't just code, they are an experience. During code review, it's unreasonable to expect reviewers to provide a guarantee that the code has no bugs or is of sufficient quality. It's also unreasonable for the author to have this level of quality since expectations are different depending on the user.

We can add an experimental mode to Coder that enables us to try the new functionality, continue to make releases, and still make it available to the public.

This can be a command-line flag: `coder server --experimental`, and an env var: `CODER_EXPERIMENTAL`. This can be included in the `buildinfo` response and should be used in the site and API.

A solid example for where this could add value is the template emoji feature. There were a few bugs that appeared after we tested it more thoroughly internally, but we would not want to slow down development. This could have been flagged under experimental mode for a few days, tested internally, then exposed to the public. 

The onus is on the feature creator to move functionality out of experimental mode.

**Comment by bpmct** [comment]
Could we add this to telemetry too? Would be interesting to know what % of deployments use this

**Comment by ammario** [comment]
Could we use `CODER_EXPERIMENTAL` as a safer way of creating internal debug flags (such as shortening refresh intervals in #3735)?

**Comment by bpmct** [comment]
@f0ssel and I just had a quick chat about this! Some things we discussed:

- We'll display this in the footer so it's easy to see, at a glance, if the experimental mode is on
  - If off, the footer should remain the same (e.g. don't say "experimental mode is off")
- We can use comments or some other indicator in the codebase to annotate the date the experimental flag is added. this will make it easy for me to generate reports that show what features are currently under the experimental mode. In most cases, a feature is not under "experimental" for more than 2 releases (that means we have not been actively testing it).
- Some configuration flags may depend on `CODER_EXPERIMENTAL` to be on so we will warn for that in `coder server --help`. Others will be on by default as they require no additional configuration.
- CODER_EXPERIMENTAL is only used to iron out bugs and minor UX issues, not to validate the usefulness/architecture of a feature.

**Comment by bpmct** [comment]
It's worth noting that this proposed behavior probably wouldn't be that useful for users since it could introduce bugs from other experimental features that they're not interested in. But, I think that is OK.

@deansheather mentioned we could do this per-feature `CODER_EXPERIMENTAL_ENABLE=healthchecks,rbac` or `CODER_EXPERIMENTAL_ENABLE=*` (all) but there were some concerns around drift (e.g. "what options are no experimental"), naming conventions (e.g. "what do I call this minor feature"), and major features might end up using an entirely separate flag (e.g. `CODER_TAILSCALE`) making it difficult to determine experimental features/deployment state at a glance. I'm still open to this behavior but think it's OK for the first iteration to be `true/false` if a feature-by-feature approach introduces too much complexity. This will help us internally with QA + any risky community members are still welcome to turn it on if they want the bleeding edge!

Additionally, the goal is that features only stay experimental for 1-2 weeks so the "global" approach may encourage us to test/document features so that they can be used with confidence!

**Comment by f0ssel** [comment]
This is completed with https://github.com/coder/coder/pull/4364
