### ISSUE TITLE
Agent Stuck On Connecting Status

### ISSUE THREAD

**Issue by hcancelik** [coder/coder#3862]
Agent seems to stuck at "Connecting" status for Digital Ocean droplet. 

I'm using the default template.

### Version
Coder v0.8.11+cde036c Thu Sep  1 20:10:53 UTC 2022
https://github.com/coder/coder/commit/cde036c1ab590d58ac4cd8b26235351b9c74d8f7

Is there anything I can help to troubleshoot this?

Please let me know if there is any additional information needed.

<img width="1653" alt="Screen Shot 2022-09-04 at 15 48 55" src="https://user-images.githubusercontent.com/5788410/188314290-ca65b5fc-97cb-420b-8c7c-4ed9c534d720.png">

**Comment by sharkymark** [comment]
@hcancelik A common cause for this state is that your workspace cannot communicate with the coder server because the CODER_ACCESS_URL is incorrectly set.

It needs to be a public DNS entry or IP address that the workspace in DO can reach.

Another cause can be you configured TLS but the access url still has http and not changed to https

Feel free to also continue this on Discord https://discord.com/invite/coder

**Comment by hcancelik** [comment]
> @hcancelik A common cause for this state is that your workspace cannot communicate with the coder server because the CODER_ACCESS_URL is incorrectly set.
> 
> It needs to be a public DNS entry or IP address that the workspace in DO can reach.
> 
> Another cause can be you configured TLS but the access url still has http and not changed to https
> 
> Feel free to also continue this on Discord https://discord.com/invite/coder

Ahh that was the issue. Thanks for the quick response.
