### ISSUE TITLE
tech debt: https://github.com/coder/coder/search?q=coderv2

### ISSUE THREAD

**Issue by ghuntley** [coder/coder#4074]
Whilst reading https://coder.com/docs/coder-oss/latest/install/uninstall the thought came to me that Coder is exposing internal codenames to end-users.

<img width="901" alt="CleanShot 2022-09-15 at 21 39 29@2x" src="https://user-images.githubusercontent.com/127353/190394363-ec2a7103-f325-40da-bcfa-faeed7774d62.png">

<img width="751" alt="CleanShot 2022-09-15 at 21 41 45@2x" src="https://user-images.githubusercontent.com/127353/190394762-2965ab3e-9cac-4928-a780-c9e71a989f33.png">

<img width="770" alt="CleanShot 2022-09-15 at 21 42 07@2x" src="https://user-images.githubusercontent.com/127353/190394840-82190c0e-cbdf-497c-9f25-17c93939b780.png">

Thoughts:
- Do we need to have `coderv2` references? Can we stop a propagating this pattern to end users? Earlier we stop propagating this the better.
- Can we have just `coder` ie `~/.config/coderv2` -> `~/.config/coder`

See https://github.com/coder/coder/search?q=coderv2

**Comment by sharkymark** [comment]
I see the point, but I think we had to have a way to differentiate from v1 installs on a machine, which is called coder already.

**Comment by bpmct** [comment]
Thanks for reporting and I'm glad we're talking about it earlier rather than later.

I'm not concerned about this, however, and don't think it is something we consider at this time. I don't think there is any long-term damage in using this default for config paths on local machines. I imagine we can address this when we release a 3.0 (likely in a few years) by supporting both paths.
