### ISSUE TITLE
Error in examples/templates/docker/README.md

### ISSUE THREAD

**Issue by ghuntley** [coder/coder#4105]
Looks like a merge conflict got merged.

<img width="968" alt="CleanShot 2022-09-19 at 11 41 29@2x" src="https://user-images.githubusercontent.com/127353/190937883-f83d4644-ba0e-402c-9be8-c0c61743a6b1.png">

Line that needs fixing https://github.com/coder/coder/blob/main/examples/templates/docker/README.md?plain=1#L62

**Comment by bpmct** [comment]
Good catch! This is intentional, but should display as a `diff` instead of `hcl`. Here's an example from the [docker-image-builds](https://github.com/coder/coder/tree/main/examples/templates/docker-image-builds) template:

<img width="1034" alt="Screen Shot 2022-09-19 at 8 09 19 AM" src="https://user-images.githubusercontent.com/22407953/191024652-283fb11d-9016-42f5-a4e7-6df022b37a49.png">
