### ISSUE TITLE
bug: JetBrains Gateways shows the compute resources of the node, not the workspace

### ISSUE THREAD

**Issue by sharkymark** [coder/coder#4206]
Version: [`v0.8.15+9e9a9e0`](https://github.com/coder/coder/commit/9e9a9e0cd2307abacdb573f9594bb5b0ee62e805)

This occurs in v1 too.

Is this just a known limitation of Gateway?

As a developer, I will get confused that I have more compute than I actually do have (as defined in the workspace)

<img width="1048" alt="image" src="https://user-images.githubusercontent.com/2022166/192321370-4ad5b40a-18c5-4425-9cf5-4f540b5ed97a.png">

**Comment by bpmct** [comment]
Sadly this is a limitation of containers, you'll notice the same behavior when you run `htop` inside a container/pod. https://web.archive.org/web/20220309104344/https://ops.tips/blog/why-top-inside-container-wrong-memory/

The host itself is able to measure the utilization of a container but shells inside containers are often unaware of the exact resources they consume. There _might_ be things Coder could do in order to replace these values with the [cgroup filesystem values](https://docs.docker.com/config/containers/runmetrics/#metrics-from-cgroups-memory-cpu-block-io) instead (or some other method) but not really sure.

**Comment by kylecarbs** [comment]
We can't do anything about this unfortunately :/ If someone is using VMs with Coder, this won't be the case.

If you're inside a container though, technically you do have access to the full CPU of the node.
