### ISSUE TITLE
audit: Two entries created for adding a auto-stop time of 1 hour

### ISSUE THREAD

**Issue by sharkymark** [coder/coder#4317]
Version: [`v0.9.1+27c8345`](https://github.com/coder/coder/commit/27c8345ef2d570f6bb05d601b3aa675dd0ee4670)

I added an auto-off setting to a workspace of 1 hour.

In the audit logs, it created 2 entries. The first entry does let me open it, to see the change.

Unfortunately it is in raw millisecond detail and not 1 hour like in the UI.

The unknown second audit log entry for this same event, cannot be opened.

<img width="1336" alt="image" src="https://user-images.githubusercontent.com/2022166/193492171-e2869cd3-20d6-4bca-b468-d3ef87007596.png">

**Comment by kylecarbs** [comment]
@coadler why does this happen?

**Comment by Kira-Pilot** [comment]
This is happening because we send down two requests when we update the workspace schedule form: 1) to `/autostart`, with an empty payload and 2) to `/ttl` with our updated auto-off. This is creating two audit logs, one without a diff. 

There are a couple things we should do here:
1) clean up that errant, empty API call on the FE
2) only record diffs if they are actually diffs on the BE
3) filter out audit logs with 0 diffs on the FE so that users don't see these old, nonsense records

Working on a PR for this now.

**Comment by Kira-Pilot** [comment]
Turns out we may, in the future, have audit logs with empty diffs for valid use cases.

Therefore, we are only going to fix 1. in the above comment.

If anyone needs an audit log cleanup, we should delete invalid records for them. Shouldn't be an issue as audit logs have only been enabled on our deploy.
