### ISSUE TITLE
rbac: no way to dismiss the license error

### ISSUE THREAD

**Issue by ammario** [coder/coder#4546]
I have this error but I have no intention of enabling RBAC on my license. How can I make this disappear? Should it even be there in the first place?

<img width="1722" alt="image" src="https://user-images.githubusercontent.com/7416144/195721792-a609f08a-e657-4a3d-861d-5ea795cf47f3.png">

**Comment by sreya** [comment]
I think showing it is fine but you should be able to close the warning cc @BrunoQuaresma

**Comment by sreya** [comment]
we should also only show this on the permissions tab

**Comment by ammario** [comment]
I'm confused by what "enabled" means. I assume if a feature is "enabled" there is a way to disable it?

**Comment by sreya** [comment]
I believe it means it's enabled on the server. I believe the intent is that even if you acquire a license with all features enabled you can still disable individual features on the server if you don't want to use/expose them for whatever reason. You _should_ be able to delete them but I'm pretty sure I just hard coded it as always enabled.

**Comment by BrunoQuaresma** [comment]
When we were planning this alert feature, I guess we wanted it not to be "dismissable" since it is a license violation. Thoughts?

**Comment by ammario** [comment]
> When we were planning this alert feature, I guess we wanted it not to be "dismissable" since it is a license violation. Thoughts?

Yes, I agree it should not be visually dismissable, but there should always be a way of returning the deployment to compliance.

> I can push a fix to make it a flag like everything else though.

(We spoke about this offline)

We agreed on moving the banner into the Templates > Permissions and Groups page.

**Comment by BrunoQuaresma** [comment]
@ammario 

> Yes, I agree it should not be visually dismissable, but there should always be a way of returning the deployment to compliance.

It is by upgrading a license or disabling the feature right?

> We agreed on moving the banner into the Templates > Permissions and Groups page.

This banner is not only shown on those pages. This banner is going to show up every time there is an unlicensed use of a feature, it can happen with the audit log, browser only, groups, RBAC, etc. We can put a banner on every page that is attached to a licensed feature but Idk if this fix the real issue. From what I can see, the issue is releasing new enterprise features without breaking previous licenses right? If yes, I would rather removing this banner at all until this is fixed on BE.
