### ISSUE TITLE
Advanced Coder server configuration (via config file or database)

### ISSUE THREAD

**Issue by mafredri** [coder/coder#4553]
The `coder server` command has an ever-growing list of CLI flags / environment variables that can be used for configuration. To support more complex configurations, like maps/arrays of objects, we need to evaluate other methods of configuration.

With the introduction of `codersdk.DeploymentFlags` in [#4452](https://github.com/coder/coder/pull/4452) (as part of [#4203](https://github.com/coder/coder/issues/4203)) we now have a way to declare flag-based configuration, however, this format is not immediately conducive to structured configuration like explained below.

There are two obvious choices:

1. Configuration files (e.g. JSON, YAML or TOML)
2. Configuration via WebUI and database

Option 1 has the benefit of being:

- Easy to deploy
- Keep configuration in one place
- Potential for configuration mismatch in HA setups

Whereas option 2:

- Automatically synced in HA setups
- Configuration in multiple places (cli/config and database)
- Configuration happens _after_ setting up Coder

These two options are not mutually exclusive.

**To solve our immediate needs, a configuration file is the simplest choice.**

One such need is to define multiple Git auth providers (as per [#3078](https://github.com/coder/coder/issues/3078)).

An example of such a configuration would be:

```yaml
server:
  auth_providers:
    - name: github-ee
      type: github
      client_id: "xxx"
      client_secret: "xxx"
      allow:
        signups: true
        organization:
          - coder
        team:
          - coder/backend
      base_url: https://github.enterprise.org
      git_scopes:
        - repo
```

This configuration can represent both OAuth2 and OIDC login providers and git auth providers, essentially deprecating the `--oauth2-github-*` and `--oidc-*` flags.

One way to represent the above configuration would be:

```go
type ServerConfig {
    // ...
    AuthProviders []AuthProvider `json:"auth_providers" yaml:"auth_providers" ...`
}

type AuthProvider {
    Name         string
    Type         ProviderType
    ClientID     string
    ClientSecret string
    Allow        struct {
        Signups bool
    }
    // ...
}
```

But it's unclear how this can be represented as a flag / environment variable.

**Potential solutions:**

1. Restructure from `DeploymentFlags` -> `DeploymentConfig`, potentially (ab)using struct tags to provide `comment:"This sets ..."` `default:"true"`, etc (similar to [`envconfig`](https://github.com/kelseyhightower/envconfig)).
2. Define a generic `JSONFlag` which takes json data as input and accepts some kind of generic type to represent
3. Define a new flag for every custom type

In option 1, we'd have to restructure a lot of the work in [#4452](https://github.com/coder/coder/pull/4452) which is not ideal.

In options 2 and 3, the command line use would still be somewhat weird as you'd have to provide something like `--auth-provider '[{"name":"github-ee",...}]'` as input. (I also don't have a clear idea of how we'd implement these currently.)

**Other ideas:**

Allow index-based environment variables and flags.

```shell
export CODER_AUTH_PROVIDER_0_NAME=github-ee
export CODER_AUTH_PROVIDER_0_TYPE=github
export CODER_AUTH_PROVIDER_0_CLIENT_ID=xxx
export CODER_AUTH_PROVIDER_0_CLIENT_SECRET=xxx
# ...
```

This also seems somewhat weird, and potentially easy to miss-type something. It's also unclear how we'd represent these as part of `--help` as they'd need a dynamic runtime factor for processing them.

---

Ideas/suggestions are welcome, especially @f0ssel and @deansheather who worked on deployment flags.

**Comment by bpmct** [comment]
I'm very much in favor of a configuration method that can be source-controlled (such as environment variables or config flags) since it contributes to #2291  👍🏼 

As we're developing this, we should think about how configuration would work across multiple deployment methods:
- Coder as a system service
- Coder on Kubernetes via Helm
- Coder via docker-compose
- Coder on an app engine such as ECS

Our current environment variable configuration method is quite pleasant in this way:
- the Helm chart rarely needs to be updated to specify flags
-  you don't need to mount a PVC or external config file in Kubernetes/docker-compose. the pod spec has all the configuration Coder needs. 

However, I see the shortcomings when it comes to configuring lists or running Coder in HA.

I'm slightly concerned about how a config file would work with containerized deployments (such as Kubernetes or DigitalOcean apps). Is an external volume mount necessary to store the config? Does it reference/require a s3 bucket? Is each value represented in the Helm chart? I can't think of a good solution here, but that doesn't mean there is one.

Based on the constraints above, I'm actually most in favor of `CODER_AUTH_PROVIDER_0_NAME=github-ee`. While slightly weird, it's still feels intuitive and am not sure if a proprietary config file makes things better.

With licensing and HA in mind, some other interesting problems arise. I imagine these are out of scope for this issue since they don't reflect our near-term product priorities?

- A Coder admin (not necessarily the infra admin) can attach licenses and therefore enable features
- If multiple replicas are running, potentially across regions configuration could get out of sync because there is not a single source of truth for the deployment config.

**Comment by bpmct** [comment]
re. Kubernetes config:

> I can't think of a good solution here, but that doesn't mean there isn't one.

Doh - I didn't think about [ConfigMaps](https://kubernetes.io/docs/concepts/configuration/configmap/).

**Comment by f0ssel** [comment]
This can be closed with https://github.com/coder/coder/pull/4727 now merged.
