### ISSUE TITLE
Non URL-safe characters in app names cause them to be inaccessible over subdomains

### ISSUE THREAD

**Issue by ntimo** [coder/coder#4571]
# Description
When using coder_apps with `subdomain=true` every time you try to open the app using the button in the ws dashboard coder shows a `404 - Application not found` page.

# Steps to reproduce
1. Define a coder app in your main.tf like this:
```

resource "coder_app" "codeserver" {
  agent_id  = coder_agent.dev.id
  name      = "Code Server"
  url       = "http://localhost:8080/?folder=/home/coder/workspace"
  icon      = "/icon/code.svg"
  subdomain = true
  healthcheck {
    url	  = "http://localhost:8080/healthz"
    interval  = 2
    threshold = 10
  }
}
```
2. Push the template change
3. Start the workspace
4. Try to open codeserver

# Addition Infos
Coder Version: [Coder v0.9.10+574e5d3](https://github.com/coder/coder/commit/574e5d37c76cb0b154ad62ccd4582e588235b15a)

Coder has a `CODER_WILDCARD_ACCESS_URL` configured to `*.coder.example.com`

**Comment by ntimo** [comment]
Ping @deansheather

**Comment by bpmct** [comment]
Looks like this only occurs if the app name contains an uppercase character

```diff
-  name      = "Code Server"
+  name      = "code server"
```

Will work as a workaround

**Comment by ntimo** [comment]
One question that came to my mind is why is coder using the name = "What Ever" to construct the subdomain url. Since this at least for me was kind if just a way to set a pretty display name. I would have thought coder would use the resource name to build the fqdn. Which in my example above would be "codeserver"

**Comment by ntimo** [comment]
Oh and this is the 404 page I get when I try to open a link for the apps with an uppercase letter in the name.
![image](https://user-images.githubusercontent.com/6145026/196047440-f18ba60e-aa67-4519-ac76-2eb12a8af66e.png)

**Comment by deansheather** [comment]
We should probably switch to using the resource ID from terraform for both path-based and subdomain app URLs, and only use the name for the button in the UI.

**Comment by deansheather** [comment]
> One question that came to my mind is why is coder using the name = "What Ever" to construct the subdomain url. Since this at least for me was kind if just a way to set a pretty display name. I would have thought coder would use the resource name to build the fqdn

We currently use the same app lookup logic for both path-based apps and subdomain-based apps. The original implementation of path-based apps used the name field which works fine in paths as you can easily have non URL-safe characters in them. For subdomains it obviously will not work and I didn't really consider this during implementation which is my bad.

In the terraform template we use internally at coder (found at `./dogfood` in this repo) we only use URL-safe characters for the app name which prevented us from discovering this bug during our own usage.

I'm working on a patch for this right now which will switch to using the resource name from terraform rather than the app name in all cases, including path-based apps.
