### ISSUE TITLE
feature request: make forwarded ports public or share with other users

### ISSUE THREAD

**Issue by ntimo** [coder/coder#4615]
> **Note**
> See product requirements below: https://github.com/coder/coder/issues/4615#issuecomment-1709080695

# Description
Currently it possible to share coder apps (https://github.com/coder/coder/pull/4378) with anyone by setting their access level to public. However when developing using coder it could be necessary to be able to share a random port publicly without having a coder app declared for this at first. Therefore I think it would be beneficial if this would be possible. Since the user can't add coder apps on his own he has no way to do this.

**Comment by phorcys420** [comment]
You can enable HTTP port forwarding if you have a wildcard URL.
![image](https://user-images.githubusercontent.com/57866459/196378084-2f6cd324-33e7-4527-9254-b64d8acb0f2b.png)

for TCP/UDP you'll have to use the ``coder port-forward`` command, unfortunately you need a client machine for that.
docs on both of these can be found [here](https://coder.com/docs/coder-oss/latest/networking/port-forwarding)

**Comment by ntimo** [comment]
> You can enable HTTP port forwarding if you have a wildcard URL. ![image](https://user-images.githubusercontent.com/57866459/196378084-2f6cd324-33e7-4527-9254-b64d8acb0f2b.png)
> 
> for TCP/UDP you'll have to use the `coder port-forward` command, unfortunately you need a client machine for that. docs on both of these can be found [here](https://coder.com/docs/coder-oss/latest/networking/port-forwarding)

I know that you can create links for ports ;) but you can't share them publicly since they are always private. And I would like to share them publicly if possible for certain ports without adding a coder_app to my terraform file.

**Comment by MrPeacockNLB** [comment]
Thumbs up as not always it is possible to determine before a workspace starts what should be shared with others. Sharing on the fly would be great as it opens a whole lot of new possibilities.

**Comment by bpmct** [comment]
Here's a bit of a hacky workaround you can give devs in the meantime: https://github.com/bpmct/coder-templates/tree/main/docker-arbitrary-port


https://github.com/coder/coder/assets/22407953/4765e2d9-1642-4ccb-9be9-ce1cae70db86

**Comment by matifali** [comment]
I didn't notice that there is a similar issues already. So bringing this over from
https://github.com/coder/coder/issues/8908#issue-1836946721

**Comment by pi3ch** [comment]
Here is my workaround for accessing two apps.

Create two `coder_app` to port forward 8080 and 5000 (you can use one app or add more apps).

```
# app - 8080
resource "coder_app" "app-8080" {
  agent_id  = coder_agent.main.id
  slug      = "app8080"
  url       = "http://localhost:8080"
  subdomain = true
  share     = "public"
}

# app - 5000
resource "coder_app" "app-5000" {
  agent_id  = coder_agent.main.id
  slug      = "app5000"
  url       = "http://localhost:5000"
  subdomain = true
  share     = "public"
}
```
Pay  attention how app slug is set: `app+PORT`

Overwrite `VSCODE_PROXY_URI` in the `coder_agent`:

```
resource "coder_agent" "main" {
  # ...
  env = {
    VSCODE_PROXY_URI = "https://app{{port}}--main--${data.coder_workspace.me.name}--${data.coder_workspace.me.owner}.YOUR-WILDCARD-DOMAIN-HERE"
  }
```

In code-server anytime you start the app, it prompts you the correct URL to navigate to.

**Comment by bpmct** [comment]
## Background

In Coder, a template admin can make `coder_apps` shared with all users, the public, or owner-only (default): https://registry.terraform.io/providers/coder/coder/latest/docs/resources/app#share

Coder v1 had a feature called dev URLs, which allowed a user to share an arbitrary port. This feature was nice because template admins didn't have to predict what ports users needed to share or build workarounds (see above). 2-3 major customers are using workarounds in the product to achieve this functionality today.

## Product Requirements

### Must have

- [ ] A server-wide flag specifies the max sharing level for ports. The default is "authenticated." This means that ports cannot be shared with non Coder users unless the server admin changes it to `public`. 
- [ ] A user can make specific ports sharable in the UI. By default, all ports are only open to the workspace owner.

### Should have

- [ ] A user can change the sharing permissions of ports in code-server and VS Code (perhaps with the native dropdown, perhaps with the VS Code extension)
- [ ] A template can specify whether sharing is enabled and the max sharing level (inheriting the deployment-wide max)

### Nice to have

- [ ] A user can change sharing permissions directly from JetBrains Gateway
- [ ] A user can specify a duration in which the port is shared (e.g. "just for this session", "2 hours," etc.)
  - [ ] An admin can specify a max duration as a server-wide flag

**Comment by mtojek** [comment]
Resolving in favor of https://github.com/coder/coder/issues/11486, so we have a single umbrella issue.
