### ISSUE TITLE
progress bar: build running is inaccurate 

### ISSUE THREAD

**Issue by sharkymark** [coder/coder#4676]
Version: [`v0.10.2+fbbecf0`](https://github.com/coder/coder/commit/fbbecf0846344650b889629005731388f3a35082)

The workspace build progress bar is inaccurate in some of my workspaces and tells me any moment now for 10-15 seconds.

I would imagine changing container images, image pull policies, and scaling of Kubernetes nodes making this progress bar inaccurate.

![image](https://user-images.githubusercontent.com/2022166/197186605-d24b623f-e04d-42b1-b977-2d17d4416ff9.png)

**Comment by kylecarbs** [comment]
@ammario we need to hide the progress bar unless there are N amount of builds to collect data from. Right now, it shows on the first workspace build.

**Comment by ammario** [comment]
Even if N is large it can be inaccurate for the reasons Mark describes. Another example is pushing a template update that dramatically affects build time. In that case it could take two weeks for the bar to return to accuracy. This problem was my largest hesitation to building this feature. Some alternatives:

* We can take the coefficient of variation across the builds, and if it's above a threshold not show a progress bar
* We can ditch the progress bar and just show an ETA like "1m to 3m remaining..." where "1m" is the 5th percentile and 3m is the 95th percentile
