### ISSUE TITLE
Insights page for at-glance state of a Coder deployment

### ISSUE THREAD

**Issue by bpmct** [coder/coder#4877]
As a Coder administrator, I'd love to see real-time and historical data on connections, queues, etc. The data should also be exposed via Otel/Prometheus for users to build custom queries and dashboards :)

I don't feel strongly about the format of any of these charts/graphs, but as a Coder administrator, this is data I'd certainly be interested in seeing (or at least having exposed via Prometheus). Open to feedback though! 😄

![insights](https://user-images.githubusercontent.com/22407953/199762351-8092e132-b432-4919-9a19-57a29c16f8f1.png)

**Comment by mtojek** [comment]
We had a short chat about this issue with @bpmct today, thanks for raising it! Let me share a few chart ideas/ops problems they can solve:

1. Correlation with Coder deployments - would be nice to know whether the increase in latency is related to a recent deployment. 
2. Latency (p90, p95) of interconnections between replicas.
3. Live auditing? Who is currently connected?
4. Insecure connections, and suspicious IP addresses.
5. Time-to-bootstrap a workspace (p90, p95) - could be also correlated with deployments.
6. Latest errors/failure (listing or a table) - it may help in root cause analysis if those are actionable.
7. List of workspaces that are security-outdated or vulnerable - these can be also click-to-action items so that Coder admins can immediately take them down. 

Once we agree to expose Coder metrics on charts, we can consider jumping on to the next level - alerting or integration with PagerDuty. The admins may configure some triggers on failures or increased latency.

> I don't feel strongly about the format of any of these charts/graphs, but as a Coder administrator, this is data I'd certainly be interested in seeing (or at least having exposed via Prometheus). Open to feedback though! 😄

Yeah, for some cases, Prometheus may be sufficient, but usually admin people value their time and they would rather use already prepared graphs :) If we don't want to build our own dashboards, maybe we can prepare ones that can imported into DataDog or Kibana.

We could share some metrics with workspace owners so that they are also aware of potential issues.

BTW I don't know if there is already that feature, but it's a common practice to show a warning message in the UI if some services might be impacted by a data center outage or similar. If there isn't any mechanism like that in Coder, we could also consider it :)

**Comment by bpmct** [comment]
Oh - I definitely think we should display our own metrics dashboard. Wasn't fully sure if these were the exact ones we should show.

Identifying disconnected agents + network bandwidth + dropped network connections would be huge

**Comment by bpmct** [comment]
> BTW I don't know if there is already that feature, but it's a common practice to show a warning message in the UI if some services might be impacted by a data center outage or similar. If there isn't any mechanism like that in Coder, we could also consider it :)

Ah we have #4322

**Comment by mattlqx** [comment]
Importing some of my thoughts onto this.

Finding where the line would be of detail to create in UI visualizations for and what should be left to exported metrics for people to create their own views/dashboards on will be a fine line. When I think about managing an installation with hundreds of workspaces, I want to know the following (some will be duplicates of what's already been said above)...

Basic aggregated stats, in both totals and broken down by template:
- Total workspaces running and stopped
- Number of workspaces per user
- Number of apply failures
- Stats on duration of runs (avg, min, max, a few percentiles)

Stats per template and version:
- Success and failure
- Number of resources
- Unique historical user count

All the server stats possible. I'm not well versed in Coder's operations to really say what exactly, but metrics that track performance, scaling, and error states I'm all very interested in.

I'd really love a tool to dig into failures at an aggregated level and running stats on template versions themselves. Each template could have success and failure counters. If I want to drill down into failures, it would be very helpful if there were a way to show commonality amongst failures (like exception collectors like [Sentry](https://sentry.io/) do) grouping them together. I could determine if some runtime/operation errors occurred easily with that information. Or that particular variable in my Terraform on a new version was causing an error.

My opinion on prepared views in product is usually that they come up short with not being flexible enough on timescales, being able to export them point-in-time when there's an incident (yay screenshots), and element selection/filtering. I love free data though so I take what I can get but usually spend most of my time in whatever tool I already have for slicing and dicing metrics ingested by our system.

**Comment by mtojek** [comment]
👍

**Comment by BrunoQuaresma** [comment]
@mattlqx thx a lot for sharing those insides. From my perspective, I would do the following:
- Have a dashboard page outside the settings page to show those metrics so we have more space to show more relevant information. In my head it would be the index page for admin users, today it is the workspaces page.
- Some of this info could be embedded into the screen's existing elements. For example, the template stats could be displayed on the template page when the user is an admin. We could also show the number of workspaces per user in the user's table.

I will reach out to a few users to get more feedback about this and how we can improve the admin experience so we can get back to this with a better plan.

**Comment by Emyrk** [comment]
We should try to implement this in an extendable way. In v1, the metrics query became large and hard to maintain.

It would be ideal if we could just use an existing time series store like Prometheus and write queries against it. But I understand embedding all that is difficult and making external calls isn't ideal

**Comment by BrunoQuaresma** [comment]
@Emyrk could you please post it on https://github.com/coder/coder/discussions/8109?

**Comment by BrunoQuaresma** [comment]
@Emyrk could you please post it on https://github.com/coder/coder/discussions/8109?

**Comment by BrunoQuaresma** [comment]
Closing this in favor of the RFC for now https://github.com/coder/coder/discussions/8109
