### ISSUE TITLE
Jupyter templates stopped working in 0.12.2 - 404

### ISSUE THREAD

**Issue by sharkymark** [coder/coder#4895]
Version: [`v0.12.2+6bfdccd`](https://github.com/coder/coder/commit/6bfdccda2f3e9b61b415d27b15b657c81a283c3c)

My docker and Kubernetes-based templates for JupyterLab and Notebook have worked for months, and no longer work in 0.12.2

The process is running, health check passes.

See attached templates

![image](https://user-images.githubusercontent.com/2022166/199953549-c2d93fa7-3b6f-46cb-9690-934c6a6105bc.png)
[docker-with-jupyter.zip](https://github.com/coder/coder/files/9937380/docker-with-jupyter.zip)
[pod-with-jupyter.zip](https://github.com/coder/coder/files/9937384/pod-with-jupyter.zip)

**Comment by sharkymark** [comment]
Although the templates use Coder provider 0.5.3, it is failing because `slug` was not specified. This only is with Jupyter.

Seems like a bug. @deansheather said it should default to `name` if `slug` is not specified.

Updating Coder provider to `0.6.0` and adding the `slug` parameter in `coder_app`, resolved this.

Also removed workspace owner and name from `coder_app` URL and used `subdomain=true` and removed the `baseURL` from the Jupyter start up command string.

**Comment by sharkymark** [comment]
[Updated pod repo](https://github.com/sharkymark/v2-templates/blob/main/pod-with-jupyter/main.tf)
[Updated Docker repo](https://github.com/sharkymark/v2-templates/blob/main/docker-with-jupyter/main.tf)

Subdomain does not work with tunnel in this case. Need to debug why.

**Comment by sharkymark** [comment]
@deansheather @bpmct my update templates with `slug` that work for jupyter, do not work in tunnel. I get

![image](https://user-images.githubusercontent.com/2022166/200120458-0cc0312f-531a-410a-bf03-a58910ad76ea.png)

**Comment by sharkymark** [comment]
ps it works if you open an arbitrary 8888 port forward though.....

**Comment by kylecarbs** [comment]
@deansheather any ideas why this failed? I'd assume this wasn't intentional to be breaking, and that we should release a patch.

**Comment by deansheather** [comment]
> my update templates with slug that work for jupyter, do not work in tunnel. I get

@sharkymark this is because of the 63 character limit, firefox doesn't report a very helpful error page sadly

> I'd assume this wasn't intentional to be breaking, and that we should release a patch

@kylecarbs yes this wasn't intentional I'll work on fixing it on Monday

**Comment by deansheather** [comment]
I determined that this was caused by the app URL changing and jupyter not being aware of the new value. In `0.12.2` onward we use the new `slug` property in the coder terraform provider 0.6.0+ in URLs. The slug needs to be a hostname-safe value.

However, for backwards compatibility with non-upgraded templates, we made it so that if the coder terraform provider was too old to have the new `slug` field we would use the resource name instead. The resource name has a strict regex similar to the slug regex, so we did this to avoid people getting errors at build time saying that their names weren't hostname safe.

In Mark's case, the resource name for the coder app was `jupyter` but the name was `jupyter-notebook`. The jupyter daemon has a flag that sets the base URL, which was being set to `/@username/workspace/apps/jupyter-notebook`, but that URL was now incorrect as a result of this change. Jupyter would then redirect to what it thought was the correct URL, but that would result in a 404 from Coder as an app didn't exist with that slug.

The scope seems limited to only users using jupyter in this way and it's fixable by upgrading to coder terraform provider 0.6.0+, so I've added a warning to the releases page for all 0.12.x versions informing users to try upgrading their terraform provider version if they have difficulties accessing Coder apps.
