### ISSUE TITLE
bug: audit logs do not capture a workspace auto stopping, but they appear if a manual stop

### ISSUE THREAD

**Issue by sharkymark** [coder/coder#5003]
Version: [`v0.12.5-devel+d64c73dd`](https://github.com/coder/coder/commit/d64c73dd746cd44a8b5bf6311561f68f58ca3bb8)

I started 2 workspaces today, with 1 hour shut off settings.

There are no entries in the audit logs for the off event.

![image](https://user-images.githubusercontent.com/2022166/201158126-c4bce3c4-d2d9-4974-88fb-3d595748299f.png)

Here is a workspace I started and stopped quickly - in the logs!

![image](https://user-images.githubusercontent.com/2022166/201158477-72268375-0262-4bf6-b7be-593e179f4a86.png)

**Comment by Kira-Pilot** [comment]
@sharkymark sounds like auto-off workspace stops are not creating audit log entries, while manual workspace stops are. Is this correct, or were these both auto-off?

**Comment by Kira-Pilot** [comment]
@sharkymark I'm closing this because it appears resolved by #5143; however, please reopen if you see anything amiss going forward!

Testing:
<img width="1341" alt="Screen Shot 2022-12-08 at 6 05 44 PM" src="https://user-images.githubusercontent.com/19142439/206585940-033f3e51-195c-4706-b313-9b9053e259ba.png">
