### ISSUE TITLE
bug: "Stops at" UI element does not reflect the set auto-stop value

### ISSUE THREAD

**Issue by ericpaulsen** [coder/coder#5080]
### What happened?

I'm running on `0.12.7`. after setting my workspace auto-stop to 5 hours, the `STOPS AT` value did not change and continued to show 1 hour from the current time.

<img width="467" alt="Screen Shot 2022-11-14 at 9 49 50 PM" src="https://user-images.githubusercontent.com/9683576/201822008-a3659a4d-8cb3-4e8c-a4d7-139caf07abc1.png">

<img width="399" alt="Screen Shot 2022-11-14 at 9 50 05 PM" src="https://user-images.githubusercontent.com/9683576/201822048-8961ce41-fc64-4ba3-a268-5e4fb25e5383.png">

### What did you expect to happen?

I expected my workspace `STOPS AT` value to be 5 hours from the current time.

**Comment by presleyp** [comment]
The behavior only takes effect after you start the workspace again - note that it says "Your workspace will shut down 5 hours after its next start." I agree that it's surprising behavior, but the problem is that you could edit your workspace more than 5 hours after it started, making the instruction technically impossible to follow (though it could shut down immediately, but I don't know if that's ideal either). @bpmct what do you think?

**Comment by bpmct** [comment]
> The behavior only takes effect after you start the workspace again

Could we change this behavior to be effective immediately?

> the problem is that you could edit your workspace more than 5 hours after it started, making the instruction technically impossible to follow (though it could shut down immediately, but I don't know if that's ideal either).

When a workspace schedule is edited, perhaps we should bump the TTL by 1 hour (and notify the user) to avoid immediate shutdowns. When the user has an active connection (VS Code, SSH, websocket on coder_app), we also bump the schedule by one hour so this seems appropriate.

**Comment by dcarrion87** [comment]
Potentially unrelated but the whole auto stop reflecting / change is broken for us in 0.12.6: https://github.com/coder/coder/issues/5146
