### ISSUE TITLE
Multiple licenses?

### ISSUE THREAD

**Issue by ammario** [coder/coder#5281]
@spikecurtis — I'm curious about the decision to allow multiple licenses? It would be a lot easier to present and work with licenses if there was a maximum of one.

**Comment by spikecurtis** [comment]
Lots of operational reasons.

Let’s say a customer renegotiates their contract, and drops a feature.  If they can only have one license, they have to either upload the new license right away and stop using the feature immediately, or wait to upload, and risk old license expiring.

Or, if we change license format, and people need to do a rolling update from a version that understands the old format to one that understands the new.

It’s generally quite a pain to modify code that implicitly assumes one license to allow multiple, and assuming multiple allows flexibility.

**Comment by ammario** [comment]
Ok, I get those reasons, do you think it's worth the UX challenges such as displaying multiple licenses in the frontend (#5100 ) and having to deal with IDs in the CLI? Also, is there prior art of other similar tools taking this multiple license approach?

**Comment by spikecurtis** [comment]
In terms of the front end UI, having multiple unexpired licenses is definitely the exception, so I think it would be fine to build the UI that looks good with one and not worry too much if it looks a bit jank with more than one.

Are there specific challenges that we can't solve with like a `for` loop?

We looked at some Hashicorp stuff when designing the feature, and the approach they take is having the license be an environment variable.  That avoids some problems like rolling updates, but at the cost of a UX that is less friendly.  We decided to put the license in the database so that you can have a frontend page to copy and paste it into.
