### ISSUE TITLE
coder Linux Unable to connect

### ISSUE THREAD

**Issue by da00891219** [coder/coder#5307]
Version: [`v0.13.1+9e80322`](https://github.com/coder/coder/commit/9e80322fe5f0c329492be62e26f3d36f97e1f3ca)

After Upgrade to code-oss-v2, Workspace doesn't show Terminal, code-server Icons.
![coder1](https://user-images.githubusercontent.com/112606830/205888019-f4baf492-1665-4087-949d-c83549024597.PNG)

**Comment by sharkymark** [comment]
How are you starting the coder server?

If just `coder server`, we provide a publicly accessible Access URL so the workspaces can reach the Coder control plane.

If you specified the Access URL in the command line along with `coder server`, it must be reachable by the workspace.

e.g., if you made it localhost:3000 or 127.0.0.1:3000 and the workspace running somewhere other than localhost, it was cause that state you see in the UI since the workspace agent cannot reach the Coder control plane.

**Comment by da00891219** [comment]
@sharkymark Is there any fix or work around for accessing DNS URL. Thanks for the help.

**Comment by bpmct** [comment]
👋🏼 @da00891219 not sure how we missed this! Are you setting `CODER_ACCESS_URL` to the external IP address with HTTP? What are the logs of the workspace pod?

If you're no longer working on this, I totally understand. I'll just close the issue and we'll think about ways we can improve the messaging/troubleshooting steps here.

**Comment by da00891219** [comment]
@bpmct I am still troubleshooting the problem. I will post the logs in 2 days. Please keep it open. thank you.

**Comment by bpmct** [comment]
Are you running Coder on a public URL/IP? If so you can start Coder with `CODER_ACCESS_URL=http://coder.mydomain.com` or `CODER_ACCESS_URL=https://coder.mydomain.com` which should resolve this. It seems like the container is unable to reach the Docker host.

Also, are you running Coder on port 7080?

**Comment by da00891219** [comment]
upgraded to v0.17.0 and configured CODER_ACCESS_URL to our DNS URL and issue is fixed.
