### ISSUE TITLE
code-server GitHub Copilot Extension is required how to install?

### ISSUE THREAD

**Issue by da00891219** [coder/coder#5312]
I have followed below doc and installed github copilot extension on coder (code-server), but it is not enabled. how to enable gothub copilot on code-server?

https://coder.com/docs/code-server/latest/FAQ#how-do-i-install-an-extension
code-server --install-extension extension-id
code-server --install-extension github.copilot

**Comment by da00891219** [comment]
logs/20221206T141537/remoteagent.log:[2022-12-06 14:15:38.975] [remoteagent] [error] Error: Failed Installing Extensions: github.copilot

**Comment by ghuntley** [comment]
:wave: there’s a couple different ways to use copilot with Coder:

- Visual Studio Desktop Remote SSH (https://code.visualstudio.com/docs/remote/ssh) from a desktop to the Coder workspace.
- Install https://code.visualstudio.com/docs/remote/vscode-server in your workspace template.
- Via JetBrains (whilst I haven’t tested it myself in theory it is possible to use w/Gateway)

Due to the licensing of Copilot, it cannot be used in free or open-source software such as code-server or https://vscodium.com/.  It is possible to install Copilot in code-server and vscodium but this likely breaks Microsofts T&C’s and advise doing research.

https://github.com/VSCodium/vscodium/issues/1020#issue-1180219275

I can’t help with troubleshooting if you head down this path. What works w/VSCodium will work with code-server.

If you are looking for suggestions to alternatives are you aware of https://www.tabnine.com/?
