### ISSUE TITLE
Self-hosted documentation

### ISSUE THREAD

**Issue by bpmct** [coder/coder#5466]
Allow Coder admins to enable "offline documentation" for users to browse, hosted by their Coder deployment. e.g. `https://coder.internal.network/docs`

**Comment by bpmct** [comment]
@BrunoQuaresma did this for Coder v1 (see https://s.cdr.dev/docs)

**Comment by BrunoQuaresma** [comment]
I would be happy to take a look into this if we want to have something like that.

**Comment by ntimo** [comment]
Just wanted to give my feedback, GitLab also does this and I quite often use the bundled docs since they will also match my GitLab version. Therefore I really like the idea of coder also having this, but I think it should be an oss feature and not be license limited. 

This would also make it possible to link to these docs from within the coder application it self which would be cool.

**Comment by BrunoQuaresma** [comment]
@ntimo definitely!

**Comment by matifali** [comment]
Sounds very useful. Looking forward to it.

**Comment by sharkymark** [comment]
Some of Coder's paying v1 customers requires offline documentation since they run air-gapped.  Re-opening @ammario @bpmct so this gets prioritized.  Notice the comment above about GitLab does this. We often see Coder and GitLab together in enterprise opportunities in regulated and highly secure deployments.

**Comment by BrunoQuaresma** [comment]
Related RFC https://github.com/coder/coder/discussions/8110

**Comment by bdsoha** [comment]
@bpmct The [sample repo](https://github.com/bpmct/coder-offline) does not document the creation of a workspace in an air-gapped network.
This [related issue](https://github.com/coder/coder/issues/5781) focusses on exactly that.
Any suggestions on a workaround for the required `code-server.dev` access during install?

**Comment by matifali** [comment]
@bdsoha have you checked https://coder.com/docs/v2/latest/install/offline#offline-docs ?

**Comment by bdsoha** [comment]
@matifali Yes I have and it was helpful.
I was referring to documentation that specifically takes into account the creation of *workspaces* in an offline environment.

**Comment by bpmct** [comment]
What issues are you running into when provisioning a workspace? The offline docs go over this in some detail
