### ISSUE TITLE
Cache `gitssh` requests from the coder agent

### ISSUE THREAD

**Issue by janLo** [coder/coder#5605]
We have a project with hundreds of submodules. The checkout process of this runs in the coder agent api ratelimit:
```
You've been rate limited for sending more than 512 requests in 1m0s.
Run 'coder gitssh --help' for usage.
fatal: Could not read from remote repository.
```

Would it be possible to cache the response for "a while" in the agent (1sec should be already sufficient here to not hit the limit).

**Comment by coadler** [comment]
This is actually a bit tricky since each `coder gitssh` is running in a separate process from the agent, so we have two less than ideal options: synchronizing on-disk or adding IPC to the agent. While I agree this is a good candidate for caching, I unfortunately think both of these options are too heavy handed at the moment to implement specifically for this.

One workaround to this for now would be to increase the default rate limit with `CODER_API_RATE_LIMIT`/`--api-rate-limit`.

**Comment by janLo** [comment]
I don't need a solution immediately because I can work around this using plain ssh and a (forwarded) agent. 

Maybe it would be an option for the future to let the coder agent speak the SSH agent protocol. Then we could plug it into plain ssh and use the SSH multiplexing that we used so far:

```
core.sshcommand=ssh -o ControlMaster=auto -o ControlPath="/build/.ssh/ssh-%r@%h:%p" -o ControlPersist=60 -o BatchMode=yes
```

**Comment by deansheather** [comment]
Another customer ran into this today when using Android `repo` cloning tool.

**Comment by kconley-sq** [comment]
When we use the `repo` tool to check out an AOSP project (~100 GB of data fetched from 700+ git repos) we noticed the overall fresh check out time takes 30-35 minutes if we use the Coder-managed SSH key for authentication (https://coder.com/docs/v2/latest/secrets#ssh-keys) but only takes 10-12 minutes if we use an SSH key we've created ourselves that exists statically in the workspace's `~/.ssh/` folder. Could that performance be improved with the caching idea described in this issue?
