### ISSUE TITLE
Customize workspace name validation

### ISSUE THREAD

**Issue by dcarrion87** [coder/coder#5619]
Is there a way to do validation on the workspace name? E.g. limit workspace names to 8 characters.

**Comment by BrunoQuaresma** [comment]
I don't think this is possible right now but I would love to understand your use case.

**Comment by dcarrion87** [comment]
Have some templates that fire a helm release where we name some pods based on the workspace.

**Comment by kylecarbs** [comment]
@dcarrion87 can you use Terraform to truncate the workspace name instead?

**Comment by dcarrion87** [comment]
Causes confusion. Just not sure why there isn't any option to put validations on a workspace name.

**Comment by kylecarbs** [comment]
I'm open to this, but only if it lets us provide uniform validation everywhere, which seems a bit tricky. @dcarrion87 are there other services that let you customize the resource naming scheme? For us this is tricky, because the workspace name needs to be a valid DNS host for things like `coder config-ssh` -> `ssh coder.my-workspace`.

**Comment by dcarrion87** [comment]
@kylecarbs we've ended up changing the naming scheme. Makes mapping a little harder but it's minimised issues we were experiencing. I'll close this since there doesn't seem to be others affected.
