### ISSUE TITLE
Is it possible to obtain a user session token through SSO?

### ISSUE THREAD

**Issue by NiklasRosenstein** [coder/coder#5716]
I was playing with the thought of integrating GitLab with Coder by leveraging it's existing Gitpod integration. You can point a self-hosted GitLab instance at your own Gitpod instance, and I think that this Gitpod instance might as well be a shim service that actually provisions a Coder workspace instead.

It appears that all GitLab does is to redirect the user to a URL like `$YOUR_GITPOD_URL/#https://my-gitlab.com/group/repo/-/tree/develop/`.

I would have `$YOUR_GITPOD_URL` be a small Flask application that asks the user to authenticate via SSO (we use Azure AD) to authorize the application to perform actions in Coder on their behalf; then it would spin up a Workspace for the user and wait until the workspace is set up, etc.

I'm not super familiar with the corresponding SSO/Oauth flows yet, or the Coder API. Is this something that would be possible?

**Comment by coadler** [comment]
I don't think this is something that would work currently since Coder doesn't have an OAuth server implementation for authorizing 3rd party applications. Though, I believe we are planning on implementing what you may want in https://github.com/coder/coder/issues/3981. We can probably implement that same `example.com/#repo`-style URL as well.

**Comment by bpmct** [comment]
I'm pretty sure this will be done with #3981. @kylecarbs can confim
