### ISSUE TITLE
Coder leaving workspace resources around on failure

### ISSUE THREAD

**Issue by dcarrion87** [coder/coder#5815]
We're having an issue with Coder leaving resources around when creation fails. Users are naturally lazy and won't try and fix this themselves.

E.g. this scenario:

```
kubernetes_pod.main[0]: Still creating... [4m50s elapsed]
kubernetes_pod.main[0]: Still creating... [5m0s elapsed]
kubernetes_pod.main[0]: Creation errored after 5m0s
```

How do we get coder to run a stop automatically when this happens so pods aren't sitting around in pending state forever plus all the rest of the supporting resources?

I'd rather not have to write our own cleanup scripts.

**Comment by ElliotG** [comment]
I think there are circumstances where the team maintaining Coder might want to look at the pod later for forensics. What are your thoughts on the following:

A: Coder provides a script or CLI that identifies and deletes pods like this, but it's up to you to choose to run it
B: Coder deletes orphaned pods that are more than X hours or days old

Or maybe you have another idea that would work well?

**Comment by dcarrion87** [comment]
Hi @ElliotG we would want the option of both terraform delete with stop count and without stop count. There are other resources that come up as part of the workspace start that need to be removed as well. 

Something inbuilt into coder would be ideal. We could script this now but we want to minimise external services maintaining coder over time and let coder do this itself. At the moment it's an admin doing coder workspace stops across the coder instances we maintain for people that have just left their workspace in failed state indefinitely. 

Forensics we are building out logging and other things to catch why something happened. 

Happy for it to be on an optional delay as well.

**Comment by dcarrion87** [comment]
Cleaning up lots this week after having to deprecate a template today because there's no deprecated feature in Coder and they just fail out. I really do wish there was auto cleanup.

**Comment by Kira-Pilot** [comment]
Related to #6535

**Comment by dcarrion87** [comment]
I think a stop on failure would be the way to go. That allows user to review the run logs and see that it stopped because of a failure. Or on failure allow an option to trigger a stop and leave in failed state.

**Comment by dcarrion87** [comment]
@Kira-Pilot @bpmct @kylecarbs do you know if this is likely to be worked on in the next 2-4 weeks?

If not, we think it's affecting us enough operationally that we're willing to try implement this ourselves directly in the code base. E.g. template or admin option to trigger a stop (apply with counts) on failures. 

Following planning meetings we think it makes more sense to do the implementation straight in coder vs write something to watch or hook coder. 

If there's something already in flight that achieves this then we'll hold off.

**Comment by bpmct** [comment]
We have something in-flight to stop resources in a failed state, but it probably will not be shipped within 2-4 weeks. This is on our roadmap though and we will have a built-in solution for this, and optionally cleaning up inactive workspaces as well. Time-frame is TBD but would probably be ~2 months until this is shipped.

> Following a planning meeting we think it makes more sense to do the implementation straight in coder vs write something to watch or hook coder externally.

I'm curious why this is? Is this for better user experience (e.g. users can "recover" from a failed state before churning) or does it just "feel" more appropriate? 

I know this sounds silly, but if y'all were to temporarily set up an hourly CRON that queries all workspaces and stops any failed builds, what functionality are you missing? As I said, we plan on creating a native feature for this in Coder that is "smarter" than this but wanted to get a better sense of how a native feature could help you, so that we can make sure we're building the right thing :)

**Comment by dcarrion87** [comment]
> I'm curious why this is? Is this for better user experience (e.g. users can "recover" from a failed state before churning) or does it just "feel" more appropriate and saves you from spinning up and maintaining extra infra?

A bit of both. It doesn't make sense to us why coder would just leave the workspace in a broken state on failed starts. If it failed starting, roll back half baked infra and let the user know that's what happened. Sweeping through failed starts every hour just doesn't feel like the right way to handle it.

If there's something I've learnt over time is nothing comes with little maintainence and overheads. Something you think might be a quick job turns into more than that tweaking, maintaining and then eventual unravelling. We're already doing similar for other things and have regretted it so far remembering that those "gap handler" crons are there and need to be managed.

Understanding the timing and knowing something is in the works does help us in deciding what to do.

**Comment by bpmct** [comment]
@dcarrion87 here's a sneak peek at the options we're adding. Open to feedback. You can also set a fraction of a day via decimals. Open to feedback though :)

![image](https://user-images.githubusercontent.com/22407953/236939785-b6641f99-472c-4264-ad0e-6456ab60f82d.png)

**Comment by dcarrion87** [comment]
This looks great thank you 🙇

**Comment by dcarrion87** [comment]
@bpmct curious is that forming part of 0.24.X or later. Just for planning our scheduled upgrades.

**Comment by dcarrion87** [comment]
@bpmct just wanted to check if this was scheduled for 0.24.x?

**Comment by dcarrion87** [comment]
Hi @Kira-Pilot @bpmct @kylecarbs 

Just wanting to get an update from anyone regarding on when this is likely to drop: https://github.com/coder/coder/issues/5815#issuecomment-1539083873

**Comment by sreya** [comment]
Hey @dcarrion87 sorry for failing to respond earlier...we're aiming to have it released in approximately 3 weeks.

**Comment by dcarrion87** [comment]
Thanks @sreya. Just to double check is this feature going to be gated by an Etnerprise licence or will it be available to everyone?

**Comment by Kira-Pilot** [comment]
Hi @dcarrion87! This feature will be available under the enterprise ->  advanced template scheduling license.

**Comment by dcarrion87** [comment]
@Kira-Pilot @bpmct I really wish you made that clear earlier on. I will need to go back to the business to determine if it's justified to go to Enterprise for this.

**Comment by dcarrion87** [comment]
> Hi @dcarrion87! This feature will be available under the enterprise -> advanced template scheduling license.

@Kira-Pilot @bpmct I really wish you made that clear earlier on. I was under the impression it was coming in the standard version given you already do auto stop in it. I will need to go back to the business to determine if it's justified to go to Enterprise for this. I'm not sure why cleaning up failure mess constitutes an Enterprise licence.

**Comment by bpmct** [comment]
@dcarrion87 We emailed you roughly 30 minutes ago with an enterprise license that is entitled to use this feature since you've been an early user of Coder v2 and gave us detailed feedback on this feature. I'll aim to do a better job communicating the feature levels of upcoming work on GitHub. Regarding _why_ this is an enterprise, we currently follow a consistent philosophy across all our features:

- Open Source: Any features that enable scale (airgap support, OIDC, VS Code Extension, templates, user roles) in an organization. It should be entirely possible for a 50-200 user deployment to use Coder assuming they have relaxed controls.
- Enterprise Edition: Any features that govern/manage scale (group sync, template permissions, browser-only, bulk actions, scheduling permissions, automated cleanup, etc). 

Our enterprise customers typically deploy Coder for use across multiple teams, have hundreds of workspaces, and naturally need ways to make it easier to operate/manage/clean up workspaces and users when they are not in use. For us, making this a feature exclusively for our enterprise customers was the right fit.

Again, this doesn't justify the lack of communication around our OSS philosophy and what to expect for upcoming features. Sorry about that!

**Comment by matifali** [comment]
@bpmct I guess this is now available under the `workspace_actions` experiment name.

**Comment by bpmct** [comment]
Yep! You can try this now with an enterprise license as long as you enable the experiment :) We'll close the issue once it's alpha!

**Comment by sreya** [comment]
Closing this since workspace actions was recently promoted to GA
