### ISSUE TITLE
CI feature: integrate pull request preview environments

### ISSUE THREAD

**Issue by waveywaves** [coder/coder#5832]
I would like to support Coder by implementing [Uffizzi](https://github.com/UffizziCloud/uffizzi) preview environments.
Disclaimer: I work on [Uffizzi](https://github.com/UffizziCloud/uffizzi).

Uffizzi is a Open Source full stack previews engine and our platform is available completely free for Coder (and all open source projects). This will provide maintainers with preview environments of every PR in the cloud, which enables faster iterations and reduces time to merge. You can see the open source repos which are currently using Uffizzi over [here](https://uffizzi.notion.site/)

Uffizzi is purpose-built for the task of previewing PRs and it integrates with your workflow to deploy preview environments in the background without any manual steps for maintainers or contributors.

We can go ahead and create an Initial PoC for you right away if you think there is value in this proposal.

**Comment by kylecarbs** [comment]
We've been hesitant to add preview environments because, historically, unintentionally, it's led to a culture of testing visually rather than thoroughly examining the code. A significant amount of our pull requests aren't tested by the individuals contributing; we communicate with code (which is nice because code is written in history).

For visual testing, we already use Storybook, and we have many integration tests. I don't think additional clicking around would yield that much benefit. I'm not opposed to trying it out, but it's not a pressing need for us right now, so if it'd be a significant effort, I'd say hold off on creating a PoC for us.
