### ISSUE TITLE
feat: custom template version naming

### ISSUE THREAD

**Issue by ericpaulsen** [coder/coder#5865]
prospective customer mentioned the following today (i am paraphrasing):

> the template version names don't provide any significance to us or our end-users. we'd like to have specific version naming conventions to make clear if a version is latest, a few behind, or very out-of-date.

**Comment by ppat** [comment]
To add further detail...

**Context**
- My team (that would maintain the remote workspace platform) would be creating the Coder templates and docker images used in them. These images would contain the baseline tools all of our engineers would need as well as following the compliance requirements.
- Users would be expected to set up a schedule that will start and stop their workspaces based on their working hours/schedule.

**UX need this issue is in response to**
- So when there is an update to the docker image or the template, what instructions should template/image maintainers provide to users so that they can identify the new template and docker image tag in the `Change Version` drop down and switch to that update?
- Ideally the user experience would enable:
  - users to opt to update their workspace at a time of their choosing (when its least disruptive).
  - maintainers can force an update to stragglers after a certain time window has elapsed.
  - maintainers can tell (through a dashboard or a manual postgres query), the adoption rate of an update (i.e. `SELECT template, image, date, count(1) FROM workspace_start_stats WHERE date > x GROUP BY template, image, date`)

**Comment by BrunoQuaresma** [comment]
About the first one in UX,  users already can update when they want. The change version option is more to be used in case you went into a broken version and want to rollback. 2 and 3 are good suggestions!

**Comment by bpmct** [comment]
We currently support custom names for template versions with 

```sh
coder templates push --name "v0.12.0"
```

We're planning on supporting messages as well to add further context:

```sh
coder templates push --name "v0.12.0" --description "upgraded to Java SE 13.0.2"
```

If you're [managing templates via CI/CD](https://coder.com/docs/v2/latest/templates/change-management) pipelines, the name could be git tag (or commit SHA) and the description could be the commit message. 

Thanks for the additional context though, we're looking into better ways to notify users when an update is available (and make sure they have the proper details on the new version). Additionally, we're looking for ways for operators to force updates.

**Comment by kylecarbs** [comment]
I believe this is fixed now!
