### ISSUE TITLE
Track template app usage

### ISSUE THREAD

**Issue by ammario** [coder/coder#5987]
Template admins want to see which of their applications are used to measure Coder adoption and understand which use cases to prioritize.

**Comment by BrunoQuaresma** [comment]
I think would be interesting to have a specific attribute like `analytics_id` when defining a Coder App in Terraform since the app ID is not the same between agents so we could use this analytics attribute to reference the same app across the deployment. 

The app has a `slug` attribute that could be used to identify the app across agents and templates but it can be unexpected for the user since the user could change that for other reasons and break how the metrics(like usage) are being calculated.

**Comment by kylecarbs** [comment]
I'm a bit confused because I think we'd want to track the usage of various apps among different agents.

Imagine a template with multiple agents: `dev` and `postgres`. `dev` is where most of my work happens. `postgres` has a simple PostgreSQL server running, so I very rarely have to access it, but it happens from time-to-time. Both have `code-server` running and are labeled as an app named `code-server`.

As a template admin, I might want to get rid of the `postgres` agent's `code-server` app for some reason. It's much easier to understand the impact if usage is separate, rather than conjoined.

---

Now if you're talking about understanding usage deployment-wide (e.g. how much VS Code is being used?), then I think a generalized `analytics_id` _might_ make more sense, but I'd rather just group by application slug in that case, because then we have an icon to display as well.

**Comment by BrunoQuaresma** [comment]
Yes, it is the second scenario that you talked about. I talked with Ammar a few minutes ago and using `slug` sounds ok for now.
