### ISSUE TITLE
Users' previous role not showing in audit logs

### ISSUE THREAD

**Issue by sharkymark** [coder/coder#6151]
Version: [`v0.17.1+4827d9e`](https://github.com/coder/coder/commit/4827d9edb81792452f1d82708778638acefc77c7)

I just changed 2 users, one was a Member, the other Template Admin, to Owner.

The audit logs do not show this.

<img width="1606" alt="image" src="https://user-images.githubusercontent.com/2022166/218096201-b8ff2db7-3ace-4709-9df6-b75b3115c193.png">

**Comment by Emyrk** [comment]
This seems to be fixed.

It might be because the UI sends an update each time you check a box. So if you uncheck the existing role, then check the new role, you get an empty previous role.

Here I unchecked each role.

![Screenshot from 2023-03-03 14-26-35](https://user-images.githubusercontent.com/5446298/222822405-4aac0aec-4800-40b2-91e5-f43154196290.png)


The `member` role is actually "no roles".
