### ISSUE TITLE
External IP address of user not captured in audit logs in EKS, even with externalTrafficPolicy set to Local

### ISSUE THREAD

**Issue by sharkymark** [coder/coder#6440]
Version: [`v0.18.1+e3a4861`](https://github.com/coder/coder/commit/e3a4861e93341ac37b58f4115dc51ce28b61feae)

My EKS `values.yaml`
![image](https://user-images.githubusercontent.com/2022166/222828828-f5de3cf6-dbf3-44a8-b000-414884c808e7.png)

A sample of the audit logs with IP starting with `192.`
![image](https://user-images.githubusercontent.com/2022166/222828877-b116b9b4-8391-4e45-ad94-e4e9e658b2ff.png)

**Comment by Kira-Pilot** [comment]
@sharkymark the logs missing the IP address are all build logs - we aren't able to capture an IP address for build logs since there isn't really a requester. I've chatted with Kyle about this and he'd said the best solution for the time being is to simply remove the IP address from the UI, which is why you see it gone in the above screenshot. I'm going to close out this issue, but if you have concerns are questions, feel free to comment in the original: #5268
