### ISSUE TITLE
bug: unable to sign in with GitHub after 0.19.2 update

### ISSUE THREAD

**Issue by matifali** [coder/coder#6573]
After the upgrade no user is able to login using GitHub

`{"message":"You aren't a member of the authorized GitHub organizations!"}`

Seems like multiple GitHub Orgs are not working as expected, using only 1 GitHub org works fine.
Previously I was setting
```shell
CODER_OAUTH2_GITHUB_ALLOWED_ORGS="org1 org2"
```
and it was working fine before updating to 0.19.2.

`CODER_OAUTH2_GITHUB_ALLOWED_ORGS="org1"` works
`CODER_OAUTH2_GITHUB_ALLOWED_ORGS="org2"` works
`CODER_OAUTH2_GITHUB_ALLOWED_ORGS="org1 org2"` both orgs can not login.

Edit:

I managed to login by joining the `org2` and setting `CODER_OAUTH2_GITHUB_ALLOWED_ORGS="org2"`

**Comment by deansheather** [comment]
@ammario bigcli regression?

**Comment by matifali** [comment]
CODER_OAUTH2_GITHUB_ALLOWED_ORGS="org1,org2" seems to work now while it was not before `0.19.2`

**Comment by ammario** [comment]
I think this happened because pflag uses CSV whereas our environment parsing uses space-separated values. I didn't realize we had different methods of accepting these string arrays. With https://github.com/coder/coder/pull/6585, we'll support either across env or flag.

**Comment by ammario** [comment]
I see in v0.18 we supported both
https://github.com/coder/coder/blob/31a37025c4de9b6a9e338bd62e9373c8da4ae487/cli/deployment/config.go#L642-L656 

I hesitate to merge https://github.com/coder/coder/pull/6585 just yet because @kylecarbs says most users did CSV, and https://github.com/coder/coder/pull/6585 would make it impossible to have spaces in your values, so this little breaking change could be worthwhile.
