### ISSUE TITLE
password requirements not clear when creating first user

### ISSUE THREAD

**Issue by ericpaulsen** [coder/coder#6666]
there is no information returned to the user regarding what is a valid, or secure password. After 5-6 attempts, a password with two special characters was successful.

<img width="436" alt="Screenshot 2023-03-19 at 7 55 32 PM" src="https://user-images.githubusercontent.com/9683576/226217839-08aabbbc-1493-4ee8-9e4b-b4ad47c8076a.png">

**Comment by bpmct** [comment]
Our current approach uses https://github.com/wagslane/go-password-validator which leverages entropy to determine whether a password is secure or not. Because of this, I'm not sure how we can change the message unless we change the way we validate passwords.

Totally get how this was confusing though, I'm not really sure how other applications that use entropy passwords have user-friendly messages. I haven't seen it in other products tbh. Related: go-password-validator#11

**Comment by bpmct** [comment]
It seems like the error message comes [from the library itself](https://github.com/wagslane/go-password-validator/blob/7bffd5ea9dacb433909a415cdc7abe22a4a53a66/validate.go#L45-L65) based on the password value. However, totally see how this wasn't helpful given that you had to do 5-6 attempts to get a secure password.

Was this a password you regularly use, or were you spinning up a ephemeral test deployment?
