### ISSUE TITLE
Can the agent update itself?

### ISSUE THREAD

**Issue by ammario** [coder/coder#6682]
Is it technically feasible for the agent to update itself when the coder server updates? Pulling the new binary is easy enough, but will the Go runtime play along on an `exec`?

cc @mafredri — seems like the kind of thing that would be interesting to you.

**Comment by bpmct** [comment]
Related: coder/coder#6229

**Comment by mafredri** [comment]
This is indeed something that’s been on my mind.

First off, do we want this to be an automatic or manual process? The former is somewhat problematic (explained below), whereas the latter makes it fine if we explain what will happen.

We could easily enough exec into the updated binary, but the downside is we terminate all connections and processes (in part because of in-memory networking). So this is close to a restart, but skips the terraform step. It should be possible to leave non-SSH processes running, but not sure if that’s a good idea or not. On Windows we wouldn’t exec per-se, but similar behavior should be doable.

Other questions arise too, like should we (re-)run the shutdown/startup script?

My ideal would be for SSH connections to be serviced by forked processes (old agent) that we leave after us as we update to the new one, similar to what OpenSSH does, but not sure if it’s feasible, especially with the in-memory networking.

There are some more alternatives, but they all feel too hacky to mention.

A few more (loosely) related issues:
- https://github.com/coder/coder/issues/5432
- https://github.com/coder/coder/issues/6177
