### ISSUE TITLE
`mutagen` doesn't work - unable to dial agent endpoint - `chmod +x` resolves it

### ISSUE THREAD

**Issue by sharkymark** [coder/coder#6685]
Connecting with `mutagen` from a local machine to a Coder workspace does not work.

Error message:

Connecting to agent (POSIX)...
Error: unable to connect to beta: unable to connect to endpoint: unable to dial agent endpoint: unable to handshake with agent process: unable to receive server magic number: EOF (error output: Connection timed out during banner exchange)

I was able to reproduce this - from a Macbook Pro to a Coder deployment. Another Coder employee using a Linux local machine, did not experience this.

A clever user of Coder has a work-around if others experience this where they have to `chmod +x` the Mutagen binary that gets copied over to the Coder workspace home directory quickly before Mutagen tries to execute it:

```sh
# From the Coder workspace home director
while true; do chmod +x .mutagen-*; done
```

**Comment by mafredri** [comment]
Oof, this issue is pretty old and breaking basic functionality. I'm pretty sure it's a bug in the `sftp` library we use, I can take a look this week, I think it'll be an easy fix.

The other factor here is that `mutagen` isn't explicitly changing permissions on the copied binary, but instead relying on default behavior (which _should_ be to retain the permission of the file being copied).
