### ISSUE TITLE
Installing Coder with .tgz file is crashing the pod

### ISSUE THREAD

**Issue by vl00920760** [coder/coder#6723]
Hi,
When I am installing coder other than latest version using command  :
$helm install coder ./coder_helm_0.13.2.tgz --namespace coder --values values.yaml

the pod gets crash. This is not the case with the command given in coder v2 documentation, that works fine.

If I follow documentation, there is no such command mentioned if you want to install any lower version of coder. 
Please note - Postgres db is on the same Kubernetes cluster.

Thanks,
Vivek

**Comment by kylecarbs** [comment]
Can you fetch the pod logs of a crashed instance for me?

**Comment by vl00920760** [comment]
ubuntu@hopserver1:~/vivek$ kubectl logs coder-9f7ccdc47-r7dlh -n coder
Started HTTP listener at http://0.0.0.0:8080/

 

View the Web UI: http://144.24.222.45/
connect to postgres: ping postgres: dial tcp: lookup postgres on 10.96.5.5:53: no such host
Run 'coder server --help' for usage.

**Comment by bpmct** [comment]
Hi @vl00920760 are you still running into this?

**Comment by dlemfh** [comment]
I'm currently facing the exact same issue..

We deploy coder to kubernetes using the helm chart,

and whenever I try to downgrade the coder version using a different helm chart version,
the coder daemon pod fails with a message like:

```
connect to postgres: migrate up: up: no migration found for version 120: read down for version 120 .: file does not exist
```

This was the message for downgrading from 0.23.0 to 0.22.2.
But other version downgrades all fail with similar logs (just with different migration versions).

Do you think it might be because older versions of the coder daemon docker image, do not have future migrations files, so they are unable to migrate down the postgres schema?

**Comment by matifali** [comment]
Hi @dlemfh Coder doesn't recommend and officially supports downgrading.

**Comment by dlemfh** [comment]
Thanks for the heads up!

If the down migrations are the reason for not supporting downgrades (as is my guess),
maybe the helm chart could add the following parts:

1. an initContainer that always uses the latest coder image, and copies the migration files to a volume
2. the main coderd container will mount said volume to its migrations directory, so that future migration files exist and can be used to downgrade the db

**Comment by jtmitchell** [comment]
I am seeing the same problem, but not in relation to downgrades. 
Instead, I see this problem when a new release is made - eventually (overnight when I'm not looking at it...) my pod will go into a crash loop with an error suggesting migration files. 

I have a [query about this on the Discord](https://discord.com/channels/747933592273027093/1128081141019193475)
My main issue is I don't understand why my installation knows anything about the new release...

`View the Web UI: https://coder.support.dev.aportio.net
2023-07-23 21:28:34.511 [warn]  coder will not check email_verified for OIDC logins
running command "coder server": connect to postgres:                                          
    github.com/coder/coder/cli.(*RootCmd).Server.func1                                        
        /home/runner/actions-runner/_work/coder/coder/cli/server.go:611                       
  - migrate up:                                                                               
    github.com/coder/coder/cli.connectToPostgres                                              
        /home/runner/actions-runner/_work/coder/coder/cli/server.go:1873                      
  - up:                                                                                       
    github.com/coder/coder/coderd/database/migrations.Up                                      
        /home/runner/actions-runner/_work/coder/coder/coderd/database/migrations/migrate.go:81
  - no migration found for version 140: read down for version 140 .: file does not exist`
