### ISSUE TITLE
ask: OIDC + `--disable-password-auth` how make OIDC user owner

### ISSUE THREAD

**Issue by smndtrl** [coder/coder#6729]
From reading the docs I'm not 100% sure what the expectation should be for disabling password auth.

1. Started the coder with `--disable-password-auth`
2. Visited webinterface, got redirected to /setup, had to create a user, didn't get logged in
3. Browsed to /login, only OIDC possible

What should be the way to proceed at giving my first OIDC user "owner" permissions as the initial user is now unable to use the webinterface.

**Comment by matifali** [comment]
cc: @bpmct this is worth considering.

**Comment by bpmct** [comment]
👋🏼 You'll need to remove the `--disable-password-auth` flag temporarily from the server, log in as the built-in user, and set the OIDC user as an Owner. If you never had an admin user, you can use this command to create one:

```sh
coder server create-admin-user
```

After that, log in, set the OIDC user as an owner, and then re-run the server with the flag.

A bit manual, I know, but this is how other platforms typically handle the same kind of thing. We don't plan on improving this experience since it's a one-time thing and a bit niche. Sorry! 

Feel free to open other issues if you have any more feedback.
