### ISSUE TITLE
bug: workspace screen not loading

### ISSUE THREAD

**Issue by matifali** [coder/coder#6807]
https://user-images.githubusercontent.com/10648092/227963320-48e2f62f-0f3b-4f63-8917-355ebb151a12.mp4

Do you see how I cannot launch the workspace on the first click? This happens if another workspace is stopping or starting.

@BrunoQuaresma

**Comment by BrunoQuaresma** [comment]
Thanks for sharing this!

**Comment by jsjoeio** [comment]
Running into this as well.

**Comment by matifali** [comment]
@BrunoQuaresma, I am unable to access my workspace now. Watch the screen recording.

https://user-images.githubusercontent.com/10648092/228171031-41310dca-af18-4d2b-a571-41cbfa31279b.mp4

**Comment by johnstcn** [comment]
Root cause was that the WorkspacePage component was hitting `/authcheck` with the following payload:

```
{"checks":{"readPagePermissions":{"object":{"resource_type":"workspace"},"action":"read"}}}
```

This equates to asking "Can I read _all_ workspaces?", which will not be true for a "Member".

The following payload returns `{"readPagePermissions": true}":

```
{"checks":{"readPagePermissions":{"object":{"resource_type":"workspace", "resource_id": "$VALID_WORKSPACE_ID_OWNED_BY_REQUESTOR"},"action":"read"}}}
```

This came from the following:

```
  const { data: permissions, isLoading: isLoadingPermissions } =
    useReadPagePermissions("workspace", workspace?.id)
```

As we're in the process of fetching the workspace by owner and name, we don't necessarily have the workspace ID available in the current context.

For the moment, I reverted the commit.

**Comment by johnstcn** [comment]
Needs a release
