### ISSUE TITLE
Do not run terraform plan while importing a starter template

### ISSUE THREAD

**Issue by matifali** [coder/coder#6860]
# Issue
I set up a coder deployment and wanted to use a remote docker daemon for some quick testing. First thing came to mind is to use the docker starter template and then edit the docker host to my remote host ip.

# Expectation
Template should import successfully and then let me edit the files and make required changes. Then build and publish.

# Actual Behavior
![image](https://user-images.githubusercontent.com/10648092/228481245-24ec8658-d146-4673-9e72-c93feb1fe894.png)

```console
Initializing the backend...
Initializing provider plugins...
- Finding coder/coder versions matching "~> 0.6.17"...
- Finding kreuzwerker/docker versions matching "~> 3.0.1"...
- Installing coder/coder v0.6.21...
- Installed coder/coder v0.6.21 (signed by a HashiCorp partner, key ID 93C75807601AA0EC)
- Installing kreuzwerker/docker v3.0.2...
- Installed kreuzwerker/docker v3.0.2 (self-signed, key ID BD080C4571C6104C)
Partner and community providers are signed by their developers.
If you'd like to know more about provider signing, you can read about it here:
https://www.terraform.io/docs/cli/plugins/signing.html
Terraform has created a lock file .terraform.lock.hcl to record the provider
selections it made above. Include this file in your version control repository
so that Terraform can guarantee to make the same selections by default when
you run "terraform init" in the future.
Terraform has been successfully initialized!
You may now begin working with Terraform. Try running "terraform plan" to see
any changes that are required for your infrastructure. All Terraform commands
should now work.
If you ever set or change modules or backend configuration for Terraform,
rerun this command to reinitialize your working directory. If you forget, other
commands will detect it and remind you to do so if necessary.
Terraform 1.3.4
data.coder_provisioner.me: Refreshing...
data.coder_workspace.me: Refreshing...
data.coder_workspace.me: Refresh complete after 0s [id=93691226-0442-4c91-8f13-9e7e10a59aee]
data.coder_provisioner.me: Refresh complete after 0s [id=0fed0777-b0b8-4b3a-88c6-e901f2575d73]
Error: Error pinging Docker server: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
on main.tf line 21, in provider "docker":
  21: provider "docker" {

```

# Suggestion

Do not run terraform plan while importing a starter template and let the user edit the files first. Wait until the user press Build button.

May this can be made default behaviour after #5573 GA.

@bpmct @BrunoQuaresma @ammario

**Comment by matifali** [comment]
In my opinion this error with a startup template is not a good thing considering we are exploring use cases such as,
1. Fly.io #6446 
2. Render.com #6841 
3. Railway.app #6861

**Comment by sharkymark** [comment]
Can we update the starter templates with Terraform variables like Kubernetes to prompt the template admin first for things like Docker daemon socket?

<img width="1342" alt="image" src="https://user-images.githubusercontent.com/2022166/228528143-d0e062dd-3019-456e-bd45-30149fe88551.png">

**Comment by matifali** [comment]
This is a good suggestion but a docker daemon can be specified by difrent ways,
1. As a `coder_parameter` 
A single typed value.
```terraform
data "coder_parameter" "docker-daemon" {
  name        = "Docker daemon"
  description = "Docker daemon to use
  type        = "string"
  default     = "tcp://12.23.45.67:2375"
}
``` 
or with options

```terraform
data "coder_parameter" "docker-daemon" {
  name        = "Docker daemon"
  description = "Docker daemon to use"
  type        = "string"
  default     = "unix:///var/run/docker.sock" 
  option {
    name        = "Local Linux"
    description = "Local Docker daemon"
    value       = "unix:///var/run/docker.sock"
  }
  option {
    name        = "Remote Linux"
    description = "Remote Linux Docker daemon"
    value       = "tcp://12.23.45.67:2375"
  }
  option {
    name        = "Remote Windows"
    description = "Remote Windows Docker daemon"
    value       = "tcp://12.23.45.68:2375"
  }
}
``` 


it can also be directly typed in the `main.tf` file, e.g.,
```terraform
provider "docker" {
	host = tcp://12.23.45.67:2375
}
```
My use case is 2nd. and I prefer to be able to edit the file before deploying.

**Comment by matifali** [comment]
@bpmct what is your opinion on this?

**Comment by bpmct** [comment]
I see. You are trying to make a new template from only the Ui, but have no way to get into the editor because you have no local Docker host.

Starter (or the add template) templates weren't designed in mind for the template editor. To support this, I suggest we rethink our flow.

1. Add a bare starter template, uses copy/paste from other examples. Fun fact: [we used to have this](https://github.com/coder/coder/blob/bec4adfc0c8e5f1a66d5264789be1936df475100/examples/templates/bare/main.tf)
2. We add a button/checkbox to skip validation/plan when importing starter templates
3. There is a way to enter the template editor without having a template/version yet and create a template from there
  - When empty, there is some way to import a starter into the editor, client-side. The plan fails, but that is OK. There is no version yet.

3 seems like the best option to me. I've always been a bit confused by this `.tar` upload, I would much prefer an option to create a template with no versions and enter the editor (perhaps with tar upload still)

<img width="509" alt="Screenshot 2023-04-04 at 2 34 38 PM" src="https://user-images.githubusercontent.com/22407953/229900775-15ffc44e-0196-41d9-9af2-1b256bc26976.png">

3 also seems like it would require some rework. I'd happily accept a modern PR for a bare template to get this use case unblocked, but it feels clunky long-term since you still need to copy & paste from the template editor.

**Comment by bpmct** [comment]
I don't think Coder should always skip Terraform plan. As much as possible, we'd like to help users configure their environment property during template creation (e.g. add proper tokens, configure host, etc).

**Comment by matifali** [comment]
Let's start with an empty template in the template editor, as now we can also create folders. So it is self-sufficient.
Something like adding a button **[New Tempplate]** on the stater template that lets you start from scratch.

**Comment by BrunoQuaresma** [comment]
@kylecarbs Is it possible right now to skip terraform plan when creating a template? Wondering if this only should be required when “activating” it.

**Comment by kylecarbs** [comment]
No, because otherwise we wouldn't know of the resources it'd create, or the parameters it exposes.
