### ISSUE TITLE
docs engine: search results prioritize API and CLI calls too much

### ISSUE THREAD

**Issue by bpmct** [coder/coder#6968]
When I search, "Audit" or "License," I see the autogenerated CLI/REST API docs instead of the dedicated page. We use algolia for our dedicated search. Is there a way to change the weights?

![Screenshot 2023-04-03 at 7 40 19 AM](https://user-images.githubusercontent.com/22407953/229512189-230ab26b-0e3c-419a-a25d-c1c49d27195d.png)

**Comment by BrunoQuaresma** [comment]
I think so. I will take a look at this today or tomorrow.

**Comment by BrunoQuaresma** [comment]
Fixed.

- Changed the scrape order to fetch first the API and CLI pages and set the page rank to 1. They need to be done first because scrapped pages are not overridden from the other start_urls. 
- In the index settings UI, I moved the page_rank to be the first element to be considered in the ranking.

<img width="738" alt="Screen Shot 2023-04-03 at 11 49 28" src="https://user-images.githubusercontent.com/3165839/229545944-a4b21993-b6c9-4cf5-a3cb-483ec5e3bcd4.png">
