### ISSUE TITLE
make the `startup_script` logs collapsed by default. 

### ISSUE THREAD

**Issue by matifali** [coder/coder#6997]
![image](https://user-images.githubusercontent.com/10648092/229705251-339e508b-18fe-4eb5-9d6e-f10332d22029.png)

**Comment by roshvin** [comment]
Hi @matifali could you pls suggest how you are displaying resource usage in workspace . example RAM usage in your screenshot.

**Comment by matifali** [comment]
Related to #6997

**Comment by matifali** [comment]
> Hi @matifali could you pls suggest how you are displaying resource usage in workspace . example RAM usage in your screenshot.

Please check https://coder.com/docs/v2/latest/templates/agent-metadata

**Comment by BrunoQuaresma** [comment]
IMO I think this should be open/visible when it is starting

**Comment by matifali** [comment]
Lets close this if Ben thinks the same.

**Comment by bpmct** [comment]
Yeah, it should stay open when starting. An admin could write logs to a file (or just `/dev/null` and add simplified logs instead). This should automatically close once the workspace starts.

**Comment by sharkymark** [comment]
@bpmct @matifali a large prospect reported this as a security concern, having potential tokens and secrets scrolling across the screen. I think it should be hidden or better configurable to be open or shown.

**Comment by matifali** [comment]
@BrunoQuaresma a 2nd thought on making it configurable. My suggestion is to keep it there but just collapsed. It may be configured to entirely remove this too if there are secrets leaking etc.

**Comment by BrunoQuaresma** [comment]
1. About the security concern, I think we should recommend to the user to not log secrets(this is kinda a "best" practice) because only hiding it on the UI does not solve the problem because the logs can still be accessed from the workspace.
2. I think adding a config is ok, but I would avoid adding too much UI configuration because can make it hard to document all the options and keep them up to date.
