### ISSUE TITLE
Agent taking too long to start warning

### ISSUE THREAD

**Issue by matifali** [coder/coder#6999]
I keep seeing this warning while the startup script runs successfully and there are no obvious issues.

![image](https://user-images.githubusercontent.com/10648092/229706650-55062883-58ae-4d05-93b7-61c1cb6d21c3.png)

**Comment by ammario** [comment]
I'm guessing this is because your startup script isn't exiting. We have no way of knowing whether the script is hung intentionally or not. Since we don't want to store arbitrarily large logs in the database, all startup scripts should terminate after basic installation and setup is complete.

If you want to start a long-running process (such as code-server) the best practice is to fork it off, (e.g. `code-server &`).

We should also consider not showing this error if the agent is blocked on running the startup script. Even startup scripts that eventually terminate can take any amount and we're in no position to determine what's reasonable.

**Comment by matifali** [comment]
I am already terminating all long running commands in my `startup_script` with `&`.

**Comment by ElliotG** [comment]
@ammario can this timer be configured at the template level? An override where we could say like "10 min" vs "20 min" expected boot?

**Comment by ammario** [comment]
It could... I'm opposed to adding more configuration unless people really want it.

**Comment by matifali** [comment]
To add more info. My startup script finishes in less than 30 seconds.

**Comment by matifali** [comment]
After updating the startup script as per https://coder.com/docs/v2/latest/templates#startup_script the issue is resolved.
