### ISSUE TITLE
Expose agent metadata through Prometheus

### ISSUE THREAD

**Issue by mtojek** [coder/coder#7012]
Coder is streaming metadata via `watch-metadata` just by querying the database, thus I suspect that it should be also possible to emit it also via the Prometheus endpoint.

The only difficulty might be format conversion. For example: `28%` -> `0.28f`, `1.24` -> `1.24f`, `<word of the day>` -> nope.

@bpmct Let me know if we should pull it under the [milestone](https://github.com/coder/coder/milestone/15).

**Comment by bpmct** [comment]
Yeah, let's put it in there. It might make sense to have an actual value versus presentation value, thoughts @ammario?

**Comment by mtojek** [comment]
> Another difficulty is avoiding counting these data multiple times when there are multiple Coderd instances. 

Isn't it a design problem with all our metric collectors? Is it possible that Coderd instances are behind a common load balancer, so we can say that agents are roaming?

> you'll get each agent metadata time series repeated for each Coderd. This is bad news if you want to, say, compute a sum over agents.

I'm not sure if there is a good solution. A Coderd instance could keep metadata metrics collected _only from connected agents_ in memory, and expose it via the Prometheus endpoint.  Do you think that this will work or should we try a different approach?

**Comment by spikecurtis** [comment]
Storing metrics in memory and publishing from connected agents is the approach we took in v1.  I don't think many customers are scraping Prometheus, so we don't have much operational experience with it outside scale testing, but it seems to be working fine.  However, we published them over a websocket, so the metric updates were "sticky" to a single Coderd.

In v2, I think it's a normal HTTP POST, so you could imagine the receiving coderd changes each metric update cycle. I don't think Prometheus will handle this situation well if the coderd that fielded the request publishes and then stops publishing.

@bpmct I think we need to take a step back and think about why we we want to publish these metrics over Prometheus in the first place.

The main reason I can think of is so that operators can build dashboards that include stuff like workspace CPU utilization, memory, etc.  The following commentary is based on this assumption, so please disabuse me of it if that's not why we're doing this.

For the operator dashboard use case, I think accurate statistics like sums is a hard requirement.

One thing to say, tho, is that most infrastructure platforms that operators might use for Coder workspaces already collect CPU, memory, network IO, etc.  Kubernetes can be straightforwardly configured to give pod-level metrics, AWS has CloudWatch, etc.  So, just getting aggregate utilization and performance metrics from workspaces is possible without this.  Many of our v1 customers show us dashboards they have built for this purpose without our help.

Another observation is that if customers are interested in Agent-collected metrics that can't easily be accessed by their infrastructure tools (like, I dunno, maybe they find a way to get time-in-IDE or something), these metrics are stored in Postgres, and so they could just query them (Grafana, for example, supports querying postgres), or use standard tooling to mirror those tables to some data warehouse or whatever.  One thing customers might find annoying about this is that values are strings, and for dashboarding they probably want numeric data.  We could introduce the ability to parse agent metadata into numeric format and store it in postgres to make this easier for people.

**Comment by spikecurtis** [comment]
> contemplating whether we should prioritize the development of an official integration between Coder agent and Datadog/Elastic?

I prefer generic tooling over targeting specific monitoring stacks, unless we have a very strong reason to do so.

**Comment by bpmct** [comment]
For accurate info, customers should use Kubernetes' Metrics Server or other purpose-built monitoring tools to measure resource utilization across all developers' workspaces. 

I assume the operator would want to use agent metadata+prometheus to collect some unique values that are better collected within the workspace (# of jobs running). However, I don't have any concrete use cases. Open to ideas!

> @bpmct Let me know if we should pull it under the [milestone(https://github.com/coder/coder/milestone/15).

Let's hold off until #8038 (better ways to understand the type/format of metadata) + perhaps we come across more use cases from our users, or by our own use of Coder.

@spikecurtis - would you be able to create an issue for pushing metrics across multiple replicas? I'm not sure I fully understand it, but it seems like something we should understand/investigate/fix now. Would this just be the case for agent metadata or would it come up if we exposed other agent stats to Prometheus (e.g. agent->coderd latency)? I believe we are doing some of this today

**Comment by spikecurtis** [comment]
Raised https://github.com/coder/coder/issues/8120 to track the problems with existing metrics @bpmct

**Comment by mtojek** [comment]
Closing in favor of https://github.com/coder/coder/issues/8120
