### ISSUE TITLE
Let template author change values while playing with the Editor

### ISSUE THREAD

**Issue by BrunoQuaresma** [coder/coder#7153]
After publishing a new template version the user is redirected to the template page. We may want to add an option "Keep on editor" to keep the user on the current editor page so they can keep playing with the template.

**Comment by aslilac** [comment]
I've kind of got a couple of ideas around this...

- we could add a checkbox (next to the existing "Promote to default version" checkbox) that might say "Navigate to template summary"
  - is that a clear enough description to the average user?
  - would it be checked or unchecked by default?
- do we add another button that publishes, but without navigating? how do we explain their effects concisely and clearly?
  - "Publish" and "Publish and Exit"? "Publish" and "Publish and continue editing"?
- or...
  - we could just make it so that publishing no longer navigates you
  - and we make the template title clickable in the editor, and have that navigate you to the summary if you really want to go there. my hunch is that no one is

that third option is definitely what I'm in favor of. keeps things simple, while hopefully smoothing out the workflow for some people without breaking it for anyone else.

@BrunoQuaresma feel free to flag other people for attention on this. heading out for the night but I'll pick it back up tomorrow.

**Comment by BrunoQuaresma** [comment]
I like more the third option! Thank you for sharing many ways of solving the problem
