### ISSUE TITLE
Customer facing documentation plan for RBAC

### ISSUE THREAD

**Issue by misskniss** [coder/coder#724]
**Acceptance Criteria**
RBAC should be clearly documented in our public facing v2 docs. It should cover what it does and does not do. How to make use of the functionality, etc. 

- Template creation
- Template permissions for provisioning
- membership in orgs
- ?
- ?

**Comment by Emyrk** [comment]
@misskniss what are you thinking for this. Something like: https://coder.com/docs/coder/latest/admin/access-control/organizations#organization-manager-permissions?

I'm not sure where we'd place this :thinking:

**Comment by tjcran** [comment]
> @misskniss what are you thinking for this. Something like: https://coder.com/docs/coder/latest/admin/access-control/organizations#organization-manager-permissions?
> 
> I'm not sure where we'd place this 🤔

You and I should discord soon and just talk through it. I don't think this issue belongs on the community plan because this is just a placeholder for figuring out what our plan is for having RBAC in the docs. this isn't any different than any other product docs we'll need IMO. I'm also tempted to just say let's close this issue altogether because i don't remember why we opened this one as an individual issue.
