### ISSUE TITLE
bug: daily active users modal in Deployment tab is incorrect

### ISSUE THREAD

**Issue by ericpaulsen** [coder/coder#7275]
customer daily active user count showed 16 on Sunday, which was incorrect, since no users had logged in. the figure was likely off by a day, since it showed 0 for the previous day, Saturday.

**Comment by Emyrk** [comment]
This might be a UTC vs local timezone thing. I will look into it.

**Comment by Emyrk** [comment]
I hope to come back to this. If anyone else wants to, then can fix this.

Pretty sure it is a UTC vs local timezone issue. We use UTC on the backend to generate these buckets.

**Comment by Emyrk** [comment]
The issue is that the metricscache does the counting calculation on UTC dates and exposes this cached value.

See the counting here:
https://github.com/coder/coder/blob/84fb50b42449590de50865df56ec722575d6f8d5/coderd/metricscache/metricscache.go#L138-L142

And UTC dates here: https://github.com/coder/coder/blob/84fb50b42449590de50865df56ec722575d6f8d5/coderd/database/queries/workspaceagentstats.sql#L41-L41

A possible solution is to calculate 24 cached values, one for each major timezone (I am aware timezones get weird and there are more).

The caller can then decide which one to use based on the closest value. Thoughts?

**Comment by Emyrk** [comment]
Just realized the postgres does a `group by` on the UTC date to remove duplicates. So we cannot return the raw date from the sql, or else we could be returning a large amount of rows.

Hmm :thinking:

**Comment by bpmct** [comment]
I'm going to reopen this until we change the frontend to show the proper values based on the user's timezone. There is a backend fix, but it's not really obvious/accessible for the user.
