### ISSUE TITLE
Local provisioners don't seem to use Terraform cache 

### ISSUE THREAD

**Issue by bpmct** [coder/coder#7316]
A customer reported that the Terraform plugins will download every time. This isn't a huge deal, but increases builds from ~2 seconds to ~8 seconds

![image](https://user-images.githubusercontent.com/22407953/234997248-487cca00-f055-4048-bf8a-f232c0f94717.png)

**Comment by coadler** [comment]
This is mostly fixed by https://github.com/coder/coder/pull/7604, but requires some extra work. Before uploading your template, make sure you have a `.terraform.lock.hcl` file in your template folder. If not, just run `terraform init`. After pushing a new version with the lock file, providers should be cached as normal.
