### ISSUE TITLE
workspace actions: add new status badge to workspaces table

### ISSUE THREAD

**Issue by Kira-Pilot** [coder/coder#7349]
- add a new 'Impending deletion' badge to the workspaces page
 - hide behind feature flag #7354

### Background

Case: Workspace is failed but not stopped
Badge solution: make use of existing 'Failed' status badge

Case: Workspace is inactive and scheduled for deletion within 2 weeks' time
Badge solution: If in 14 days or less the workspace will be deleted, any status badge is replaced with a 'Impending deletion' status badge

**Comment by bpmct** [comment]
Should "impending deletion" workspaces show toward the top of the list? I'm thinking of a case where a user has 25 workspaces, and they do not notice that the workspaces at the bottom (since they are inactive) are scheduled for deletion.

As I understand it, this is the only visual indicator on the dashboard that the workspace is impending deletion? That is, unless they directly navigate to the workspace page.

**Comment by bpmct** [comment]
> If this doesn't seem noticeable enough, we could also add a dismissible banner to the top of the /workspaces page: "You have workspaces that will be deleted soon. Use this filter to see them." or something similar.
> 
> Let me know what you'd prefer!

This seems like the best option IMO. I am curious about the dismiss behavior.

Would the "dismiss" be per-session, or stored in localStorage or something? If another workspace is scheduled, would the old dismiss be invalidated? I'd be concerned about A) it showing up all the time and B) it not showing up when another workspace is scheduled, that the owner may not have reviewed.

**Comment by Kira-Pilot** [comment]
> Would the "dismiss" be per-session, or stored in localStorage or something? 

Yes, per session and stored in local storage as a list of workspaces to be deleted.

> If another workspace is scheduled, would the old dismiss be invalidated?

Correct, we would invalidate local storage if the list was out of date.
