### ISSUE TITLE
Clear all auth cookies before auth-redirect

### ISSUE THREAD

**Issue by deansheather** [coder/coder#7363]
If you have duplicate auth cookies (and one is invalid/expired) you may get into an infinite redirect loop.

**Comment by Emyrk** [comment]
Without being able to reproduce this, this cannot be solved.

The only way to have duplicate cookies is if the location of the cookies is on different domains or different paths. If this is the case, then to delete the cookie, a new cookie must be issued on that same domain/path. 

This information is not included in a client request, only the value of the cookie is.

So if the user has 2 cookies, and we delete the one on `/`, this will only "fix it" until a new cookie is issued on `/` (login).

This means the only way to fix it on the server side is to find where the duplicate cookie is being added, and fix the logic there. Without being able to reproduce, or know which cookie was the culprit, this becomes very difficult to begin to fix.

Given this bug was reported during the early experimental days, I am going to close this. If it happens again, we can open a new issue with more information.
