### ISSUE TITLE
Connection stalls with coder ssh connections

### ISSUE THREAD

**Issue by janLo** [coder/coder#7388]
I'm experiencing connection stalls if I use coder ssh connections. 

- Coder is running as HA-Setup with a HA-Proxy as Loadbalancer. 
- The coder instances/LB is on the same layer2 domain as the target for the workspace.
- The workspace is a Sysbox container (via docker) on a bare metal machine
- No stalls can be observed if using SSH directly from the client to any of the machines

The following screencast is the stalled connection:
![stall](https://user-images.githubusercontent.com/96146/235925326-90956491-390f-42eb-9a66-c898f3c5b63a.gif)

If there is no stall it should look like this (ws-6 is the machine the workspace is running on):
![no-stall](https://user-images.githubusercontent.com/96146/235925469-5b80d258-12a0-4a34-af0a-03e815425330.gif)

As requested by @spikecurtis this is the output of `coder -v speedtest your-workspace -t 60s`:
[speedtest.log](https://github.com/coder/coder/files/11382845/speedtest.log)

**Comment by janLo** [comment]
If I run the same speedtest on a machine on the same L2 network as coder and the workspace target I also see stalls - even though less often (this is 120 sec):
[speedtest.log](https://github.com/coder/coder/files/11383092/speedtest.log)
[speedtest-1.log](https://github.com/coder/coder/files/11383094/speedtest-1.log)

Even if I add `-d` it sees these stalls:
[speedtest-direct.log](https://github.com/coder/coder/files/11383140/speedtest-direct.log)

On the WS agent side I see a lot of these, I don't know if its related:

```
2023-05-03 13:47:52.469 [DEBUG] (tailnet.wgengine) <./../../../tailscale.com/wgengine/wglog/wglog.go:81> NewLogger.func1 wg: [v2] [ciway] - Handshake did not complete after 5 seconds, retrying (try 6)
2023-05-03 13:47:52.469 [DEBUG] (tailnet.wgengine) <./../../../tailscale.com/wgengine/wglog/wglog.go:81> NewLogger.func1 wg: [v2] [ciway] - Sending handshake initiation
2023-05-03 13:47:52.692 [DEBUG] (tailnet.wgengine) <./../../../tailscale.com/wgengine/wglog/wglog.go:81> NewLogger.func1 wg: [v2] [DvYd+] - Handshake did not complete after 5 seconds, retrying (try 12)
2023-05-03 13:47:52.692 [DEBUG] (tailnet.wgengine) <./../../../tailscale.com/wgengine/wglog/wglog.go:81> NewLogger.func1 wg: [v2] [DvYd+] - Sending handshake initiation
2023-05-03 13:47:57.538 [DEBUG] (tailnet.wgengine) <./../../../tailscale.com/wgengine/wglog/wglog.go:81> NewLogger.func1 wg: [v2] [ciway] - Handshake did not complete after 5 seconds, retrying (try 7)
2023-05-03 13:47:57.539 [DEBUG] (tailnet.wgengine) <./../../../tailscale.com/wgengine/wglog/wglog.go:81> NewLogger.func1 wg: [v2] [ciway] - Sending handshake initiation
2023-05-03 13:47:57.741 [DEBUG] (tailnet.wgengine) <./../../../tailscale.com/wgengine/wglog/wglog.go:81> NewLogger.func1 wg: [v2] [DvYd+] - Handshake did not complete after 5 seconds, retrying (try 13)
2023-05-03 13:47:57.741 [DEBUG] (tailnet.wgengine) <./../../../tailscale.com/wgengine/wglog/wglog.go:81> NewLogger.func1 wg: [v2] [DvYd+] - Sending handshake initiation
```

**Comment by bpmct** [comment]
Thanks for reporting, we'll take a look

**Comment by janLo** [comment]
As requested via discors, the log from `coder ping -v`.

This is the one from the clinet machine:
[ping-v-from-client.log](https://github.com/coder/coder/files/11390810/ping-v-from-client.log)

This is the one from the machine on the same L2 network as the coder infra:
[ping-v-from-server.log](https://github.com/coder/coder/files/11390811/ping-v-from-server.log)

**Comment by coadler** [comment]
The issue seems to be here:
```
2023-05-03 19:59:04.323 [DEBUG]	(wgengine)	<./../../../tailscale.com/wgengine/magicsock/magicsock.go:2759>	(*Conn).logEndpointChange	magicsock: endpoints changed: 172.18.159.2:48252 (stun)
```
In the client ping, it's only able to discover an external ip of `172.18.159.2`. Could you provide some more info of the network setup that the client is running in?

**Comment by janLo** [comment]
This is basically the current setup.

![image](https://user-images.githubusercontent.com/96146/236048711-edb9a2e8-0025-431e-a07f-d208879a5a5e.png)

`172.18.159.2` is the "client" machine. But I also see the stalls from the "server" machine (the machine located in the same L2 domain as the rest of the coder infra).

**Comment by coadler** [comment]
Sorry, I was focusing more on being unable to p2p from the client first. @mafredri has been looking into connection stalls as of recent which sounds similar to your issue.

As for getting p2p working, you'll have to allow UDP to flow between the two networks. The host and client will need to be able to send UDP packets directly to each other, otherwise DERP will be necessary.

**Comment by janLo** [comment]
No worries!

I'm aware of the udp issues between the two networks - but this is something I can live with for now as it's a policy issue. The stalls are a problem though. I just ran out of ideas how to debug this further.

**Comment by janLo** [comment]
> @mafredri has been looking into connection stalls as of recent which sounds similar to your issue.


You mean #7262 ?

**Comment by coadler** [comment]
Yep, I believe so!

**Comment by bpmct** [comment]
Hey @janLo - just a small update. We're still investigating this. We'll keep you posted.

**Comment by janLo** [comment]
@bpmct thank you for the update and your efforts. I'm following the related issues with great interest. 🤞

**Comment by mtojek** [comment]
@bpmct Do you think that we can bake a release to ship the [workaround](https://github.com/coder/coder/pull/7500)? I'm not 100% convinced that it helps, but the overall situation shouldn't get worse.

If so, would you mind triggering the release workflow?

**Comment by janLo** [comment]
@mtojek just to add some feedback: the 0.23.3 release hasn't changed the situation on our end.

**Comment by mtojek** [comment]
@janLo Sorry to hear that, Jan. Just double-checking: did you restart workspaces, so that agents were updated? If it doesn't help much, then we may need to wait for the proper fix in https://github.com/google/gvisor/issues/6113.

It is interesting that we stopped observing PTY timeouts in our [flaky issues](https://github.com/coder/coder/commits/main).

**Comment by janLo** [comment]
I've restarted the workspace, and I've just double-checked that all components are on 0.23.3.

**Comment by spikecurtis** [comment]
I've been investigating, and it seems like there are multiple overlapping issues.

---

The first, and possibly most important issue, where we see connection stalls for ~15 seconds, is that we don't wait for the wireguard layer to have established a connection to the peer before starting the TCP handshake.  If the first wireguard handshake fails, it waits 5 seconds to retry, meaning the TCP SYN, SYN-ACK round trip takes 5+ seconds.

TCP specs call for setting the initial retry timeout (RTO) to 3x the first round trip measurement, leading to a 15s RTO.  The RTO is the "backstop" of TCP recovery from lost packets.  There are algorithms that attempt to do fast retransmissions, but they don't work in all cases, so you always have the RTO to fall back on.  But, with a ~15s RTO, this can stall the connection for a long time.

The RTO is gradually adjusted as additional round-trip measurements are made, but it can only change slowly, on the order of the initial RTT, so if fast recovery schemes fail early in the connection, you'll hit the stall.

---

A second issue I've observed is that the TCP sender pushes several hundred kiB of data that's "in flight" in the network between the time that a dropped packet is observed at the receiver and the notification is delivered to the sender.  This data then gets delivered to the receiver, but the receiver will only store about 256kiB of "out of order" data.  After that, it can't process the data and deliver it to the application layer because it's missing a packet, but it also won't store it, so it just drops it.  The sender seems to easily hit this limit in my testing over the local loopback.  Presumably, the packets are getting queued either in the tailnet netstack or the wireguard layer.  The problem, then, is that it creates a second, larger hole in the data stream.  The sender has no way of knowing those packets were dropped, so it can get stuck in a congestion backoff when it exits fast recovery.  This then waits for RTO, and we see a stall as above.

I'm not sure yet whether the connection getting stuck is a genuine gVisor bug, or just an edge case TCP congestion control doesn't handle well.

I'm also not sure if there are any practical things we can do at the tailscale or wireguard layer to reduce the number of in-flight packets so we don't hit this issue as much.

----

Lastly, I've observed the TCP stack getting stuck _during_ fast recovery in some cases with multiple dropped packets.  I haven't had a chance to fully understand why this is happening.

**Comment by spikecurtis** [comment]
Wow, wireguard looks like it has fairly large queues. https://github.com/WireGuard/wireguard-go/blob/master/device/queueconstants_default.go

So, we could be queueing up 1024 in both outbound and inbound packet queues.  With packets around 1kiB in length, that's maybe 2 MB of data that could be in flight in the network, which can easily overwhelm the 256kiB max out of order.

The issue above where the TCP stack gets stuck _during_ fast recovery is another manifestation of overwhelming the out of order buffer.  With SACK enabled we tend to do a little better, but once the out-of-order buffer is exhausted, even SACK doesn't help keeping things moving along because the receiver drops those packets without SACK'ing them or anything above them --- so the sender (erroneously) thinks they're still in the network and it's congestion control won't let it send, even in fast recovery.  They annoying thing is that even after a timeout, we can still be stuck because the SACK information continues to be sent, and the TCP stack doesn't keep track of the time it sent individual packets, so it can't realize those packets can't reasonably be still in the network.

When I increase the TCP buffer to a total of 32MiB (and thus 8MiB for out of order packets), then I no longer see the issue with stalled progress due to exhausting the out of order buffer.  I still see the RTO occasionally triggering, but that's due to a fast-retransmit being dropped, and there is nothing we can reasonably do about that.  As I said above, the RTO is the backstop, and you can't reasonably expect it never to be triggered in a lossy network.

I also tried shrinking the wireguard queues to 32, and this also seems to help with not exhausting the out of order buffer, but some very basic perf testing shows an impact on throughput with this approach from 47MiB/s down to 37 MiB/s.

**Comment by spikecurtis** [comment]
So, for some concrete recommendations:

1. We should try to ensure that the WG handshake has completed before attempting to dial a TCP connection when using `coder ssh`.  We should also ensure the `coder tunnel` command doesn't write any confirmatory messages until WG handshake is up, so that people using that command in scripts can wait before attempting to dial the port we're forwarding.

2. We should consider increasing the TCP recv buffers to 16MB in the Agent, and in the CLI client.  I _don't_ think we should increase it in Coderd/proxies, since that's likely to be more memory constrained handling many proxy requests in parallel.  Furthermore, the triggering use case of sending a big, sustained bunch of traffic over the TCP connection (e.g. a file upload) is much less likely --- proxying is typically going to be handling HTTP requests from devURLs, web terminal, or IDE websockets and the like.

**Comment by spikecurtis** [comment]
I've raised an issue with the gVisor team about only having 25% of the receive window available for out of order packets. https://github.com/google/gvisor/issues/9153

**Comment by mafredri** [comment]
I did some experimenting with the repro PR and modifying gvisor to use a 75% buffer (instead of 25%, as per the inconsistency identified by @spikecurtis) and with this change, TCP flow is very stable and I was no longer able to reproduce the issue.

This could be a permanent fix, or at least a very huge improvement, but the change seems potentially dangerous may have repercussions we're not aware of. Hopefully the gvisor team will get back to us soon.

**Comment by mafredri** [comment]
@spikecurtis IIRC, gvisor includes some breaking changes in main and the package can't simply be bumped without making changes to Tailscale as well. Tailscale (main) is currently on `gvisor.dev/gvisor v0.0.0-20230504175454-7b0a1988a28f`, we could pick this one as a forking point and cherry-pick the commit.

We may also want to include https://github.com/google/gvisor/commit/c77d00a7eeb31b7093548cb30d7982191286b191, just in case it also plays a role (I've been using this patch in my testing, and it at least hasn't made things worse).

**Comment by bpmct** [comment]
@janLo We're now using the new version of gvisor in the `main` branch and made an image + system package that should let you try this in advance to confirm the fix worked. We'll make a release in a few days if everything works normally.

Container image: `ghcr.io/coder/coder-preview:pr8563`
Packages & binaries: https://github.com/coder/coder/actions/runs/5577994811

**Comment by janLo** [comment]
Thank you very much! I'm following this and the related issue with great interest and admiration for your in-depth analysis of the situation.

I'm on vacation in a few days and I won't try an update just before that but I'll do it as soon as I'm back at work and will report back what the results are.
