### ISSUE TITLE
Make it easier to create unlimited access tokens

### ISSUE THREAD

**Issue by ammario** [coder/coder#7539]
Right now, we limit the maximum token duration to 100 years, since that's approximately the maximum value a Go duration can support. 100 years is basically forever, so there is no security advantage to having this ceiling vs. allowing truly unlimited lifetimes.

**Comment by Emyrk** [comment]
I think this might be a visual thing we handle, rather than a special number we pass in.

If we used `null` or `time.Zero()`, I fear that we have to add extra conditional logic where ever the date is compared. So we should maintain "unlimited expiration" is just some far out date/duration.

As for display purposes, I think we can make the UX interpret anything over X years as "unlimited". And for input, just have a button or selector to select "unlimited" which converts it to a large duration.
