### ISSUE TITLE
Remove the WS filter owner:me when user is Owner

### ISSUE THREAD

**Issue by francisco-mata** [coder/coder#7586]
As an admin of Coder, I would like to see as default all workspaces created, not only mine. Each time I enter to workspaces tab, need to the delete this filter... Isn't that of an issue, but it's annoying

**Comment by kylecarbs** [comment]
Maybe we should make these filters clickable buttons instead so this is less of an issue:
![image](https://github.com/coder/coder/assets/7122116/a62ca72f-3440-40b7-8a6d-120c8fd6ea73)

Thoughts?

**Comment by francisco-mata** [comment]
@kylecarbs Lovely idea :D. Yeah for a user POV user:me it works perfectly. But for an admin POV is really annoying, because you lost context of all the WS

**Comment by kylecarbs** [comment]
cc @BrunoQuaresma thoughts?

**Comment by Emyrk** [comment]
@kylecarbs I thought awhile back maybe we should save the user's last non-errored search. So if they leave and come back, it is the same. Thoughts?

**Comment by BrunoQuaresma** [comment]
@kylecarbs I think we should remove the default since members only will be able to see the workspaces they have permission to. 

@Emyrk I think the user can bookmark the URL with the search params if they want to have a faster way to access a specific workspace set. Something like GH does for filtering issues. I think applying a "last successful filter" can be tricky and kinda error-prone
