### ISSUE TITLE
Coder CLI on Windows: SSH ProxyCommand does not include quotes

### ISSUE THREAD

**Issue by bpmct** [coder/coder#7639]
It seems like when I manually download `coder.exe` and add to PATH, the ProxyCommand does not include quotes which results in failed SSH connections in many cases, including when using git bash.

From manual .exe download, added to path, and `coder config-ssh` in git bash:

```
Host coder.dev
	HostName coder.dev
	ConnectTimeout=0
	StrictHostKeyChecking=no
	UserKnownHostsFile=/dev/null
	LogLevel ERROR
	ProxyCommand C:\Users\benpotter\Desktop\bin\coder.exe --global-config C:\Users\benpotter\AppData\Roaming\coderv2 ssh --stdio dev
``` 

Result when I try to SSH:

```sh
$ ssh coder.dev
/usr/bin/bash: line 1: exec: C:UsersbenpotterDesktopbincoder.exe: not found
kex_exchange_identification: Connection closed by remote host
```

From msi installer (this works):

```
Host coder.dev
	HostName coder.dev
	ConnectTimeout=0
	StrictHostKeyChecking=no
	UserKnownHostsFile=/dev/null
	LogLevel ERROR
	ProxyCommand "C:\Program Files\Coder\bin\coder.exe" --global-config C:\Users\benpotter\AppData\Roaming\coderv2 ssh --stdio dev
```

**Comment by kylecarbs** [comment]
@bpmct if you manually toss quotes around the exe path does it work? I'll add an exception for this right away.

**Comment by bpmct** [comment]
yeah, it works if i manually add the quotes.

**Comment by Emyrk** [comment]
There has been a deep dive here already: https://github.com/coder/coder/blob/eee4f835ec0b51fc6b3a87d264968a38142c6306/cli/configssh.go#L703-L729

So simply adding quotes might not be a complete solution.

**Comment by Emyrk** [comment]
Talked with @mafredri about this. Simply quoting the strings is not a complete solution.

The issue is that the git bash is being "unix compatabile", but `path/filepath` package is using windows path separators (being the backslash). 

So I am going to add a flag + env var that allows forcing to use the forward slash. So people in this situation can run something like `coder config-ssh --path-separator="/"` or use an env var to keep it persistent. 

This is an unfortunate fix. But any solution aimed at fixing this could break the windows Command prompt. So this is the stop gap.

**Comment by Emyrk** [comment]
Not great, but this can now be done on windows:
```
coder --config-ssh --force-unix-filepaths
```

Setting an env var in your profile would make this permanent
