### ISSUE TITLE
Show service banners in SSH/TTY sessions

### ISSUE THREAD

**Issue by ammario** [coder/coder#7652]
See background in https://github.com/coder/vscode-coder/issues/101 that applies verbatim here.

I'm not sure of the practicality of showing the banner in all TTY sessions, but doing it over SSH should be easy enough using the agent as a MITM.

Some credits to @matifali for his foresight in https://github.com/coder/coder/issues/4322#issuecomment-1269662272.

**Comment by Kira-Pilot** [comment]
@ammario is this at all related to #7360?

**Comment by ammario** [comment]
@Kira-Pilot Looks related to me 😶‍🌫️

**Comment by spikecurtis** [comment]
We need to be very careful about injecting stuff into people's TTYs.  

Jetbrains Gateway operates by remotely executing commands over SSH, and they request a TTY rather than just executing the command directly over SSH.  IIRC, they mentioned they do this so that they can send signals.

Anyway, the point is that we can't make the assumption that it's a live human on the other end of a TTY session who can make sense of our messages and not get broken by them.

In the specific case of the user starting a shell (command is empty), it is probably fine to insert some stuff before the initial prompt, Message-of-the-Day style, since bots will be used to dealing with that, but in the case they execute some other command, it is not safe to just insert text into the output stream.

**Comment by ammario** [comment]
Makes sense to me. I do think we should show the service banner in the MOTD instead of requiring that users edit their template. It is a valuable default for 99% of users and only a small nuisance to the remaining 1%.
