### ISSUE TITLE
Flake in test-js

### ISSUE THREAD

**Issue by ammario** [coder/coder#7948]
[See example run](https://github.com/coder/coder/actions/runs/5226164318/jobs/9436516524)

cc @coder/ts

**Comment by Kira-Pilot** [comment]
I tried to reproduce this flake locally by running it 1000 times with Jest's `it.each` method to no avail. I have seen the same error in CI, but only very recently.
![Screenshot 2023-06-12 at 3 26 24 PM](https://github.com/coder/coder/assets/19142439/8810d908-785e-4271-af8e-98878b40fa66)

Given this test has been in production for over a year without flaking continuously, I am wondering if the culprit is actually the same CI agent flake we've been running into on the Go side? I notice we are actually opening the workspaceagent websocket in this test - perhaps we could mock that out somehow instead to avoid this issue.
@code-asher I see that you were the original author - does the above seem reasonable?

**Comment by code-asher** [comment]
It looks like we are mocking out the web socket, I think?  We create a websocket with `jest-websocket-mock` then we send text on that (essentially acting as the backend) and expect that text to show up in the terminal.

The linked run reports the string in the first row is `" "`; I wonder if xterm.js sometimes renders a row with a space in it for...some reason.  There was that recent xterm.js major version update.  Could be something related to that.

Maybe if we check all the rows for the expected text instead of just the first one.

**Comment by Kira-Pilot** [comment]
Ah, you're right - I missed the mock. Good idea about xterm - I'll do some digging this week between sprint work.

**Comment by mtojek** [comment]
I have a feeling that it is stale issue. Feel free to reopen when it bumps up again.
