### ISSUE TITLE
BUG: Adding coder_apps when using multiple coder_agents hangs

### ISSUE THREAD

**Issue by hh** [coder/coder#7957]
Seems similar to https://github.com/coder/coder/issues/7291

When using multiple coder_agents (ex: one for host and one for kubernetes pod), template works fine UNTIL you add any coder_apps. This causes coder template create/push to HANG:

✔ Detecting ephemeral resources [13906ms]
> ⧗  Cleaning Up

Very difficult to debug. How can we turn on logs that helped created you @bpmct  create the logs in https://github.com/coder/coder/issues/7291#issue-1684118153?

**Comment by bpmct** [comment]
@hh - would you be able to provide a copy of your template so we can debug? You could also try setting `TF_LOG=debug` in the server config.

**Comment by bpmct** [comment]
We took a look at this live on a call. Their template essentially does the following:
- Provisions 2 agents
- Provisions a bare metal server and starts agent 1 on this server
- With cloud_init, the bare metal server spins up a Kubernetes cluster. 
- That Kubernetes cluster spins up a pod and starts agent 2 on that pod

It seems like the "slug must be unique" error is not entirely true since there is only one slug, but it is being duplicated since the agent association is wrong (there is no Terraform resource for the pod).

As a workaround, @hh is going to try:
- Provisioning a null_resource to represent the pod for Coder and passing in the agent token to guarantee the right association
- The `null_resource` can be rendered as the "pod" with agent metadata
- The agent 2 token still has to be passed into cloud_init+K8s, but a `local` will be used in an attempt to avoid the association to the bare metal server, which I believe does the duplicate stuff.

**Comment by bpmct** [comment]
Created #8048 to ideally surface this better. I'm not really sure how we could show a better error based on the template association.

**Comment by bpmct** [comment]
@hh - were you able to get it working then?

**Comment by matifali** [comment]
Closing as not planned due to no response from OP. Please feel free to comment, and we can reopen if you'd like.
