### ISSUE TITLE
user interface for coder PostgreSQL database

### ISSUE THREAD

**Issue by da00891219** [coder/coder#8241]
how to get user interface for postress that was installed as part of coder?

**Comment by da00891219** [comment]
basically, we are looking to administer postgress in easy way

**Comment by sharkymark** [comment]
Utilities like https://www.pgadmin.org/ and https://dbeaver.io/ can connect to PostgreSQL.  This is outside the scope of Coder responsibility and you would use the database credentials that you established at creation.

If you're just using the embedded PostgreSQL, you can retrieve the database connection string to view the port, database name, user and password with:

`coder server postgres-builtin-url`

Otherwise, use the information when you manually set up PostgreSQL either as a pod or external service.

**Comment by sharkymark** [comment]
I tested pgadmin4 out with my local deployment, seems to work 

![image](https://github.com/coder/coder/assets/2022166/964be98c-a20d-4f14-a260-1632b0f0d63e)

**Comment by da00891219** [comment]
I get this string and pgadmin not able to connect. can you please help me with this.
```
coder server postgres-builtin-url
 psql "postgres://coder@localhost:52918/coder?sslmode=disable&password=xxx"

```

**Comment by sharkymark** [comment]
Seems that using the information in the string above should work. It works fine for me.

**Comment by da00891219** [comment]
Yes. I have used cluster IP in host and remaining details from the string.
