### ISSUE TITLE
Feat: Easier inter-workspace communication 

### ISSUE THREAD

**Issue by sharkymark** [coder/coder#8257]
A large enterprise has a vision where development environments are also development servers.

e.g., Microservices should be able to run atomically (one per) in a workspace. Imagine 50 workspaces each with a microservice.

Developer's primary workspaces should be able to easily access these microservices.

Coder has capabilities like `coder_app` where RBAC can make that endpoint accessible by other users in the deployment but there is no discovery in Coder. Or use the CLI in a workspace to `coder port-forward` workspaces, but it is difficult to setup and brittle. Same thing - no discovery mechanism for users to know about these running services.

Combining the microservices inside a single workspace with `docker-compose` or multiple containers in a workspace pod are not appealing since the enterprise does not want to be constrained by the workspace's compute.

Coder workspaces also are subject to auto-off and not automatically restarting if a problem occurs.

Maybe this enterprise suggestion is outside the scope of Coder, but the concept would require easier and more resilient tooling.

**Comment by matifali** [comment]
Is it somehow related to 
#2425
#6304
#4786
#8220
#6278
#6606

**Comment by MrPeacockNLB** [comment]
Sounds great! Except #8220, #2425, #6304 this should not be an option for security reasons. To collaborate we are planing to use **code with me**. I like the Idear to discover services via `coder` so one can configure local application. 

We have the use case were for one project a developer needs to start 7 microservices in order to get the application to start. One solution is to run these services via docker-compose. But on the other hand often one need to modify 2 or more service at the same time. In this case the developer has to start multiple workspaces and configure them.

- What if multiple instances of an microservices are running? Which one should be used?
- How does a workspace say hey I'm service A?

**Comment by sharkymark** [comment]
Some additional feedback on the use case was they are familiar with helm, so potentially have the template create a namespace for the user, and run specific charts to spin up additional pods that are accessible in their project.

**Comment by matifali** [comment]
@sharkymark This approach is a good use-case, and maybe we should document it as a guide/walkthrough if there is more demand.
