### ISSUE TITLE
Docs: defaults to "latest" a.k.a. main, which is confusing for new features

### ISSUE THREAD

**Issue by spikecurtis** [coder/coder#8324]
When you go to docs.coder.com and click v2, you get sent to "latest" which is the `main` branch.  These docs often describe features that are not yet released, which can be confusing for users.  We should default to the latest _released_ version.

Also, there is no obvious way to navigate to docs for a specific release of Coder.

**Comment by bpmct** [comment]
Totally in favor of adding versioning to the docs. I think it would be relatively easy, like v1. To save on cloud cost, let's only do the last 4 versions + some way to view "upcoming" but it is not the "latest".

**Comment by matifali** [comment]
Related to 
- https://github.com/coder/coder.com/issues/330
- https://github.com/coder/coder.com/issues/329

**Comment by matifali** [comment]
Hi, @Kira-Pilot, can you also add `latest` to the list to quickly switch back to `latest` docs?
![image](https://github.com/coder/coder/assets/10648092/eea5b37a-0d55-4bf1-aa6b-4cb44db91c8c)

Also, when we open docs, we should land on the last stable version docs instead of `latest`.

**Comment by Kira-Pilot** [comment]
@matifali `latest` does load when you open docs - the latest released is 2.5.1, so that is what shows up in the picker. We always show the actual version in the picker, but accept tags in the URL (including `main` or commit hashes). This way, users know what the latest version is:
https://www.loom.com/share/9820c7e764c44ce6858c82eed39a31b2

LMK if you still want changes!
