### ISSUE TITLE
values from `.tfvars` not getting loaded

### ISSUE THREAD

**Issue by da00891219** [coder/coder#8356]
coder templates create not loading .tfvars values.

**Comment by mtojek** [comment]
Hi @da00891219,

Let me give you some advice on proper issue reporting.

Unfortunately, issues like this do not make any sense and are hard to investigate. We don't know which version of coder you're using, what is the error you're facing, or what is the expected result. Sometimes it is also valuable to share the template you're working on. If this is a new feature you're asking for, please justify why and when are you going to use it.

Could you please correct the issue and add a proper description with more details about the bug you see? Otherwise, we will close the issue as it is too vague.

Thank you for your understanding.

**Comment by da00891219** [comment]
my coder template comprised of below files.

README.md
`main.tf` --> where resources are created
`variables.tf` --> defined variables here
`values.auto.tfvars` --> consists values for variables, mainly secrets --> but these values were not reflected when I run `coder templates create`

coder version server/client: v0.20.1
terraform version on my client: v1.3.7

**Comment by ElioDiNino** [comment]
This may relate to #8279

**Comment by bpmct** [comment]
Going to close in favor of https://github.com/coder/coder/issues/8501
