### ISSUE TITLE
scaletest: determine impact of one greedy agent

### ISSUE THREAD

**Issue by johnstcn** [coder/coder#8556]
# Question

## Given
You have N workspaces connected happily to a single coderd instance, sending / receiving data at a constant rate.

## When
One workspace starts and begins performing a large amount of data upload / download.

## Then
What is the effect on existing connections?
Expected: minimal impact on read/write latency P99.

Perform a scaletest to determine the effect of the above
a) For SSH traffic
b) For ReconnectingPTY traffic

**Comment by bpmct** [comment]
I think we should prioritize this, we have some customers who have users who download/upload large bundles as a core part of their workflow.

**Comment by mafredri** [comment]
I opened a related issue, #10278.

**Comment by mafredri** [comment]
Update: A single user connected to agent/workspace over web terminal (reconnecting PTY) is pretty much able to bring Coder to its knees. (This test was run using 1 regular workspace and 1 greedy).

<img width="986" alt="image" src="https://github.com/coder/coder/assets/147409/40bbf207-b4b2-4d98-8520-74351bfe8a72">

We also only seem to be able to push 15MB/s from user->workspace and receive at 10MB/s. Yet the coder CPU shoots up. (The asymmetry in up/down here is due to user sending JSON, and workspace sending raw terminal output back.)

We can also see that the metrics for `coderd_agentstats_rx_bytes`(/tx) are not very good:

<img width="986" alt="image" src="https://github.com/coder/coder/assets/147409/ba088e30-cce3-4e6c-93fd-319cb6d8240e">

I would assume that the traffic doesn't propagate in this kind of bursty manner.
