### ISSUE TITLE
License Issue Banner Shows up in Error

### ISSUE THREAD

**Issue by ElioDiNino** [coder/coder#8665]
Version: [`v0.27.1+65583ec`](https://github.com/coder/coder/commit/65583eca47f6d9d194ed8b038c3c010a4cd331c4)

After upgrading my deployment through Helm (my deployment is on Kubernetes), the "License Issue" banner shows up complaining about replicas.
![Screenshot 2023-07-21 at 3 25 19 PM](https://github.com/coder/coder/assets/52972357/8aec6fe3-7a93-4018-bff5-290e8d87a8b4)

This is despite the fact that `replicaCount` is only set to 1 in `values.yaml` and I can see there is only 1 Coder deployment pod running. Another note is that I am still able to start and connect to workspaces fine (which contradicts the banner).

I suspect this is just a visual bug where when Helm deploys it creates a new instance and fully boots it up before shutting down the old one. In this time, Coder detects an additional instance so it reports the error. However, I also suspect the backend checks this again at later points to allow workspaces to boot up but the frontend is not updated. I could be wrong here though. Just odd that none of the prior Coder versions had this issue.

Reproduction Steps:
1. Start with Coder deployed with Helm on Kubernetes
2. Redeploy (with `values.yaml` changes) or upgrade the instance with Helm (so that a new instance is booted up)
3. Open the Coder dashboard once the new instance has started and observe the banner

**Comment by ElioDiNino** [comment]
Upon further investigation and a few redeploys, I have found that the banner sticks around for almost exactly 10 minutes each time before disappearing. Not sure if this is because the frontend updates this information every 10 minutes?

Either way, I think there should be a slight delay before the initial check and showing of the banner to consider deployment lifecycles such as that of Helm's.

**Comment by smolinari** [comment]
I came across this same issue. I reported it on the Discord server first. 

https://discord.com/channels/747933592273027093/991429648200245358/1132578113658830901

I'll also now check to see if it goes away after 10 minutes, as I want to turn on verbose logging for another issue.

Scott

**Comment by sthdev** [comment]
The banner also disappears when the Coder pod is restarted.

**Comment by spettinichi** [comment]
I have also seen this. It hasn't stopped us from actually doing anything, but it does appear like it is an issue to users. I hadn't timed it but it does go away after a bit. A longer wait before displaying the message should fix it. The two pods are only up simultaneously for a few seconds

**Comment by Emyrk** [comment]
The polling interval for license checks is 10 minutes: https://github.com/coder/coder/blob/94cbc2ae7fd689b04a33d603bde8838605cc0ddf/enterprise/coderd/coderd.go#L48-L48

The number of replicas comes from `replicasync`. When a coderd goes down, it should call `Close()` which removes the "replica" from being tracked: https://github.com/coder/coder/blob/94cbc2ae7fd689b04a33d603bde8838605cc0ddf/enterprise/replicasync/replicasync.go#L418-L421

Replicas are grabbed from this query. The updatedAt time does look into the past, but specifically ignores `Stopped` replicas. Replicas expect heartbeats every 5s, so if an old coderd did not deregister itself, it would be "expired" by the next time the license check comes around.

https://github.com/coder/coder/blob/94cbc2ae7fd689b04a33d603bde8838605cc0ddf/enterprise/replicasync/replicasync.go#L163-L163

----

So the issue is likely the old coderd not being fully down before the new one is up. 

As for solutions, this can be tricky if both Coderd's are alive. If a blue/green deployment is being done, then there exists 2 coderds at one point of time, and this does conflict with the license. Maybe we can implement a grace period that 2 can be alive during?

A "dumber" solution is to allow either a manual "check the license again" button, or reducing the interval in some cases (after boot have the license check be 1min until 10min after boot or something).

**Comment by spettinichi** [comment]
That is correct, the new one spins up and the old one doesn't terminate until the new is healthy. It'll shut down almost right away once it has gone healthy, this ensures there is not an interruption during the upgrade. I think some sort of grace period after startup is probably the easiest solution so that there doesn't have to be much knowledge beyond age of the container. I think that something short like 1-1 min grace period should likely be enough in most ideal circumstances. If it occasionally triggers because of a slow deployment that's not as big of a deal in my opinion. It just seems bad that it happens every upgrade.

**Comment by Emyrk** [comment]
Agreed it is an annoying issue.

I was looking how to implement a grace period. There is nothing in the code that actually enforces the "You will be unable to connect to your workspaces".

What happens is both Coderd's run local in memory coordinators, and they are unable to communicate with each other. So as a client, when you go to access your workspace, if you hit the wrong Coderd, your workspace connection will fail. If you hit the correct one, it _should work_.

This means the banner is strictly visual. If there is really only 1 Coderd, then workspaces are reachable.

----

So the grace period would only affect the visual element. We do include the `started_at` time, so I could have the code see a new coded has just recently started, and not show the message, since it _just booted up_. But then if there really was an issue, say you set your replica count to `2` in the helm chart, then this grace period would hide a genuine issue.

Or said differently, I do not see an easy way from the started_at times to determine if something is being upgraded/rebooted/downgraded from accidentally starting 2 coderds. Do I say if only 1 replica started recently, and 1 started more than "1 hour" ago, then it's really just "1", and I can assume the old one will die? 


If someone has a simple algorithm in mind, I would be happy to implement it. I just worry about posting a false negative, more than I worry about posting a false positive. In the current case, it is annoying, but things work. If I implement this grace period, things could be broken for up to 10 minutes without any notification.

---

As a stop gap, I can implement a "force refresh" button. To at least let you remove that banner quicker :cry:

**Comment by Emyrk** [comment]
I just thought of another idea in addition to the button. When a Coderd goes away, in this case the first one, it can send an update on the pubsub to tell other coderd's to update their entitlements. 

This should force the refresh automatically when the first goes away. And should work. The banner would still appear for any duration the both are alive.

**Comment by spettinichi** [comment]
Yeah in my experience I'm not actually blocked but that's good to know for sure. I definitely don't see this as a major bug, more an annoyance that makes users think it's broken when it isn't. The suggestion to just refreshing more often than 10 min after startup should work to not hide real issues but minimize impact of false positives. if it only shows 1 min for example far fewer people will catch it. Otherwise if you could have the dying one report to update that would work too but I assume it's more complex

**Comment by Emyrk** [comment]
PR: https://github.com/coder/coder/pull/9155

- Dying one will tell the ones alive it is going away. This should remove the banner _instantly_
- Button in place as last resort if the banner won't go away from above.


I am going to hold off on:
> but every 1 min after startup until 5 min, then at 10 min, then regularly scheduled or something to back off?

The first thing I mentioned of the dying one should resolve this. So when this gets released, I will close this issue. If the issue reappears and is annoying, please reopen an issue. We might implement the faster checks at the start, and gradually back off to the 10minutes, or come up with another solution. 

But I think this should resolve things :crossed_fingers:

**Comment by spettinichi** [comment]
yup that's fine with me! I just figured the recheck would be easier, but the dying one telling it to recheck should be the fastest! Thank you for being so responsive!

**Comment by ElioDiNino** [comment]
Thanks for the hard work on this @Emyrk ! Can't wait to see it working with the release it gets included in

**Comment by smolinari** [comment]
Maybe from left field, but how about simply allowing two Coder instances? If the Enterprise license/system isn't in place, the two instances won't work properly anyway (if my understanding is correct), so allow two. If there are three instances, then it is obviously someone is trying to do HA, then show that red banner. All that other work isn't necessary. 

And/ Or, when there are two (or even more instances), show the banner as a warning (not red, yellow maybe?), and with a much different text, something like:

> There are or were two instances of Coder running. This may have been due to maintenance. If you are trying to run Coder in HA mode, the system won't work properly. This mode only works with an Enterprise License. If you are interested in running HA mode, please contact our Sales team at sales@coder.com. We'd love to hear from you!

And make it closable. :grin: 

Now the banner is a much more friendly commercial banner about the missing feature, instead of a cold error about a failing system. 

Theoretically, this warning should only be for admins/ owners too, but you gents have the system locked down in terms of features (i.e. no groups allowed), you can't decipher who is an admin and who isn't, so everyone will get this banner shown to them. I even say that is a further issue (the "complete" lockdown of some features), but that is another discussion. :wink: 

Scott

**Comment by Emyrk** [comment]
@smolinari I think the wording can 100% be made better, and I really like your suggestion for the text.

> how about simply allowing two Coder instances?

We do! The current banner saying "You will be unable to connect to workspaces" **has no enforcement in the code**. So in the case of a maintenance upgrade it is strictly a textual warning, because you really do only have 1 "available" coderd.

If you truly have 2, and are trying to run HA, then you have a 1/n chance of connecting to the right instance. If you connect to the wrong one, the connection will fail. So it's not enforced from a license POV, just the Coderd's don't talk to each other, so if you connect to Coderd **A** and the workspace connects to Coderd **B**, then the connection will not work.

> Theoretically, this warning should only be for admins/ owners too

We can detect this! Honestly I thought is how it was, but I could 100% be incorrect about that, and we can fix that. We never check role names (`owner`, `user admin`, etc), we only check capabilities. So we can show the banner if the user has the ability to upload a new license for example. 

---

So @smolinari I will figure out some text changes (@bpmct weigh in on the text of the banner?).

The PR I have open is still beneficial as it removes the banner quicker when it is a false positive due to the blue/green deployment strategy.

**Comment by smolinari** [comment]
> We can detect this!

Out of curiosity, how? Every user is the same, aren't they? Except for maybe the original/ first user after the install?

Scott

**Comment by Emyrk** [comment]
@smolinari The `Owner` can add/remove roles to other users. The available roles are listed in the docs:

https://github.com/coder/coder/blob/1a4b873a3ff518dd13a89fbe183aeac49de949e8/coderd/rbac/roles.go#L292-L319

Our frontend decides to show/hide UI components based on the capability of a user. So the checks are `CanCreateUser` instead of checking if the user has the role `"owner"`.

**Comment by spettinichi** [comment]
Yeah we have multiple admins because we want multiple people able to reset passwords and such. Its actually possible that's who I've heard from.. I don't actually know for sure so maybe emyrk is correct and not everyone was seeing the banner. I'd have to actually poll people next upgrade to verify

**Comment by Emyrk** [comment]
@spettinichi the banner is shown to everyone. I took a look at the code, and it does not have any conditional showing based on perms.

I also confirmed that that is intended behavior.

**Comment by spettinichi** [comment]
Ahh okay, I realized I didn't write down who all mentioned it to check their status so I wasn't sure. Thanks for the update!

**Comment by smolinari** [comment]
> @smolinari The `Owner` can add/remove roles to other users. The available roles are listed in the docs:
> 
> https://github.com/coder/coder/blob/1a4b873a3ff518dd13a89fbe183aeac49de949e8/coderd/rbac/roles.go#L292-L319
> 
> Our frontend decides to show/hide UI components based on the capability of a user. So the checks are `CanCreateUser` instead of checking if the user has the role `"owner"`.

Thanks for the explanation. It got me looking deeper. To be honest, I hadn't yet created a new user and didn't realize roles were even a thing. So I apologize for my ignorance. :blush: 

Scott

**Comment by sempie** [comment]
Seems to have been reintroduced in v2.2.0.

I was able to reproduce running a helm upgrade on an instance already running v2.2.0.

**Comment by Emyrk** [comment]
@sempie how long did the error last? It should appear, but only for the overlap duration, which should be small (<30 seconds)

**Comment by Emyrk** [comment]
@sempie can you provide how long the error lasted? If it is less than 1 minute (during the overlap period of the 2 coderds), then this is expected behavior.

**Comment by TylerHendrickson** [comment]
I'm seeing this issue again in v2.3.1 (after running a helm upgrade from v2.3.0).

After 10 minutes of waiting, I used "empty cache and hard reload" in the browser, which made the banner finally go away.

**Comment by Emyrk** [comment]
I think 10 minutes is the check interval, so that is expected. I wouldn't guess the value would be cached anywhere 🤔.

It's clear my solution isn't working all the time

**Comment by smolinari** [comment]
For some reason, it seemed like this problem went away the last couple/ few updates, but then it happened again. 

https://discord.com/channels/747933592273027093/991429648200245358/1199933710137557013

Scott

**Comment by taxilian** [comment]
definitely this is happening again in late 2025...
