### ISSUE TITLE
The users list looks a bit funny as a user

### ISSUE THREAD

**Issue by bpmct** [coder/coder#8739]
Since we disabled viewing other members, it's a bit of a funky UX. Perhaps we redirect to `/` instead?

Same with `coder users ls`:

```sh
# there are way more users, i just don't have permissions to see them
➜  ~ coder users ls
USERNAME  EMAIL           CREATED AT            STATUS  
user      user@coder.com  2023-07-26T16:57:45Z  active  
```

https://github.com/coder/coder/assets/22407953/540e97a8-d2e5-4aa9-9887-6c0a2cc497c2

**Comment by Emyrk** [comment]
Didn't really think of the cli experience. As for th4e web UI, we hide the link to that page. So you should not be able to navigate there except manually.

**Comment by bpmct** [comment]
Makes sense. I think we should probably disable the manual page + the CLI command for normal users since the result is inaccurate.

**Comment by Emyrk** [comment]
We cannot really disable to cli command from the `help` page, since we can't know a user's roles before they run the cli.

At best, we can just block the call, but what if the user can read _some_ users. Right now we don't have roles that allow reading a subset of users, but you could have that. So it is easier to just leave it imo in the cli and maybe add some wording that indicates it's only users you can see.

**Comment by bpmct** [comment]
> At best, we can just block the call, but what if the user can read some users. Right now we don't have roles that allow reading a subset of users, but you could have that. So it is easier to just leave it imo in the cli and maybe add some wording that indicates it's only users you can see.

Yeah I agree with that
