### ISSUE TITLE
Using external provisionerd with daily_cost won't work

### ISSUE THREAD

**Issue by MrPeacockNLB** [coder/coder#8785]
# Description

As the title says we are using an external provisionerd to deploy our workspaces. The provisionerd stops working as soon as I add **daily_cost** to the template. Without setting daily_cost everything works as desired.

When setting daily_cost it gets stuck after planing phase...

![image](https://github.com/coder/coder/assets/103434584/d38bb638-4b83-4468-a301-58320b0e0137)

In the logs of external provionerd raises an error **you don't own this job**

![image](https://github.com/coder/coder/assets/103434584/e1476680-cef6-4d50-bc3a-b2dfeb5b2efb)

# Mitigation

Disable **daily_cost**

**Comment by bpmct** [comment]
Good find!

**Comment by spikecurtis** [comment]
Ok, so there are 2 issues.

The first is that we miss initializing a pointer for external provisioner daemons, which gets dereferenced when we commit quota.  This causes coderd to crash with null pointer exception.

The provisioner daemon reconnects to a new coderd, but then gets rebuffed with "you don't own this job" because job ownership is bugged and tied to a specific connection for external provisioners, meaning they can't reconnect mid-job.

I'm planning to fix the first problem in this GitHub issue, but am going to track the second issue in #9399
