### ISSUE TITLE
`replicaCount: 1` but banner says 'License issue`

### ISSUE THREAD

**Issue by sharkymark** [coder/coder#8927]
Version: [`v2.0.0+ad513fa`](https://github.com/coder/coder/commit/ad513fa8b90dc851113589df93f67885bd4571cf)

I upgraded an AKS deployment which has the following conditions:
1. An expired enterprise license
2. `replicaCount: 1` in `values.yaml`

![image](https://github.com/coder/coder/assets/2022166/41ac75dc-3949-4e66-80ab-cb304da6a088)

![image](https://github.com/coder/coder/assets/2022166/c6f7767a-3482-4770-8534-9ab075ef1349)

![image](https://github.com/coder/coder/assets/2022166/7dbd577c-3d35-4a5e-a041-ec854e890eb5)

**Comment by bpmct** [comment]
I believe this happens briefly during a `helm upgrade` since one pod is spinning up as the other is terminating, so there is a brief period of time where 2 pods are online.

A couple of ideas to hide this error during the brief period of time: 

- Debounce this warning (e.g. only show it after ~30 seconds of a new replica replica being alive)
- Change the default Kubernetes `Deployment` strategy. I believe we can use `Recreate`. Open to other ideas though!
