### ISSUE TITLE
Add configurable user dormancy duration

### ISSUE THREAD

**Issue by kylecarbs** [coder/coder#8959]
90 days is too long for some of our users. As one mentioned, "you snooze, you lose" and they'd prefer 30 days.

This is a hard-coded duration right now and can easily be converted to a server CLI option.

**Comment by ammario** [comment]
Related: https://github.com/coder/coder/issues/8987

**Comment by bpmct** [comment]
Going to close this out in favor of #8987. I know this is a tricky topic, but since dormant users are only used to deoccupy a license seat (when they are logged in, they are marked as active again, and can access all their workspaces) we are going to keep it hardcoded to 90 days. 

We are working on other features to clean up Coder deployments such as #7095.

If you want to free up license seats, you can build custom scripts to delete workspaces, delete users, or suspend users.
