### ISSUE TITLE
`jq` in `2.0.0` image has vulnerability; please upgrade to latest `jq`

### ISSUE THREAD

**Issue by sharkymark** [coder/coder#8974]
During a scan of the coder image by a customer, they found a vulnerability so cannot use this image. Apparently the image uses jq [1.6-r3] and this has a High vulnerability which is fixed in 1.6_rc1-r0.

The details for the vulnerability are here : https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2016-4074

**Comment by deansheather** [comment]
This is an issue with the customer's vulnerability scanner. We're shipping `1.6-r3` which is greater than `1.6_rc1-r0`. We can leave this issue open while we track what we want to do about this though (like removing `jq` and encouraging customers who need it to extend our image for example) to avoid this false positive.

`1.6-r3` was released in [2018](https://github.com/jqlang/jq/releases/tag/jq-1.6), and this CVE was fixed in release candidate versions in [2017](https://github.com/jqlang/jq/commit/83e2cf607f3599d208b6b3129092fa7deb2e5292) ([issue](https://github.com/jqlang/jq/issues/1136)). I tried the PoC in the Coder image and it doesn't cause a segfault.
![image](https://github.com/coder/v2-customers/assets/11241812/aa02334d-c94a-40c0-8832-8d0e084695cc)
