### ISSUE TITLE
Improve UX for template admin when viewing users' workspaces

### ISSUE THREAD

**Issue by bpmct** [coder/coder#9175]
## Background

The template admin can view other users' workspaces to view the build logs, but they cannot access coder_apps, the terminal, or perform actions (stop/start/etc)

## Current behavior

@matifali brought up a good point with these two issues https://github.com/coder/coder/issues/9081 https://github.com/coder/coder/issues/9082. The UX is quite confusing which makes Coder look broken. Template admins can click into workspaces but then get vague errors.

## Proposed behavior

We disable buttons for unavailable actions for template admins with a tooltip that explains they do not have permissions to do the action. Alternatively, we change the error on the terminal page, coder_apps, etc to show the user does not have permisisons

We also have [CODER_DISABLE_OWNER_WORKSPACE_ACCESS](https://coder.com/docs/v2/latest/cli/server#--disable-owner-workspace-access) so the product should also disable the button for owners on workspaces that is not theirs if that is flag is enabled.

**Comment by matifali** [comment]
I prefer the first suggested solution to disable the buttons and additionally add a tooltip stating they do not have access. 

And for template admins they should not be able to even list other users workspaces.

**Comment by bpmct** [comment]
> And for template admins they should not be able to even list other users workspaces.

Why is that? Template admins have permissions to view build logs of other users' workspaces

**Comment by matifali** [comment]
> > And for template admins they should not be able to even list other users workspaces.
> 
> Why is that? Template admins have permissions to view build logs of other users' workspaces

I didn't think about build logs. I was of the impression that the list is only to access the workspace page and workspace.

**Comment by matifali** [comment]
@bpmct @BrunoQuaresma What do you think about removing access for other users' workspaces and adding a tab for all builds of that template to the template page? And only the template admin can view/access that tab.

This will also require disabling access to the other users' workspace page entirely instead of blocking individual buttons/coder_apps. And remove the filters from the workspace page to see other users' workspaces.

**Comment by matifali** [comment]
I believe you can better think on the implementation and design part and also the UX. Maybe @aslilac can add her opinion here.

**Comment by aslilac** [comment]
> Also, another option is to change the link on the workspace list to send the template admin directly into the workspace build logs page.

as long as the button text reflected that it could be cool. my only worry would be if we add some other feature later that they need access to and we either have to keep adding buttons or eventually deal with getting the workspace summary to behave the way we need.

**Comment by BrunoQuaresma** [comment]
Thinking more about this, it is not very clear what the solution is. I'm concerned disabling all the buttons, which are many, and adding tooltips for each one will make it look weird and add unnecessary complexity to the code.

Maybe instead of a tooltip, we could display a banner saying the user only has view-only access to that workspace but it still has a lot of buttons to disable.

Maybe another option would be:
- Identify what workspace resources we want to keep showing: startup logs, agent metadata, etc...
- Identify if the user only has view-only access to the workspace
- If they have, we show a simpler workspace view to the user only

What do you think @bpmct?

**Comment by bpmct** [comment]
> Maybe another option would be:
> 
> * Identify what workspace resources we want to keep showing: startup logs, agent metadata, etc...
> * Identify if the user only has view-only access to the workspace
> * If they have, we show a simpler workspace view to the user only

I like this approach, but it feels a bit complex. If it is not too bad, I am in favor of this.

---

However, I was thinking: the root cause of this is that when the user presses the "terminal" or tries to restart a workspace, they get:

> Disconnected

or

> Resource not found or you do not have access to this resource.


Perhaps we just make it clear the user does not have permissions to do these actions?

**Comment by aslilac** [comment]
I think I'd rather have the complexity of one view with a bunch of `disabled=` props and a "you have limited access to this workspace" banner over maintaining two entirely separate views that will inevitably get out of sync and cause bugs

**Comment by BrunoQuaresma** [comment]
Last question, should we disable or hide the buttons/elements?

**Comment by bpmct** [comment]
Yeah, hiding should be fine
