### ISSUE TITLE
Serious performance issues with Kubernetes

### ISSUE THREAD

**Issue by Smartich0ke** [coder/coder#9212]
I got started with Coder in Docker and it worked really well but I have recently switched to Kubernetes and installed the Coder helm chart and I'm using the default "develop in Kubernetes" starter template.

I'm able to spin up workspaces with it fine, but inside the workspace is very slow. When I type letters into the the web terminal, they are slightly delayed. Operations like running `composer install` or `npm run build` take 5-10 minutes for relatively small projects.

This is strange since I run similar operations on the same cluster through other applications without any problems.

I've tried allocating more resources without improvement and network speed doesn't seem to be a problem since it's the operations in the container that sometimes fail due to timeouts. I'm using the NFS subdir provisioner as the default storage class which has been serving well for other applications on the cluster.

Any assistance on how to fix this or further diagnose the issue would be appreciated.

Coder version v2.1.0+c15ce7b

**Comment by kylecarbs** [comment]
NFS isn't typically performant for operations like npm install.

Coder doesn't do anything magical inside the container, our thin agent just runs and pipes the terminals.

Could you share your template?

**Comment by mh013370** [comment]
We don't see any serious latency issues and we're running entirely in Kubernetes, so my suspicion is that it's not necessarily Coder that's causing the behavior you're seeing.

**Comment by Smartich0ke** [comment]
Sorry for the long wait,

Even though I have been running stuff on NFS storage without problems, I'm setting up longhorn soon on the drive array my cluster VMs run on and see how that goes. Will get back with results soon.

**Comment by smolinari** [comment]
I'm also on k8s and don't see any performance issues running processes inside workspaces. I do notice the performance is a bit slower (minorly) than local dev'ing, but I'd say that is due to the el-cheapo hosting I'm using and underpowered servers. I'm using Longhorn too, but am using the `local-path` provisioner, since I want PVCs to be destroyed, once the pod is destroyed. I can pretty much say with confidence, if you put volumes onto Longhorn and it is using its default replication, you won't be happy with performance either. I'd highly suggest to not have your dev code saved anywhere long-term inside the k8s cluster. 

Scott

**Comment by Smartich0ke** [comment]
Ok so I changed to local path storage and workspaces seem to be a lot faster now. Thanks for the help!
