### ISSUE TITLE
Cannot open mitmproxy UI via port forward in UI

### ISSUE THREAD

**Issue by MrPeacockNLB** [coder/coder#9240]
# Description

We want to inspect all workspace application traffic. I found **mitmproxy** would fit here perfectly. But it is not possible to access the `mitmweb` UI via port forward. Opening port of the web UI shows 404 not found.

![image](https://github.com/coder/coder/assets/103434584/280d27d3-f85f-49a1-98dc-1a51738355ac)

# Steps to reproduce

- install mitmproxy
- start mitmweb with `mitmweb -p 8888 --web-port 4444 --mode reverse:http://127.0.0.1:8000`
- open UI on **port 4444** via port forwarding
- 404 shows up in the browser

# Notes

- accessing UI via `curl http://localhost:4444` shows the html code from **mitmweb**
- Opening the proxied app works as aspected
- all traffic gets shown in the TUI of **mitmproxy**
- not tested: port forwarding via CLI to localhost

**Comment by MrPeacockNLB** [comment]
just retested now with latest version of Coder. The Problem still exists.

![image](https://github.com/coder/coder/assets/103434584/dda13135-0bb3-486c-9f4e-129c696c8f1f)

Steps used to reproduce:

- install mitmproxy
- start `mitmweb -p 8888 --web-port 4444 --mode reverse:http://127.0.0.1:8000`
- open Port 4444 via Port menu (see below)

![image](https://github.com/coder/coder/assets/103434584/29218494-d085-453e-a8fc-1fe1855d4228)

**Comment by SasSwart** [comment]
I've replicated this behaviour using Coder v2.16.0:
![Image](https://github.com/user-attachments/assets/ff47fb68-8ba5-44de-bce7-d4d9dfca4b2f)

However, I've found that the port is in fact being forwarded. The 404 seems to come from mitmproxy itself.

# Summary:
This is likely because of the way that the reverse proxy or ingress controller in front of coder is configured.
If it sets the `X-Real-Ip` header, then mitmweb will respond with a 404. If it does not set that header, you will instead see this 403 response:
![Image](https://github.com/user-attachments/assets/d8904e04-cd72-46e5-a33e-120cd2c5827c)

The issue that the 403 response points to contains an interesting discussion about dns rebinding attacks:
https://github.com/mitmproxy/mitmproxy/issues/3234

If you need to bypass the 403, you can follow some of the advice posted in that issue. They all seem to manually override the Host header to `127.0.0.1` in order to convince mitmproxy to serve the web interface. In certain environments, this would be insecure. It is up to you to determine whether this would be safe in your environment. 

Doing this at the ingress controller level would not work, because Coder relies on that host header. You would have to put something in front of mitmproxy inside the workspace that can override the Host header after coder has routed to the workspace.

# Investigation

I verified that coder does in fact forward the port by looking at mitmweb's logs:
![Image](https://github.com/user-attachments/assets/6173c0fd-dc96-49e0-bd08-d97122107b7b)

The 404 in mitpweb's logs show that it received the request. This verifies that Coder is behaving as it should.

Nevertheless, I wanted to see if I can get mitmweb working over a shared port, so I looked into why it responds with a 404. To do this, I configured socat to forward to mitmproxy's web host and dump the raw request to stdout. I then took that raw request dump and turned it into this curl command:
```
curl -v   -H "Host: 5555--main--testportsharing--sas.coder.<redacted>"   -H "User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/18.0.1 Safari/605.1.15"   -H "Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8"   -H "Accept-Encoding: gzip, deflate, br"   -H "Accept-Language: en-GB,en;q=0.9"   -H "Cookie:"   -H "Priority: u=0, i"   -H "Sec-Fetch-Dest: document"   -H "Sec-Fetch-Mode: navigate"   -H "Sec-Fetch-Site: cross-site"   -H "X-Forwarded-For: 127.0.0.1"   -H "X-Forwarded-Proto: http"   -H "X-Real-Ip: <redacted>"   http://127.0.0.1:5555/
```

Running this command inside the workspace targeting 127.0.0.1 directly still yielded a 404. This is further evidence that the port is in fact being forwarded.

I then removed a header at a time and replayed the request until I got a new response. The header that was responsible is `X-Real-Ip`.

This can all be done on a docker container on a local machine that does not have coder installed at all.

**Comment by leonjza** [comment]
Using `caddy` in a code-server container next to mitmweb, I can "fool" the host header check, but it seems like the websocket fails to connect.

The command looks something like this:

```
caddy reverse-proxy --from :8888 --to localhost:8889 --change-host-header 127.0.0.1
```

**Comment by SasSwart** [comment]
Hi Leon,

Thanks for reporting the web socket issue. I have replicated it. mitmweb does acknowledge the request and according to its logs it responds with either a 400 or a 403 depending on the caddy config. The web socket response code in the browser is [1006](https://github.com/Luka967/websocket-close-codes). Unfortunately mitmweb doesn't want to tell me any more than that about why it's unhappy with the request. I didn't have enough time to get socat in there to actually look at what is being sent to mitmweb. 

I *suspect* that an issue with how TLS is handled somewhere along the chain of reverse proxies results in a failure to upgrade from HTTP[S] to WS[S].

If the web socket is a must have for you, please let me know and I'll try to make some more time for this.

For now my advice is to disable the websocket connection in your mitmweb configuration. Doing so would probably impact convenience, but it will be more predictable than keeping the web socket enabled.

**Comment by leonjza** [comment]
In my scenario, there is no TLS involved. I didn't realise disabling websockets for the webui was an option though! I can't seem to find the flag for that though, any chance you could point me to it?

As an aside, I got a https://github.com/caido/caido instance up in the same code-server container, and that proxies fine. I'm not too keen on it though based on what seems like a tight coupling to a cloud component.

**Comment by SasSwart** [comment]
Thanks for the information on caido. In contrast to it, mitmweb seems to be quite specific with how it wants to be proxied to. [I've asked them about this](https://github.com/mitmproxy/mitmproxy/issues/6449#issuecomment-2441425322). It should be possible to configure a reverse proxy to send on the websocket request in a way that mitmweb approves of. I'll need to explore its codebase to see what it needs. I would love to do this once I can allocate some capacity to it.

As for the websocket option, I was mistaken. This is the option that I was referring to:
https://docs.mitmproxy.org/stable/concepts-options/#websocket
It seems to be about websocket support for the proxy component, not the web ui component. Apologies.

**Comment by leonjza** [comment]
Ah no worries. Thanks for checking!

**Comment by SasSwart** [comment]
Update:

The maintainer of mitmproxy has stated that we should now be able to host it under arbitrary domains:
https://github.com/mitmproxy/mitmproxy/issues/6449#issuecomment-2643554911

This means we should be able to access mitmweb using Coder's port forwarding.
I'll test this in the week and revert back here.

**Comment by MrPeacockNLB** [comment]
@SasSwart thank for further investigating!

I can confirm that I'm able to open up the UI via port forwarding.

![Image](https://github.com/user-attachments/assets/8cfd0dd4-a91b-48be-8db5-1605a608dbc6)

But the provided link in the web terminal is not able to capture the needed token so one has to copy it by hand. I'll create a separate issue regarding this topic.
