### ISSUE TITLE
template insights: show data for older than 30 days

### ISSUE THREAD

**Issue by matifali** [coder/coder#9301]
## Problem
![image](https://github.com/coder/coder/assets/10648092/ae660001-75ea-4c8c-b101-45290bdc8fd1)
## Suggested solution
Either show all historical data as per the selected range
or
limit the date selection as per available data.

**Comment by bpmct** [comment]
@mafredri is this a one-time thing because the feature is new, or can we anticipate insights to only go back 30 days moving forward?

**Comment by mafredri** [comment]
@bpmct this happens because we purge agent statistics after ~1 month, which I didn't know about when I started working on the feature.

So as suggested in this issue, we should apply one of the proposals, or I can think of a third too:

1. Limit the date picker to one month (easiest)
2. Keep agent stats for longer (there's still an upper limit, but we write a lot of "zero" agent stats and if we filtered those, we could keep the data for 3 - 6 months instead without a big increase in size
3. In coderd, periodically query the daily stats and write them to a new table, this new table is then always used for the stats (this limits our options in the future, we can't increase granularity and may not be able to add new data points retroactively)

PS. We currently don't delete workspace app stats, so eventually when people have used v2.1.1+ for >1 month, these graphs will start showing partial data based on those. This would not be ideal and we should amend this in some way before that happens.

**Comment by bpmct** [comment]
Gotcha! I think option 2 is the best for us (extending the retention window to 6 months). A few reasons:

- I think it is fair for insights to be used for an "at-glance snapshot" of the template usage, growth, etc. GitHub only persists data for 14 days, but I think we want to show more in Coder to highlight adoption over time.
- We may want to show weekly active users charts to show growth over a longer period of time and 1 month is too small for that: #9495
- Customers can use our API (and we should support Prometheus exports) so they can do more granular queries or save historical data

**Comment by BrunoQuaresma** [comment]
Just checking, is this a BE limitation? cc.: @mafredri

**Comment by mafredri** [comment]
@BrunoQuaresma will be fixed by #12122.

**Comment by mafredri** [comment]
This has been fixed by recent commits to `main`, as part of #12122. We can't create insights beyond 6 months currently, but as time progresses so will the range.
