### ISSUE TITLE
Why is role sync needed for `CODER_OIDC_USER_ROLE_DEFAULT`

### ISSUE THREAD

**Issue by bpmct** [coder/coder#9310]
There are some use cases for setting a default role for a Coder deployment:
- Heavy trust and collaboration (everyone can modify templates)
- Staging environments for debugging (everyone is Owner)

The `CODER_OIDC_USER_ROLE_DEFAULT` feature is cool for this, but I'm not sure why it requires an enterprise license or for role sync to be enabled. Could we make this not rely on role sync to set the default role for OIDC users?

**Comment by Emyrk** [comment]
@bpmct unfortunately this gets a bit tricky without role sync. 

With role sync enabled, it disables all manual role editing. So we can assume all the roles assigned to a user come from the IDP source of truth. 

If you allow manual editing, then having default roles means we also need to implement some feature to disable removing certain roles, but not others. Because removing a default role should probably fail?

So tl'dr, with role sync this behavior is just more straight forward with less edge cases.

-----


Not saying we cannot do this, it just brings in some behaviors we need to define.

**Comment by bpmct** [comment]
Totally makes sense, thanks for clarifying!
