### ISSUE TITLE
Web terminal does not render correctly when `screen` is present

### ISSUE THREAD

**Issue by mafredri** [coder/coder#9343]
When the reconnecting-pty uses the screen backend, the web terminal doesn't render all characters for me:

incorrect:

<img width="900" alt="image" src="https://github.com/coder/coder/assets/147409/7aa01902-2381-44f8-97f6-7200bafa4975">

vs (correct, after `apt remove screen`):

<img width="900" alt="image" src="https://github.com/coder/coder/assets/147409/f78571ab-8af3-4399-b3ad-f63c4b92a1a1">

The missing characters are `❯` and `⇣`.

**Comment by code-asher** [comment]
Does resizing the window also fix it?  I have been seeing rendering glitches that seem to occur from the size not actually being set, so screen and xterm are operating on different screen sizes.

Here we set the size, seems to not working though:
https://github.com/coder/coder/blob/225cf8acec2ba12bbb94cd3190b07b608cfb555e/agent/reconnectingpty/screen.go#L226-L227

**Comment by matifali** [comment]
@mafredri moving it to `s2` as the uninstalling `screen` is a workaround.

**Comment by code-asher** [comment]
@matifali I am going to re-open the other issue and assign to myself because it looks to be a different issue (related to the size issue I mentioned, as far as my investigation has revealed).

As for this issue, it seems screen does not support UTF-8 by default but it can be fixed by exporting something like `LANG=C.UTF-8` or launching screen with `-U` (and maybe some other ways).  I am not sure what the best method is but I think I will go with `-U` since I am not sure if we can reasonably set a default for `LANG`.
