### ISSUE TITLE
Link to existing workspaces when you can't delete a template

### ISSUE THREAD

**Issue by bpmct** [coder/coder#9348]
## Background

You cannot delete a template if there existing workspaces

## Current behavior

The user sees the error and then manually has to navigate to the workspace search to delete workspaces

https://github.com/coder/coder/assets/22407953/a2fe49fe-c76b-4238-a1f2-2a15e9479d91

## Desired behavior

With one click, a user can click to see all of the workspaces using a template to bulk delete

**Comment by matifali** [comment]
This is related to a request in #9473 to allow deleting a template along with all it's workspace in bulk. 

As we already have bulk deleting capability now. I guess a simple implementation can be 
1. A user selects the template and tries to delete
2. We show them a message that there are workspace created from this template
3. We add a checkbox that says "delete all workspaces"
4. If user selects that checkbox, we select all workspace with that template as filter and issue a bulk delete command. 

Thoughts @BrunoQuaresma @bpmct 

PS:
It can be done manually quite easily but that includes manual steps
1. Go to workspace page
2. Filter for all workspace of the template ro be deleted
3. Select all and delete
4. Go back to template page
5. Select the template and complete deletion

**Comment by bpmct** [comment]
I'd be open to this, although it may be better for us to provide a link that helps with steps "Go to workspace page," "Filter for all workspace of the template to be deleted" to ensure the admin manually reviews the workspaces that are being deleted, to avoid disrupting users. Will defer to Bruno here!

**Comment by matifali** [comment]
@bpmct I guess you mean this workflow

> It can be done manually quite easily, but that includes manual steps
> 1. Go to workspace page
> 2. Filter for all workspace of the template to be deleted
> 3. Select all and delete
> 4. Go back to the template page
> 5. Select the template and complete the deletion

**Comment by BrunoQuaresma** [comment]
Since the bulk deletion feature is enterprise and unavailable for all the accounts, we could have a link "See all the existent workspaces for this template" redirecting the user to the workspaces page filtered by the template. Thoughts?

**Comment by matifali** [comment]
@BrunoQuaresma, I like it.

**Comment by BrunoQuaresma** [comment]
> The deletion box and delete button should actually be hidden completely. Don't even give the user the chance to try a deletion that will fail anyway

By doing that, the user has no chance to understand why it is happening. 

> Instead show a message that tells them they have workspaces that need to be deleted, as well as a link that:

I would not redirect the user directly without their knowing why. Showing a message like "You are not able to delete this template because there are workspaces using it. [See all workspaces using this template]" looks like a better and more predictive option IMO

> If a user has access to bulk-deletion, would you also like some kind of button/input to be made visible alongside the link?

I didn't understand this part.

**Comment by Parkreiner** [comment]
Oh, sorry. That was a part I omitted. Basically, the way I'm thinking about it is that there's two states the modal could be in:
1. There are workspaces linked to the template
2. There aren't

If there aren't any, we just use the same UI as before, and the experience doesn't change.

But if there are, the following would change:
1. The text input and delete button disappear
2. A new message appears (styled as a warning) saying that the user has workspaces. Inside that message is a link to the workspaces page, but the link also has search params set, so the user will see the workspaces linked to the template the moment they navigate. None of this is automatic – the user has to initiate everything

And then for the other question, basically, I'm wondering if it's worth trying to reduce friction further if the user has access to bulk-deletion. As in, rather than making them jump to the workspaces page, add one extra element/input set that lets the user do the bulk deletion directly from the modal. I do think that there's such a thing as too little friction (especially for destructive actions), though, so I'm not sure if this might be going too far
