### ISSUE TITLE
site: stopped scripts/develop.sh results in the site error

### ISSUE THREAD

**Issue by mtojek** [coder/coder#9527]
When a developer stops the `./scripts/develop.sh`, the browser reacts with an error:

<img width="1509" alt="Screenshot 2023-09-05 at 12 32 46" src="https://github.com/coder/coder/assets/14044910/0898a40f-2e19-426a-8cfe-d2247ef6a2e9">

Maybe it is possible to present something user-friendly?

**Comment by Emyrk** [comment]
Is this because all http requests fail?

**Comment by mtojek** [comment]
Hey @Parkreiner, as the issue was marked as a weekly commitment last Monday, and you unassigned yourself, do you still want to look into this or should we look for somebody else?

**Comment by Parkreiner** [comment]
Sorry about the confusion – I can take care of it this week.

**Comment by Parkreiner** [comment]
@mtojek I know it's been a while, but do you remember what exactly you did to produce the issue? Similarly, have you noticed the issue happening ever since we had the migration from XState to React Query?

I've been trying to replicate the issue, and I just haven't been able to force an error for any of the pages. This is the main process I've tried:

1. Boot up the server and UI using the development Bash script
2. Navigate to either localhost:3000 or localhost:8080 (tried both – it didn't seem to make any difference)
3. Navigate to a few different pages, just to make sure as many of them were lazy-loaded as possible
4. Kill the server
5. Try navigating around the app, interacting with the UI elements that rely on data fetching, and just trying to break the UI

It's been really resilient so far – no error messages in the UI.

I have to wonder if the RQ migration might have inadvertently solved this, since it's more tailored to querying than XState was. The first RQ PR was submitted seven days after this issue was opened, so at the very least, the timelines seem believable

**Comment by Parkreiner** [comment]
@BrunoQuaresma How did we have XState's data fetching set up previously? I know that if RQ encounters an error, it will generally hold on to the previous data while trying to retry the fetches. If XState ran into an error with a fetch, did the previous data immediately get vacated?

**Comment by mtojek** [comment]
This might be a reason why I don't see this error again. I can see the friendly message now: `Something went wrong.
Please check the developer console for more details.`, which is absolutely fine!

I believe that we don't need to take any more actions here, so feel free to resolve the issue. Thanks for investigating it.
