### ISSUE TITLE
feature request: Coder port forward using suddirectory instead of subdomain

### ISSUE THREAD

**Issue by gburiola** [coder/coder#9845]
Hello

At the moment, coder port forward via the UI dashboard uses subdomain in the following format

```
https://<PORT>-<ENV_NAME>-<USERNAME>.coder.company.internal
```

That means it requires a wildcard SSL certificate as well as a wildcard DNS.

Some companies do not allow wildcard SSL certificates and/or wildcard DNS entries.

Would it be possible to have port forwarding via the UI dashboard using a subdirectory instead? Something like:

```
https://coder.company.internal/port-forward/<PORT>-<ENV_NAME>-<USERNAME>
```

thanks

**Comment by MrPeacockNLB** [comment]
This should also fix the double dashes problem with owasp rule for sql injection. I'm pritty sure we have to disable this rule. Accessing Application via sub path should be possible too.

**Comment by kylecarbs** [comment]
Could you use our existing path-based routing instead?

Going to close for now until we get a response from someone, but will happily reopen!

**Comment by gburiola** [comment]
Hi @kylecarbs, thanks for getting back to me.

Could you please point me to the documentation on how to set up path-based routing? I couldn't find it on https://coder.com/docs/v2/latest/networking/port-forwarding#dashboard

The doc above for **UI port-forwarding (dashboard)** still says wildcard SSL / DNS is a requirement.

**Comment by JustSch** [comment]
From my experience coder (and VSCode) tends to automatically forward ports to 
 ```
https://<ENV_NAME>-<USERNAME>.coder.company.internal/proxy/<PORT>
``` 
(I tried to copy the url format from your first post)

where
 ```
/proxy/<PORT>
``` 
is appended to the workspace url.


There was a bug that had prevented this from working in coder but it has  been fixed since https://github.com/coder/coder/pull/11759 . It does not require a wildcard access url to be set.

I could not find documentation for this in the coder docs but this behavior may be documented in the VSCode docs since it works similarly

**Comment by kylecarbs** [comment]
@gburiola ahh, my bad. We don't support path-based port routing directly, but you can add a `coder_app` that is predefined to route any port.
