### ISSUE TITLE
Audit logs: IP is missing/nil for `workspace_build` events

### ISSUE THREAD

**Issue by denbeigh2000** [coder/coder#9867]
Currently, in audit log entries for `workspace_build` events, `<nil>` is currently set for `Ip` values, when it should contain the IP the request came from.

Here is a sample of what is currently seen:
![Screenshot_2023-09-25_at_13 58 03](https://github.com/coder/coder/assets/1646744/bc71e294-0cef-405f-bb46-499835bf0562)

Instead of `<nil>`, I would expect this field to contain the IP address of the actor that invoked the action.

Observed on `v2.1.5+66019ef`.

**Comment by kylecarbs** [comment]
We shall fix this. Thank you @denbeigh2000!

**Comment by Emyrk** [comment]
This is going to require adding the IP meta data to the job

**Comment by Emyrk** [comment]
@coadler would using `TraceMetadata` not be the move here?

It seems to be for OTEL tracing: https://github.com/coder/coder/blob/ff73baba92904f631f05d07cfb64fb5826a90698/coderd/tracing/util.go#L47-L56

But since it's used to track the request cycle, it would be nice if we could extend the context for some coder specific tracing props.
