### ISSUE TITLE
Breaking API changes in agents and provisioners  

### ISSUE THREAD

**Issue by mtojek** [coder/coder#9984]
The goal of this issue is to enhance the awareness of Coder administrators regarding potential API compatibility concerns. Coder administrators should have the capability to promptly recognize outdated agents and provisioners with incompatible APIs and take action to update them.

_This issue requires further refinement._

**Comment by spikecurtis** [comment]
We already detect the Agent version, and warn on the workspace page if the agent isn't the same version as coderd.

We could enhance the frontend to allow administrators to see which workspaces have outdated agents across the whole fleet (e.g. a new filter on the workspaces page).

We don't currently have a mechanism for checking whether the version is compatible or not. The Coder version is formatted like a semantic version, but we don't actually follow SemVer on when to update the major, minor and patch versions, so we can't do a semantic comparison of versions to figure out compatibility.  We'd have to either define a new "agent API" version that we do follow SemVer on, or use a lookup table/custom logic to find incompatible versions.

Right now the agent version is included in `PostStartup()`, which isn't a great place for checking for incompatibility, since at present API calls to get the service banner and manifest have to succeed first, and these could be incompatible and fail. 

One other edge case is that the Agent makes multiple API calls that could be routed by a load balancer to different Coderd  instances with potentially different versions, so passing a version check initially doesn't guarantee that you'll later connect to a coderd with a compatible version.  This is primarily an issue during Coderd upgrades.

If an agent is found to be incompatible, then the correct course of action is almost always to rebuild the workspace.  We could trigger this automatically when an incompatible agent is detected.

**Comment by mtojek** [comment]
ping @bpmct

I would identify quick wins first, and prepare a long-term plan for others. As a quick win, we could start with better observability:

> We could enhance the frontend to allow administrators to see which workspaces have outdated agents across the whole fleet (e.g. a new filter on the workspaces page).

👍 New filter or a dedicated cluster overview for admins

> One other edge case is that the Agent makes multiple API calls that could be routed by a load balancer to different Coderd instances with potentially different versions, so passing a version check initially doesn't guarantee that you'll later connect to a coderd with a compatible version. This is primarily an issue during Coderd upgrades.
 
Should we store the information about the newest replica or all replicas in the database? In theory, that could help admins perform the deployment update and see outdated agents. 

> We'd have to either define a new "agent API" version that we do follow SemVer on, or use a lookup table/custom logic to find incompatible versions.

I like the SemVer rules, and most likely we should not be hesitant to use them from time to time. Today we're breaking the API silently, and I agree that it would be more transparent to have `v2.1`, `v2.2`, etc. (if we don't want to go with `v3`, `v4`).

 Maybe RFC first?

**Comment by spikecurtis** [comment]
I think it's a pipe dream to apply SemVer to the whole product. Enterprise customers have _feelings_ about major version bumps.

But, we could assign semantic versions to particular APIs or the API as a whole.

**Comment by spikecurtis** [comment]
Provisioner daemons have a well defined dRPC API that operates over a single websocket.  This means we don't need to worry about RPCs hitting an incompatible Coderd instance once an initial version check succeeds.

Right now, Provisioner daemons don't send a version, but it would be straightforward to include in the initial HTTP-handshake of the websocket protocol.  We have the same issues as agents regarding whether to use the main Coder version (which is not semantic) or defining a new semantic "Provisioner daemon API" version to calculate compatibility.

Right now we don't track the lifecycle of Provisioner daemon instances in the database, so we don't have anywhere to store their versions to surface on the frontend.

When external provisioner daemons are on an old or incompatible version, the best we can do in Coderd is warn about it, since they are themselves provisioned outside of Coder.

**Comment by spikecurtis** [comment]
[Link to the (internal) RFC](https://www.notion.so/coderhq/API-Changes-Back-Compatibility-36e779e691e140d4a3dcb78700c6d0bf)

**Comment by spikecurtis** [comment]
RFC approved.
